// @generated by @pattern-stack/codegen from test/fixtures/demo-deal.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Deals tRPC Router
 * Generated by entity codegen - do not edit directly
 *
 * Add this router to TrpcModule providers:
 *   providers: [..., DealsRouter],
 */

import { Injectable } from '@nestjs/common';
import { Router, Query, Mutation, Input } from '@mguay/nestjs-trpc';
import { z } from 'zod';
import {
	createDealSchema,
	updateDealSchema,
} from '../../application/schemas';
import { GetDealByIdQuery } from '../../application/queries/deal/get-by-id.query';
import { ListDealsQuery } from '../../application/queries/deal/list.query';
import { CreateDealCommand } from '../../application/commands/deal/create.command';
import { UpdateDealCommand } from '../../application/commands/deal/update.command';
import { DeleteDealCommand } from '../../application/commands/deal/delete.command';

@Injectable()
@Router({ alias: 'deals' })
export class DealsRouter {
	constructor(
		private readonly getDealById: GetDealByIdQuery,
		private readonly listDeals: ListDealsQuery,
		private readonly createDeal: CreateDealCommand,
		private readonly updateDeal: UpdateDealCommand,
		private readonly deleteDeal: DeleteDealCommand,
	) {}

	@Query()
	async list() {
		return this.listDeals.execute();
	}

	@Query({ input: z.object({ id: z.string().uuid() }) })
	async getById(@Input('id') id: string) {
		return this.getDealById.execute(id);
	}

	@Mutation({ input: createDealSchema })
	async create(@Input() input: z.infer<typeof createDealSchema>) {
		return this.createDeal.execute(input);
	}

	@Mutation({ input: z.object({ id: z.string().uuid(), data: updateDealSchema }) })
	async update(
		@Input('id') id: string,
		@Input('data') data: z.infer<typeof updateDealSchema>,
	) {
		return this.updateDeal.execute(id, data);
	}

	@Mutation({ input: z.object({ id: z.string().uuid() }) })
	async delete(@Input('id') id: string) {
		return this.deleteDeal.execute(id);
	}
}
