/**
 * Organizations tRPC Router
 * Generated by entity codegen - do not edit directly
 *
 * Add this router to TrpcModule providers:
 *   providers: [..., OrganizationsRouter],
 */

import { Injectable } from '@nestjs/common';
import { Router, Query, Mutation, Input } from '@mguay/nestjs-trpc';
import { z } from 'zod';
import {
	createOrganizationSchema,
	updateOrganizationSchema,
} from '../../application/schemas';
import { GetOrganizationByIdQuery } from '../../application/queries/organization/get-by-id.query';
import { ListOrganizationsQuery } from '../../application/queries/organization/list.query';
import { CreateOrganizationCommand } from '../../application/commands/organization/create.command';
import { UpdateOrganizationCommand } from '../../application/commands/organization/update.command';
import { DeleteOrganizationCommand } from '../../application/commands/organization/delete.command';

@Injectable()
@Router({ alias: 'organizations' })
export class OrganizationsRouter {
	constructor(
		private readonly getOrganizationById: GetOrganizationByIdQuery,
		private readonly listOrganizations: ListOrganizationsQuery,
		private readonly createOrganization: CreateOrganizationCommand,
		private readonly updateOrganization: UpdateOrganizationCommand,
		private readonly deleteOrganization: DeleteOrganizationCommand,
	) {}

	@Query()
	async list() {
		return this.listOrganizations.execute();
	}

	@Query({ input: z.object({ id: z.string().uuid() }) })
	async getById(@Input('id') id: string) {
		return this.getOrganizationById.execute(id);
	}

	@Mutation({ input: createOrganizationSchema })
	async create(@Input() input: z.infer<typeof createOrganizationSchema>) {
		return this.createOrganization.execute(input);
	}

	@Mutation({ input: z.object({ id: z.string().uuid(), data: updateOrganizationSchema }) })
	async update(
		@Input('id') id: string,
		@Input('data') data: z.infer<typeof updateOrganizationSchema>,
	) {
		return this.updateOrganization.execute(id, data);
	}

	@Mutation({ input: z.object({ id: z.string().uuid() }) })
	async delete(@Input('id') id: string) {
		return this.deleteOrganization.execute(id);
	}
}
