/**
 * Semantic emitter — renders `model.ts` (SEM-2, ADR-045).
 *
 * Printing only. Every mapping decision was already made in `build-model.ts`;
 * this file turns a {@link SemanticModel} into source text. Output is
 * deterministic for a given model — the builder has already imposed a total
 * order — so re-running is byte-identical (charter I2).
 */

import type {
	DerivedExprNode,
	SemanticEntity,
	SemanticField,
	SemanticMetric,
	SemanticModel,
	SemanticRelationship,
} from './types';

export const GENERATED_BANNER = `// @generated by @pattern-stack/codegen — do not edit.
// Regenerate with \`codegen entity new --all\` (requires generate.semantic: true).

`;

/**
 * The semantic-query package the emitted model imports from — named ONCE. It
 * supplies the vocabulary types and one value, `measuresFromRegistry` (#734).
 * An optional peer of `@pattern-stack/codegen` that a project with
 * `generate.semantic: true` installs (SEM-4, #694).
 * `src/__tests__/emitters/semantic/emit-model.test.ts` pins that no other
 * import specifier is hard-coded.
 */
export const QUERY_SURFACE_MODULE = '@pattern-stack/query-surface';

export const SEMANTIC_MODEL_FILE = 'model.ts';

/** A JS string literal, single-quoted, with the obvious escapes. */
function str(value: string): string {
	return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/** An object key: bare when it is a valid identifier, quoted otherwise. */
function key(name: string): string {
	return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : str(name);
}

function renderField(field: SemanticField): string {
	const parts = [`type: ${str(field.type)}`];
	if (field.role !== undefined) parts.push(`role: ${str(field.role)}`);
	if (field.agg !== undefined) parts.push(`agg: ${str(field.agg)}`);
	if (field.aggs !== undefined) {
		parts.push(`aggs: [${field.aggs.map(str).join(', ')}]`);
	}
	if (field.additivity !== undefined) parts.push(`additivity: ${str(field.additivity)}`);
	if (field.time !== undefined) parts.push(`time: ${String(field.time)}`);
	parts.push(`column: ${str(field.column)}`);
	if (field.hasDeclaredDomain !== undefined) {
		parts.push(`hasDeclaredDomain: ${String(field.hasDeclaredDomain)}`);
	}
	return `{ ${parts.join(', ')} }`;
}

function renderRelationship(rel: SemanticRelationship): string {
	return `{ kind: ${str(rel.kind)}, target: ${str(rel.target)}, fk: ${str(rel.fk)} }`;
}

function renderExpr(node: DerivedExprNode): string {
	if ('ref' in node) return `{ ref: ${str(node.ref)} }`;
	if ('lit' in node) return `{ lit: ${String(node.lit)} }`;
	return `{ op: ${str(node.op)}, left: ${renderExpr(node.left)}, right: ${renderExpr(node.right)} }`;
}

function renderMetric(metric: SemanticMetric): string {
	const label = metric.label !== undefined ? `, label: ${str(metric.label)}` : '';
	switch (metric.kind) {
		case 'ratio':
			return `{ kind: 'ratio', numerator: ${str(metric.numerator)}, denominator: ${str(metric.denominator)}${label} }`;
		case 'derived':
			return `{ kind: 'derived', expr: ${renderExpr(metric.expr)}${label} }`;
		case 'cumulative': {
			const partition =
				metric.partition_by !== undefined
					? `, partition_by: ${str(metric.partition_by)}`
					: '';
			return `{ kind: 'cumulative', measure: ${str(metric.measure)}, order_by: ${str(metric.order_by)}${partition}${label} }`;
		}
	}
}

function renderTables(entities: SemanticEntity[]): string {
	const lines = entities.map((e) => `\t${key(e.name)}: schema.${e.tableVar},`);
	return `const tables: Record<string, PgTable> = {\n${lines.join('\n')}\n};\n`;
}

/**
 * A junction's key is composite and the package's descriptor holds one column,
 * so the emitted `'id'` names no column. Say so where it is printed (#689).
 */
function compositeKeyNote(entity: SemanticEntity): string[] {
	if (!entity.compositeKey) return [];
	return [
		`\t\t// Composite key (${entity.compositeKey.join(', ')}); a junction has no \`id\` column.`,
		`\t\t// A single-column key cannot express it, so this fails loudly if read (#689).`,
	];
}

function renderRegistry(entities: SemanticEntity[]): string {
	const blocks = entities.map((entity) => {
		const rels = Object.entries(entity.relationships).map(
			([name, rel]) => `\t\t\t${key(name)}: ${renderRelationship(rel)},`,
		);
		const relBody = rels.length > 0 ? `{\n${rels.join('\n')}\n\t\t}` : '{}';
		const searchable =
			entity.searchableColumns.length > 0
				? `[${entity.searchableColumns.map(str).join(', ')}]`
				: '[]';
		return [
			`\t${key(entity.name)}: {`,
			`\t\tname: ${str(entity.name)},`,
			`\t\ttable: tables[${str(entity.name)}]!,`,
			...compositeKeyNote(entity),
			`\t\tprimaryKey: ${str(entity.primaryKey)},`,
			`\t\tcolumns: columnsByProp[${str(entity.name)}]!,`,
			`\t\trelationships: ${relBody},`,
			`\t\tsearchableColumns: ${searchable},`,
			`\t\tmeta: { kind: ${str(entity.kind)} },`,
			`\t},`,
		].join('\n');
	});
	return `const registry: Record<string, EntityDescriptor> = {\n${blocks.join('\n')}\n};\n`;
}

function renderAnalytics(entities: SemanticEntity[]): string {
	const blocks = entities.map((entity) => {
		const rels = Object.entries(entity.relationships).map(
			([name, rel]) => `\t\t\t${key(name)}: ${renderRelationship(rel)},`,
		);
		const relBody = rels.length > 0 ? `{\n${rels.join('\n')}\n\t\t}` : '{}';
		const fields = Object.entries(entity.fields).map(
			([name, field]) => `\t\t\t${key(name)}: ${renderField(field)},`,
		);
		const fieldBody = fields.length > 0 ? `{\n${fields.join('\n')}\n\t\t}` : '{}';
		return [
			`\t${key(entity.name)}: {`,
			`\t\ttable: ${str(entity.tableName)},`,
			...compositeKeyNote(entity),
			`\t\tpk: ${str(entity.primaryKey)},`,
			`\t\trels: ${relBody},`,
			`\t\tfields: ${fieldBody},`,
			`\t},`,
		].join('\n');
	});
	return `const analytics: AggRegistry = {\n${blocks.join('\n')}\n};\n`;
}

/**
 * The composites from `analytics.metrics:` — the only catalog entries the
 * emitter writes. The atomic ones come from the package at call time; see
 * {@link BUILD_AGGREGATE_MODEL}.
 */
function renderComposites(metrics: SemanticMetric[]): string {
	if (metrics.length === 0) {
		return `// No composite metrics declared.
const composites: MeasureCatalog = {};\n`;
	}
	const lines = metrics.map((m) => `\t${key(m.name)}: ${renderMetric(m)},`);
	return `// Composite metrics from \`analytics.metrics:\`.
const composites: MeasureCatalog = {\n${lines.join('\n')}\n};\n`;
}

/**
 * The model's one export, the same for every entity set.
 *
 * `catalog` is the package's own `measuresFromRegistry(analytics)` with the
 * composites over it (#734). The engine resolves a `{ ref }` only from
 * `model.catalog` and never derives atomic entries itself, so they must be in
 * it — but the tag → `<field>.<agg>` rule belongs to the package, so the model
 * emits a CALL, never the entries (ADR-045, 2026-10-04 revision). Validation
 * already refuses a metric named like a derived measure, so the spread order
 * shadows nothing.
 */
const BUILD_AGGREGATE_MODEL = `
/**
 * The declared semantic model for this schema.
 *
 * A function, not a const: it reads \`getColumns\` at call time, so importing
 * this module before the schema barrel is fully initialised is safe.
 */
export function buildAggregateModel(): AggregateModel {
	// Atomic measures are derived by the package from the \`role: 'measure'\`
	// tags above — one owner of that rule; the composites are declared here.
	const catalog: MeasureCatalog = { ...measuresFromRegistry(analytics), ...composites };
	return { registry, analytics, tables, colByDbName, catalog };
}
`;

/** Render the whole `model.ts`. */
export function buildSemanticModelSource(model: SemanticModel): string {
	const header = `${GENERATED_BANNER}import { getColumns } from 'drizzle-orm';
import type { PgColumn, PgTable } from 'drizzle-orm/pg-core';

import * as schema from '../schema';
import {
	measuresFromRegistry,
	type AggRegistry,
	type AggregateModel,
	type EntityDescriptor,
	type MeasureCatalog,
} from ${str(QUERY_SURFACE_MODULE)};

`;

	if (model.entities.length === 0) {
		return `${header}const tables: Record<string, PgTable> = {};
const colByDbName: Record<string, Record<string, PgColumn>> = {};
const registry: Record<string, EntityDescriptor> = {};
const analytics: AggRegistry = {};
${renderComposites(model.metrics)}${BUILD_AGGREGATE_MODEL}`;
	}

	const derived = `// The ONE place a Drizzle object is read: \`PgColumn\` references cannot be
// written down in YAML. Everything else above is declared.
const columnsByProp: Record<string, Record<string, PgColumn>> = Object.fromEntries(
	Object.entries(tables).map(([name, table]) => [
		name,
		getColumns(table) as unknown as Record<string, PgColumn>,
	]),
);

const colByDbName: Record<string, Record<string, PgColumn>> = Object.fromEntries(
	Object.entries(columnsByProp).map(([name, columns]) => [
		name,
		Object.fromEntries(Object.values(columns).map((column) => [column.name, column])),
	]),
);

`;

	return [
		header,
		renderTables(model.entities),
		'\n',
		derived,
		renderRegistry(model.entities),
		'\n',
		renderAnalytics(model.entities),
		'\n',
		renderComposites(model.metrics),
		BUILD_AGGREGATE_MODEL,
	].join('');
}
