---
to: "<%= exposeRest ? `${basePaths.backendSrc}/${paths.controllers}/${plural}.controller.ts` : '' %>"
force: true
---
<% if (exposeRest) { -%>
/**
 * <%= classNamePlural %> Controller
 * Generated by entity codegen - do not edit directly
 */

import {
	Body,
	Controller,
	Delete,
	Get,
	Param,
	ParseUUIDPipe,
	Post,
	Put,
<% if (hasRelationships) { -%>
	Query,
<% } -%>
	UsePipes,
} from '@nestjs/common';
import { Get<%= className %>ByIdQuery } from '<%= imports.controllerToGetByIdQuery %>';
import { List<%= classNamePlural %>Query } from '<%= imports.controllerToListQuery %>';
import {
	type Create<%= className %>Dto,
	create<%= className %>Schema,
	type Update<%= className %>Dto,
	update<%= className %>Schema,
} from '../../application/schemas';
import { Create<%= className %>Command } from '<%= imports.controllerToCreateCommand %>';
import { Delete<%= className %>Command } from '<%= imports.controllerToDeleteCommand %>';
import { Update<%= className %>Command } from '<%= imports.controllerToUpdateCommand %>';
import { ZodValidationPipe } from '../../core/pipes/zod-validation.pipe';
import { <%= className %> } from '../../domain';
<% if (hasRelationships) { -%>
import type { <%= className %>With } from '../../domain';
<% } -%>

@Controller('<%= plural %>')
export class <%= classNamePlural %>Controller {
	constructor(
		private readonly get<%= className %>ByIdQuery: Get<%= className %>ByIdQuery,
		private readonly list<%= classNamePlural %>Query: List<%= classNamePlural %>Query,
		private readonly create<%= className %>Command: Create<%= className %>Command,
		private readonly update<%= className %>Command: Update<%= className %>Command,
		private readonly delete<%= className %>Command: Delete<%= className %>Command,
	) {}

	@Get()
	async findAll(<%- hasRelationships ? `@Query('include') include?: string` : '' %>): Promise<<%= className %>[]> {
<% if (hasRelationships) { -%>
		return this.list<%= classNamePlural %>Query.execute(this.parseInclude(include));
<% } else { -%>
		return this.list<%= classNamePlural %>Query.execute();
<% } -%>
	}

	@Get(':id')
	async findById(
		@Param('id', ParseUUIDPipe) id: string,
<% if (hasRelationships) { -%>
		@Query('include') include?: string,
<% } -%>
	): Promise<<%= className %>> {
<% if (hasRelationships) { -%>
		return this.get<%= className %>ByIdQuery.execute(id, this.parseInclude(include));
<% } else { -%>
		return this.get<%= className %>ByIdQuery.execute(id);
<% } -%>
	}

	@Post()
	@UsePipes(new ZodValidationPipe(create<%= className %>Schema))
	async create(@Body() dto: Create<%= className %>Dto): Promise<<%= className %>> {
		return this.create<%= className %>Command.execute(dto);
	}

	@Put(':id')
	async update(
		@Param('id', ParseUUIDPipe) id: string,
		@Body(new ZodValidationPipe(update<%= className %>Schema)) dto: Update<%= className %>Dto,
	): Promise<<%= className %>> {
		return this.update<%= className %>Command.execute(id, dto);
	}

	@Delete(':id')
	async delete(@Param('id', ParseUUIDPipe) id: string): Promise<<%= className %>> {
		return this.delete<%= className %>Command.execute(id);
	}
<% if (hasRelationships) { -%>

	/**
	 * Parse comma-separated include query param into typed options.
	 * Example: ?include=account,owner → { account: true, owner: true }
	 */
	private parseInclude(include?: string): <%= className %>With | undefined {
		if (!include) return undefined;
		const parts = include.split(',').map((s) => s.trim());
		return {
<% relationships.forEach((rel) => { -%>
			<%= rel.name %>: parts.includes('<%= rel.name %>'),
<% }) -%>
		};
	}
<% } -%>
}
<% } -%>
