---
to: "<%= (exposeRest || exposeElectric) ? `${basePaths.backendSrc}/${paths.controllers}/${plural}.controller.ts` : '' %>"
skip_if: <%= !isCleanArchitecture %>
force: true
---
<% if (exposeRest) { -%>
/**
 * <%= classNamePlural %> Controller
 * Generated by entity codegen - do not edit directly
 */

import {
	Body,
	Controller,
	Delete,
	Get,
	Headers,
	Param,
	ParseUUIDPipe,
	Post,
	Put,
	UsePipes,
} from '@nestjs/common';
import {
	ApiBearerAuth,
	ApiBody,
	ApiOperation,
	ApiParam,
	ApiResponse,
} from '@nestjs/swagger';
import { <%= getByIdQueryClass %> } from '<%= imports.controllerToGetByIdQuery %>';
import { <%= listQueryClass %> } from '<%= imports.controllerToListQuery %>';
import {
	type Create<%= className %>Dto,
	create<%= className %>Schema,
	type Update<%= className %>Dto,
	update<%= className %>Schema,
} from '<%= imports.controllerToSchemas %>';
import { <%= createCommandClass %> } from '<%= imports.controllerToCreateCommand %>';
import { <%= deleteCommandClass %> } from '<%= imports.controllerToDeleteCommand %>';
import { <%= updateCommandClass %> } from '<%= imports.controllerToUpdateCommand %>';
import { ZodValidationPipe } from '../../core/pipes/zod-validation.pipe';
import { <%= className %> } from '<%= imports.controllerToDomain %>';

// OPENAPI-3: controller decorators reference schemas by `$ref` rather
// than `type:` class references because generated DTOs are Zod-derived
// types (not NestJS classes). Schemas are registered by name in the
// `OpenApiRegistry` at onModuleInit (OPENAPI-2); these `$ref` URIs point
// at those registered entries. `ErrorResponseDto` is auto-registered by
// the shared registry.
@ApiBearerAuth()
@Controller('<%= plural %>')
export class <%= classNamePlural %>Controller {
	constructor(
		private readonly get<%= className %>ByIdQuery: <%= getByIdQueryClass %>,
		private readonly list<%= classNamePlural %>Query: <%= listQueryClass %>,
		private readonly create<%= className %>Command: <%= createCommandClass %>,
		private readonly update<%= className %>Command: <%= updateCommandClass %>,
		private readonly delete<%= className %>Command: <%= deleteCommandClass %>,
	) {}

	@ApiOperation({ summary: 'List <%= plural %>', operationId: 'list<%= classNamePlural %>' })
	@ApiResponse({
		status: 200,
		schema: { type: 'array', items: { $ref: '#/components/schemas/<%= className %>ResponseDto' } },
	})
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@Get()
	async findAll(): Promise<<%= className %>[]> {
		return this.list<%= classNamePlural %>Query.execute();
	}

	@ApiOperation({ summary: 'Find <%= name %> by id', operationId: 'find<%= className %>ById' })
	@ApiResponse({ status: 200, schema: { $ref: '#/components/schemas/<%= className %>ResponseDto' } })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiParam({ name: 'id', type: 'string', format: 'uuid' })
	@Get(':id')
	async findById(
		@Param('id', ParseUUIDPipe) id: string,
	): Promise<<%= className %>> {
		return this.get<%= className %>ByIdQuery.execute(id);
	}

	@ApiOperation({ summary: 'Create <%= name %>', operationId: 'create<%= className %>' })
	@ApiBody({ schema: { $ref: '#/components/schemas/Create<%= className %>Dto' } })
	@ApiResponse({ status: 201, schema: { $ref: '#/components/schemas/<%= className %>ResponseDto' } })
	@ApiResponse({ status: 400, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@Post()
	@UsePipes(new ZodValidationPipe(create<%= className %>Schema))
	async create(
		@Body() dto: Create<%= className %>Dto,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<<%= className %>> {
		return this.create<%= className %>Command.execute(dto, { actor: { tenantId, userId } });
	}

	@ApiOperation({ summary: 'Update <%= name %>', operationId: 'update<%= className %>' })
	@ApiBody({ schema: { $ref: '#/components/schemas/Update<%= className %>Dto' } })
	@ApiResponse({ status: 200, schema: { $ref: '#/components/schemas/<%= className %>ResponseDto' } })
	@ApiResponse({ status: 400, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiParam({ name: 'id', type: 'string', format: 'uuid' })
	@Put(':id')
	async update(
		@Param('id', ParseUUIDPipe) id: string,
		@Body(new ZodValidationPipe(update<%= className %>Schema)) dto: Update<%= className %>Dto,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<<%= className %>> {
		return this.update<%= className %>Command.execute(id, dto, { actor: { tenantId, userId } });
	}

	@ApiOperation({ summary: 'Delete <%= name %>', operationId: 'delete<%= className %>' })
	@ApiResponse({ status: 204 })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiParam({ name: 'id', type: 'string', format: 'uuid' })
	@Delete(':id')
	async delete(
		@Param('id', ParseUUIDPipe) id: string,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<<%= className %>> {
		return this.delete<%= className %>Command.execute(id, { actor: { tenantId, userId } });
	}
}

<% } -%>
<% if (exposeElectric) { -%>
/**
 * <%= classNamePlural %> Controller (Electric SQL)
 * Generated by entity codegen - do not edit directly
 */

import {
	Controller,
	Get,
	Body,
	Delete,
	Headers,
	Param,
	ParseUUIDPipe,
	Post,
	Put,
	Req,
	Res,
	UseGuards,
	UsePipes,
} from '@nestjs/common';
import {
	ApiBearerAuth,
	ApiBody,
	ApiOperation,
	ApiParam,
	ApiResponse,
} from '@nestjs/swagger';
import type { Request, Response } from 'express';
import { AuthGuard } from '<%= imports.controllerToAuthGuard %>/auth.guard';
import { CurrentUser } from '<%= imports.controllerToCurrentUser %>/current-user.decorator';
import { User } from '<%= imports.controllerToDomain %>/user';
import { ElectricService } from '<%= imports.controllerToElectricService %>/electric.service';
import { <%= plural %>Columns } from '<%= locations.dbSchemaClient.import %>';
import {
	type Create<%= className %>Dto,
	create<%= className %>Schema,
	type Update<%= className %>Dto,
	update<%= className %>Schema,
} from '<%= imports.controllerToSchemas %>';
import { <%= createCommandClass %> } from '<%= imports.controllerToCreateCommand %>';
import { <%= deleteCommandClass %> } from '<%= imports.controllerToDeleteCommand %>';
import { <%= updateCommandClass %> } from '<%= imports.controllerToUpdateCommand %>';
import { <%= getByIdQueryClass %> } from '<%= imports.controllerToGetByIdQuery %>';
import { ZodValidationPipe } from '../../core/pipes/zod-validation.pipe';
import { <%= className %> } from '<%= imports.controllerToDomain %>';

@ApiBearerAuth()
@Controller('<%= plural %>')
@UseGuards(AuthGuard)
export class <%= classNamePlural %>Controller {
	constructor(
		private readonly electricService: ElectricService,
		private readonly get<%= className %>ByIdQuery: <%= getByIdQueryClass %>,
		private readonly create<%= className %>Command: <%= createCommandClass %>,
		private readonly update<%= className %>Command: <%= updateCommandClass %>,
		private readonly delete<%= className %>Command: <%= deleteCommandClass %>,
	) {}

	@ApiOperation({ summary: 'List <%= plural %> (Electric SQL proxy)', operationId: 'list<%= classNamePlural %>' })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@Get()
	async findAll(
		@CurrentUser() user: User,
		@Req() req: Request,
		@Res() res: Response,
	): Promise<void> {
		return this.electricService.proxyRequest({
			req,
			res,
			table: '<%= table %>',
			columns: <%= plural %>Columns,
			where: `"<%= electricWhereColumn %>" = '${<%= electricWhereValue %>}'`,
		});
	}

	@ApiOperation({ summary: 'Find <%= name %> by id', operationId: 'find<%= className %>ById' })
	@ApiResponse({ status: 200, schema: { $ref: '#/components/schemas/<%= className %>ResponseDto' } })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiParam({ name: 'id', type: 'string', format: 'uuid' })
	@Get(':id')
	async findById(@Param('id', ParseUUIDPipe) id: string): Promise<<%= className %>> {
		return this.get<%= className %>ByIdQuery.execute(id);
	}

	@ApiOperation({ summary: 'Create <%= name %>', operationId: 'create<%= className %>' })
	@ApiBody({ schema: { $ref: '#/components/schemas/Create<%= className %>Dto' } })
	@ApiResponse({ status: 201, schema: { $ref: '#/components/schemas/<%= className %>ResponseDto' } })
	@ApiResponse({ status: 400, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@Post()
	@UsePipes(new ZodValidationPipe(create<%= className %>Schema))
	async create(
		@Body() dto: Create<%= className %>Dto,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<<%= className %>> {
		return this.create<%= className %>Command.execute(dto, { actor: { tenantId, userId } });
	}

	@ApiOperation({ summary: 'Update <%= name %>', operationId: 'update<%= className %>' })
	@ApiBody({ schema: { $ref: '#/components/schemas/Update<%= className %>Dto' } })
	@ApiResponse({ status: 200, schema: { $ref: '#/components/schemas/<%= className %>ResponseDto' } })
	@ApiResponse({ status: 400, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiParam({ name: 'id', type: 'string', format: 'uuid' })
	@Put(':id')
	async update(
		@Param('id', ParseUUIDPipe) id: string,
		@Body(new ZodValidationPipe(update<%= className %>Schema)) dto: Update<%= className %>Dto,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<<%= className %>> {
		return this.update<%= className %>Command.execute(id, dto, { actor: { tenantId, userId } });
	}

	@ApiOperation({ summary: 'Delete <%= name %>', operationId: 'delete<%= className %>' })
	@ApiResponse({ status: 204 })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiParam({ name: 'id', type: 'string', format: 'uuid' })
	@Delete(':id')
	async delete(
		@Param('id', ParseUUIDPipe) id: string,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<<%= className %>> {
		return this.delete<%= className %>Command.execute(id, { actor: { tenantId, userId } });
	}
}
<% } -%>
