// @generated by @pattern-stack/codegen from test/fixtures/entities/user.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
/**
 * User module barrel export
 * Generated by entity codegen - do not edit directly
 */

// Value exports (module, service, controller)
export { UsersModule } from './users.module';
export { UserService } from './user.service';
export { UserController } from './user.controller';

// Type-only exports (entity, DTOs)
export type { User } from './user.entity';
export type { CreateUserDto } from './dto/create-user.dto';
export type { UpdateUserDto } from './dto/update-user.dto';
export type { UserOutputDto } from './dto/user-output.dto';
export type { ListUsersQueryDto } from './dto/list-users.query';
