// @generated by @pattern-stack/codegen from test/fixtures/entities/user.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, Inject, Optional } from '@nestjs/common';
import { WithAnalytics } from '@shared/base-classes/with-analytics';
import { EVENT_BUS } from '@shared/constants/tokens';
import { BaseService } from '@shared/base-classes/base-service';
import { UserRepository } from './user.repository';
import type { User } from './user.entity';
import { PersonRepository } from '../persons/person.repository';
import type { Person } from '../persons/person.entity';
import { OpportunityRepository } from '../opportunities/opportunity.repository';
import type { Opportunity } from '../opportunities/opportunity.entity';

@Injectable()
export class UserService extends WithAnalytics(
  BaseService<UserRepository, User>,
) {
  protected override readonly entityName = 'user';

  /** Injected by NestJS when EventsModule is registered. */
  @Optional() @Inject(EVENT_BUS)
  protected override eventBus: any = undefined;

  constructor(
    protected override readonly repository: UserRepository,
    private readonly personRepo: PersonRepository,
    private readonly opportunityRepo: OpportunityRepository,
  ) {
    super(repository);
  }

  // Lifecycle events (created/updated/deleted + per-field changes) are emitted
  // automatically by BaseService when the events subsystem is installed.
  //
  // Inherited from BaseService:
  //   findById, findByIds, list, count, exists, create, update, delete

  // ═══════════════════════════════════════════════════════════════════════
  // Relationship composition methods (CGP-358b / CGP-62)
  // Two queries, no SQL JOIN.
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Fetch the Person parent for this User.
   * Two repo calls: find self by id → find target by FK.
   */
  async person(userId: string): Promise<Person | null> {
    const entity = await this.repository.findById(userId);
    if (!entity) return null;
    return entity.personId ? this.personRepo.findById(entity.personId) : null;
  }

  /**
   * Fetch owned_opportunities for this User by FK traversal.
   * Single repo call with optional cursor/limit pagination.
   */
  async owned_opportunities(userId: string, opts?: { cursor?: string; limit?: number }): Promise<Opportunity[]> {
    return this.opportunityRepo.findByOwnerId(userId, opts);
  }


}
