---
to: <%= basePaths.backendSrc %>/modules/<%= plural %>.module.ts
force: true
---
/**
 * <%= classNamePlural %> Module
 * Generated by entity codegen - do not edit directly
 */

import { Module } from '@nestjs/common';
import { <%= repositoryToken %> } from '../constants';
import { Get<%= className %>ByIdQuery } from '../application/queries/<%= name %>/get-by-id.query';
import { List<%= classNamePlural %>Query } from '../application/queries/<%= name %>/list.query';
import { Create<%= className %>Command } from '../application/commands/<%= name %>/create.command';
import { Delete<%= className %>Command } from '../application/commands/<%= name %>/delete.command';
import { Update<%= className %>Command } from '../application/commands/<%= name %>/update.command';
import { PersistenceModule } from '../infrastructure/persistence/persistence.module';
import { <%= className %>Repository } from '../infrastructure/persistence/drizzle/repositories/<%= name %>.repository';
<% if (exposeRest) { -%>
import { <%= classNamePlural %>Controller } from '../../presentation/rest/<%= plural %>.controller';
<% } -%>

@Module({
	imports: [PersistenceModule],
<% if (exposeRest) { -%>
	controllers: [<%= classNamePlural %>Controller],
<% } -%>
	providers: [
		{ provide: <%= repositoryToken %>, useClass: <%= className %>Repository },
		// Queries
		Get<%= className %>ByIdQuery,
		List<%= classNamePlural %>Query,
		// Use Cases
		Create<%= className %>Command,
		Update<%= className %>Command,
		Delete<%= className %>Command,
	],
	exports: [
		<%= repositoryToken %>,
		Get<%= className %>ByIdQuery,
		List<%= classNamePlural %>Query,
		Create<%= className %>Command,
		Update<%= className %>Command,
		Delete<%= className %>Command,
	],
})
export class <%= classNamePlural %>Module {}
