// @generated by @pattern-stack/codegen from test/fixtures/entities/person.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable } from '@nestjs/common';
import { PersonService } from '../person.service';
import type { CreatePersonDto } from '../dto/create-person.dto';
import type { Person } from '../person.entity';

@Injectable()
export class CreatePersonUseCase {
  constructor(private readonly service: PersonService) {}

  async execute(
    dto: CreatePersonDto,
  ): Promise<Person> {
    return this.service.create(dto);
  }
}
