// @generated by @pattern-stack/codegen from test/fixtures/entities/person.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, NotFoundException } from '@nestjs/common';
import { PersonService } from '../person.service';
import type { Person } from '../person.entity';

@Injectable()
export class FindPersonByIdUseCase {
  constructor(private readonly service: PersonService) {}

  async execute(id: string): Promise<Person> {
    const entity = await this.service.findById(id);
    if (entity === null || entity === undefined) {
      throw new NotFoundException(`Person not found: ${id}`);
    }
    return entity;
  }
}
