// @generated by @pattern-stack/codegen from test/fixtures/entities/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Inject, Module, type OnModuleInit } from '@nestjs/common';
import { OPENAPI_REGISTRY, type OpenApiRegistry } from '@shared/openapi';
import { DatabaseModule } from '@shared/database/database.module';
import { OpportunityRepository } from '../opportunities/opportunity.repository';

import { DealStateRepository } from './deal_state.repository';
import { DealStateService } from './deal_state.service';
import { DealStateController } from './deal_state.controller';
// OPENAPI-2: Zod schemas registered with OpenApiRegistry at module init.
import { CreateDealStateSchema } from './dto/create-deal_state.dto';
import { UpdateDealStateSchema } from './dto/update-deal_state.dto';
import { DealStateOutputSchema } from './dto/deal_state-output.dto';
import { FindDealStateByIdUseCase } from './use-cases/find-deal_state-by-id.use-case';
import { ListDealStatesUseCase } from './use-cases/list-deal_states.use-case';
import { CreateDealStateUseCase } from './use-cases/create-deal_state.use-case';
import { UpdateDealStateUseCase } from './use-cases/update-deal_state.use-case';
import { DeleteDealStateUseCase } from './use-cases/delete-deal_state.use-case';

@Module({
  imports: [
    DatabaseModule,
    // TODO: Add subsystem modules as needed (EventsSubsystemModule, IntegrationsSubsystemModule, etc.)
    // Cross-domain modules from relationships:
  ],
  controllers: [DealStateController],
  providers: [
    DealStateRepository,
    DealStateService,
    OpportunityRepository,
    FindDealStateByIdUseCase,
    ListDealStatesUseCase,
    CreateDealStateUseCase,
    UpdateDealStateUseCase,
    DeleteDealStateUseCase,
  ],
  // ADR-002 (revised): the service is the public API; the repository is ALSO
  // exported so sibling modules that compose this entity cross-module (junction
  // `.list()`, EAV value→definition resolution) inject the home-module instance
  // — the only place the repo's own deps are wired (e.g. an EAV entity's repo
  // injects FieldValueService for the #374 integration dual-write tx). Local-providing
  // such a repo elsewhere can't satisfy those deps. Use-case internals stay unexported.
  exports: [DealStateService, DealStateRepository],
})
export class DealStatesModule implements OnModuleInit {
  // OPENAPI-2: register this entity's Zod schemas with the shared
  // OpenApiRegistry at module init. OPENAPI-4 awaits `build()` at boot
  // to emit the full /docs-json document.
  constructor(
    @Inject(OPENAPI_REGISTRY) private readonly openApi: OpenApiRegistry,
  ) {}

  onModuleInit(): void {
    this.openApi.registerSchema('CreateDealStateDto', CreateDealStateSchema);
    this.openApi.registerSchema('UpdateDealStateDto', UpdateDealStateSchema);
    // The response schema is named <Entity>OutputDto (matches
    // classNames.outputDto); the OPENAPI-2 spec sketch uses "ResponseDto"
    // but the generated code publishes OutputDto everywhere, so we
    // keep consistency. OPENAPI-3 decorators reference the same name.
    this.openApi.registerSchema('DealStateOutputDto', DealStateOutputSchema);
  }
}
