// @generated by @pattern-stack/codegen from test/fixtures/entities/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
/**
 * DealState module barrel export
 * Generated by entity codegen - do not edit directly
 */

// Value exports (module, service, controller)
export { DealStatesModule } from './deal_states.module';
export { DealStateService } from './deal_state.service';
export { DealStateController } from './deal_state.controller';

// Type-only exports (entity, DTOs)
export type { DealState } from './deal_state.entity';
export type { CreateDealStateDto } from './dto/create-deal_state.dto';
export type { UpdateDealStateDto } from './dto/update-deal_state.dto';
export type { DealStateOutputDto } from './dto/deal_state-output.dto';
export type { ListDealStatesQueryDto } from './dto/list-deal_states.query';
