// @generated by @pattern-stack/codegen from test/fixtures/entities/person.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { z } from 'zod';

export const PersonOutputSchema = z.object({
  id: z.string().uuid(),
  tenantId: z.string().uuid(),
  email: z.string(),
  firstName: z.string(),
  lastName: z.string(),
});

export type PersonOutputDto = z.infer<typeof PersonOutputSchema>;
