// @generated by @pattern-stack/codegen from test/fixtures/entities/contact-v2.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable } from '@nestjs/common';
import { ContactService } from '../contact.service';

@Injectable()
export class DeleteContactUseCase {
  constructor(private readonly service: ContactService) {}

  async execute(
    id: string,
  ): Promise<void> {
    return this.service.delete(id);
  }
}
