// @generated by @pattern-stack/codegen from test/fixtures/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Get DealState By ID Query
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add query logic here):
 * - Authorization: Check if user can access this specific record
 * - Enrichment: Add computed fields or related data
 * - Caching: Add cache layer for frequently accessed records
 */

import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { DEALSTATE_REPOSITORY } from '../../../constants';
import type { IDealStateRepository } from '../../../domain';
import { DealState } from '../../../domain';

@Injectable()
export class GetDealStateByIdQuery {
	constructor(
		@Inject(DEALSTATE_REPOSITORY)
		private readonly dealStateRepository: IDealStateRepository,
	) {}

	async execute(id: string): Promise<DealState> {
		// TODO: Add authorization check if needed (row-level security)

		const entity = await this.dealStateRepository.findById(id);
		if (!entity) {
			throw new NotFoundException(`DealState with id ${id} not found`);
		}

		// TODO: Add enrichment or computed fields if needed

		return entity;
	}
}
