/**
 * List DealStates Query
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add query logic here):
 * - Filtering: Add where clauses based on query parameters
 * - Authorization: Filter results based on user permissions (row-level security)
 * - Pagination: Add limit/offset or cursor-based pagination
 * - Sorting: Add order by clauses
 * - Caching: Add cache layer for frequently accessed lists
 */

import { Inject, Injectable } from '@nestjs/common';
import { DEALSTATE_REPOSITORY } from '../../../constants';
import type { IDealStateRepository, DealStateWith } from '../../../domain';
import { DealState } from '../../../domain';

@Injectable()
export class ListDealStatesQuery {
	constructor(
		@Inject(DEALSTATE_REPOSITORY)
		private readonly dealStateRepository: IDealStateRepository,
	) {}

	async execute(include?: DealStateWith): Promise<DealState[]> {
		// TODO: Add filtering, pagination, sorting as needed
		return this.dealStateRepository.findAll(include);
	}
}
