// @generated by @pattern-stack/codegen from test/fixtures/opportunity.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Delete Opportunity Command
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add business logic here):
 * - Authorization: Check if user can delete this specific record
 * - Referential integrity: Check for dependent records, cascade or block
 * - Soft delete: Mark as deleted instead of hard delete
 * - Side effects: Emit events, clean up related data, notify subscribers
 * - Audit: Log deletion for compliance/debugging
 */

import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { OPPORTUNITY_REPOSITORY } from '../../../constants';
import type { IOpportunityRepository } from '../../../domain';
import { Opportunity } from '../../../domain';

@Injectable()
export class DeleteOpportunityCommand {
	constructor(
		@Inject(OPPORTUNITY_REPOSITORY)
		private readonly opportunityRepository: IOpportunityRepository,
	) {}

	async execute(
		id: string,
		_opts?: { actor?: { tenantId?: string | null; userId?: string } },
	): Promise<Opportunity> {
		// TODO: Add pre-delete validation here
		// e.g., check for dependent records, verify user permissions

		const deleted = await this.opportunityRepository.delete(id);
		if (!deleted) {
			throw new NotFoundException(`Opportunity with id ${id} not found`);
		}

		// TODO: Add post-delete side effects here (events, cleanup, etc.)

		return deleted;
	}
}
