// @generated by @pattern-stack/codegen from the entity set — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

/**
 * Generated frontend data layer.
 *
 * Entities:
 * - Person
 * - User
 *
 * Version pairing — the emitted imports require these package ranges in the
 * consumer's frontend package.json:
 *
 *   @pattern-stack/frontend-patterns  ^0.2.0-alpha.18
 *   @tanstack/react-db                ^0.1.55
 *   @tanstack/electric-db-collection  ^0.2.11
 *   @tanstack/query-db-collection     ^1.0.6
 *   @tanstack/react-query             ^5.0.0
 */

// Per-entity sync configuration + runtime overrides
export * from './config';

// Shared TanStack QueryClient
export * from './query-client';

// REST api client
export * from './api/index';

// TanStack DB collections (per-entity sync mode)
export * from './collections/index';

// Entity hooks (createEntityHooks wiring)
export * from './entities/index';

// Field metadata (DataGrid / forms / admin)
export * from './fields/index';

// Unified store (entities + collections + resolvers + lookups)
export * from './store/module-index';
