// @generated by @pattern-stack/codegen from the entity set — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { QueryClient } from '@tanstack/react-query';

/**
 * Shared QueryClient for REST-backed (`api` sync mode) collections.
 *
 * Replaceable: swap this for your app's own QueryClient if you already create
 * one — every generated collection imports `queryClient` from this module.
 */
export const queryClient = new QueryClient({
	defaultOptions: {
		queries: {
			staleTime: 60 * 1000, // 60s
			gcTime: 5 * 60 * 1000, // 5m
		},
	},
});
