// @generated by @pattern-stack/codegen from test/fixtures/demo-deal.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * List Deals Query
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add query logic here):
 * - Filtering: Add where clauses based on query parameters
 * - Authorization: Filter results based on user permissions (row-level security)
 * - Pagination: Add limit/offset or cursor-based pagination
 * - Sorting: Add order by clauses
 * - Caching: Add cache layer for frequently accessed lists
 */

import { Inject, Injectable } from '@nestjs/common';
import { DEAL_REPOSITORY } from '../../../constants';
import type { IDealRepository } from '../../../domain';
import { Deal } from '../../../domain';

@Injectable()
export class ListDealsQuery {
	constructor(
		@Inject(DEAL_REPOSITORY)
		private readonly dealRepository: IDealRepository,
	) {}

	async execute(): Promise<Deal[]> {
		// TODO: Add filtering, pagination, sorting as needed
		return this.dealRepository.findAll();
	}
}
