// @generated by @pattern-stack/codegen from test/fixtures/entities/organization.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { z } from 'zod';

export const OrganizationOutputSchema = z.object({
  id: z.string().uuid(),
  parentId: z.string().uuid().nullable(),
  tenantId: z.string().uuid(),
  name: z.string(),
  domain: z.string().nullable(),
});

export type OrganizationOutputDto = z.infer<typeof OrganizationOutputSchema>;
