// @generated by @pattern-stack/codegen from test/fixtures/entities/account.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { z } from 'zod';

export const CreateAccountSchema = z.object({
  name: z.string(),
});

export type CreateAccountDto = z.infer<typeof CreateAccountSchema>;
