// @generated by @pattern-stack/codegen from test/fixtures/entities/account.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { z } from 'zod';
import { CreateAccountSchema } from './create-account.dto';

export const UpdateAccountSchema = CreateAccountSchema.partial();

export type UpdateAccountDto = z.infer<typeof UpdateAccountSchema>;
