// @generated by @pattern-stack/codegen from test/fixtures/entities/demo-deal.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { z } from 'zod';

export const CreateDealSchema = z.object({
  ownerId: z.string().uuid(),
  accountId: z.string().uuid(),
  name: z.string(),
  amount: z.coerce.string().nullable().optional(),
  stage: z.enum(['prospecting', 'qualification', 'proposal', 'negotiation', 'closed_won', 'closed_lost']),
  closeDate: z.coerce.date().nullable().optional(),
  probability: z.number().int().nullable().optional(),
});

export type CreateDealDto = z.infer<typeof CreateDealSchema>;
