---
to: "<%= generate.structure === 'entity-first' ? `${locations.frontendGenerated.path}/${name}/fields.ts` : generate.structure === 'concern-first' ? `${locations.frontendGenerated.path}/fields/${name}.ts` : '' %>"
skip_if: <%= generate.structure === 'monolithic' || !generate.fieldMetadata %>
force: true
---
/**
 * <%= className %> Field Metadata
 * Generated by entity codegen - do not edit directly
 *
 * Field definitions for DataGrid, forms, and admin interfaces
 */

import type { FieldMeta, FieldType, FieldImportance } from '<%= locations.frontendFieldMetaTypes.import %>/field-meta';
<% if (generate.structure === 'entity-first') { -%>
import type { <%= className %>Resolved } from './types';
<% } else if (generate.structure === 'concern-first') { -%>
import type { <%= className %>Resolved } from '../types/<%= name %>';
<% } -%>

export const <%= camelName %>Fields: Record<string, FieldMeta<<%= className %>Resolved>> = {
<% fields.forEach((field) => { -%>
<% // Skip entity ref internal fields from metadata display
if (field.isEntityRefType || field.isEntityRefId) return;
-%>
	<%= field.camelName %>: {
		field: '<%= field.camelName %>',
		label: '<%= field.ui_label %>',
		type: '<%= field.ui_type %>' as FieldType,
		importance: '<%= field.ui_importance %>' as FieldImportance,
<% if (field.ui_sortable) { -%>
		sortable: true,
<% } -%>
<% if (field.ui_filterable) { -%>
		filterable: true,
<% } -%>
<% if (field.ui_format) { -%>
		format: <%- JSON.stringify(field.ui_format) %>,
<% } -%>
<% if (field.hasChoices) { -%>
		choices: <%- JSON.stringify(field.choices) %>,
<% } -%>
<% if (field.foreignKey) { -%>
		reference: '<%= field.foreignKey.split('.')[0] %>',
<% } -%>
	},
<% }); -%>
<% // Add resolved relation fields to metadata
belongsToRelations.forEach((rel) => { -%>
	<%= rel.name %>: {
		field: '<%= rel.name %>',
		label: '<%= rel.targetClass.replace(/([A-Z])/g, ' $1').trim() %>',
		type: 'entity' as FieldType,
		importance: 'secondary' as FieldImportance,
		reference: '<%= rel.targetPlural %>',
	},
<% }); -%>
<% if (hasTimestamps) { -%>
	createdAt: {
		field: 'createdAt',
		label: 'Created',
		type: 'datetime' as FieldType,
		importance: 'tertiary' as FieldImportance,
		format: { dateFormat: 'relative' },
	},
	updatedAt: {
		field: 'updatedAt',
		label: 'Updated',
		type: 'datetime' as FieldType,
		importance: 'tertiary' as FieldImportance,
		format: { dateFormat: 'relative' },
	},
<% } -%>
};

export const <%= camelName %>Metadata = {
	name: '<%= name %>',
	plural: '<%= plural %>',
	displayName: '<%= className.replace(/([A-Z])/g, ' $1').trim() %>',
	displayNamePlural: '<%= classNamePlural.replace(/([A-Z])/g, ' $1').trim() %>',

	fields: <%= camelName %>Fields,

	// Display configuration
	primaryFields: [
<% fields.filter(f => f.ui_importance === 'primary').forEach(f => { -%>
		'<%= f.camelName %>',
<% }); -%>
	],
	searchFields: [
<% fields.filter(f => f.ui_filterable).forEach(f => { -%>
		'<%= f.camelName %>',
<% }); -%>
	],
	defaultSort: { field: '<% if (hasTimestamps) { %>createdAt<% } else { %>id<% } %>', direction: 'desc' as const },

	// Capabilities
	capabilities: {
		create: <%= exposeRepository || exposeTrpc %>,
		update: <%= exposeRepository || exposeTrpc %>,
		delete: <%= exposeRepository || exposeTrpc %>,
		list: true,
		get: true,
	},
} as const;
