---
to: "<%= generate.structure === 'entity-first' ? `${locations.frontendGenerated.path}/${name}/index.ts` : '' %>"
skip_if: <%= generate.structure !== 'entity-first' %>
force: true
---
/**
 * <%= className %> - Entity Module
 * Generated by entity codegen - do not edit directly
 *
 * Barrel export for all <%= className %> components
 */

export * from './types';
export * from './collection';
export * from './hooks';
<% if (generate.mutations && (exposeTrpc || exposeRepository)) { %>
export * from './mutations';
<% } %>
<% if (generate.fieldMetadata) { %>
export * from './fields';
<% } %>
