---
to: "<%= generate.structure === 'entity-first' ? `${locations.frontendGenerated.path}/${generate.fileNaming === 'plural' ? plural : name}/mutation-hooks.ts` : generate.structure === 'concern-first' ? `${locations.frontendGenerated.path}/mutation-hooks/${generate.fileNaming === 'plural' ? plural : name}.ts` : '' %>"
skip_if: <%= generate.structure === 'monolithic' || !generate.mutations || !(exposeTrpc || exposeRepository) %>
force: true
---
/**
 * <%= className %> Mutation Hooks
 * Generated by entity codegen - do not edit directly
 *
 * React hooks wrapping mutation functions with error state management
 */

import { useState, useCallback } from 'react';
<%
// File name for imports depends on fileNaming config
const fileName = generate.fileNaming === 'plural' ? plural : name;
-%>
<% if (generate.structure === 'entity-first') { -%>
import { insert<%= className %>, update<%= className %>, delete<%= className %> } from './mutations';
import type { <%= className %> } from './types';
<% } else if (generate.structure === 'concern-first') { -%>
import { insert<%= className %>, update<%= className %>, delete<%= className %> } from '../mutations/<%= fileName %>';
import type { <%= className %> } from '../types/<%= fileName %>';
<% } -%>

type MutationHookResult<TFn extends (...args: any[]) => any> = {
	mutate: TFn;
	error: Error | null;
	clearError: () => void;
};

export function useCreate<%= className %>(): MutationHookResult<typeof insert<%= className %>> {
	const [error, setError] = useState<Error | null>(null);

	const mutate = useCallback<typeof insert<%= className %>>((data) => {
		try {
			insert<%= className %>(data);
			setError(null);
		} catch (err) {
			const error = err instanceof Error ? err : new Error(String(err));
			setError(error);
			throw error;
		}
	}, []);

	const clearError = useCallback(() => setError(null), []);
	return { mutate, error, clearError };
}

export function useUpdate<%= className %>(): MutationHookResult<typeof update<%= className %>> {
	const [error, setError] = useState<Error | null>(null);

	const mutate = useCallback<typeof update<%= className %>>((id, fn) => {
		try {
			update<%= className %>(id, fn);
			setError(null);
		} catch (err) {
			const error = err instanceof Error ? err : new Error(String(err));
			setError(error);
			throw error;
		}
	}, []);

	const clearError = useCallback(() => setError(null), []);
	return { mutate, error, clearError };
}

export function useDelete<%= className %>(): MutationHookResult<typeof delete<%= className %>> {
	const [error, setError] = useState<Error | null>(null);

	const mutate = useCallback<typeof delete<%= className %>>((id) => {
		try {
			delete<%= className %>(id);
			setError(null);
		} catch (err) {
			const error = err instanceof Error ? err : new Error(String(err));
			setError(error);
			throw error;
		}
	}, []);

	const clearError = useCallback(() => setError(null), []);
	return { mutate, error, clearError };
}
