/**
 * Organization Repository Interface
 * Generated by entity codegen - do not edit directly
 */

import type { Organization } from './organization.entity';

/**
 * Domain-level input types for repository operations.
 */
export type CreateOrganizationInput = {
	tenantId: string;
	name: string;
	domain?: string | null;
	parentId?: string | null;
};

export type UpdateOrganizationInput = Partial<CreateOrganizationInput>;

export interface IOrganizationRepository {
	create(input: CreateOrganizationInput): Promise<Organization>;
	findById(id: string): Promise<Organization | null>;
	findAll(): Promise<Organization[]>;
	update(id: string, input: UpdateOrganizationInput): Promise<Organization | null>;
	delete(id: string): Promise<Organization | null>;
	findByParentId(id: string, opts?: { cursor?: string; limit?: number }): Promise<Organization[]>;
}
