/**
 * Delete DealState Command
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add business logic here):
 * - Authorization: Check if user can delete this specific record
 * - Referential integrity: Check for dependent records, cascade or block
 * - Soft delete: Mark as deleted instead of hard delete
 * - Side effects: Emit events, clean up related data, notify subscribers
 * - Audit: Log deletion for compliance/debugging
 */

import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { DEALSTATE_REPOSITORY } from '../../../constants';
import type { IDealStateRepository } from '../../../domain';
import { DealState } from '../../../domain';

@Injectable()
export class DeleteDealStateCommand {
	constructor(
		@Inject(DEALSTATE_REPOSITORY)
		private readonly dealStateRepository: IDealStateRepository,
	) {}

	async execute(id: string): Promise<DealState> {
		// TODO: Add pre-delete validation here
		// e.g., check for dependent records, verify user permissions

		const deleted = await this.dealStateRepository.delete(id);
		if (!deleted) {
			throw new NotFoundException(`DealState with id ${id} not found`);
		}

		// TODO: Add post-delete side effects here (events, cleanup, etc.)

		return deleted;
	}
}
