/**
 * Create Person Command
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add business logic here):
 * - Validation: Add domain validation rules before creating
 * - Defaults: Compute default values not handled by DTO
 * - Side effects: Emit events, send notifications, create related entities
 * - Authorization: Check user permissions beyond route-level auth
 * - Audit: Log creation for compliance/debugging
 */

import { Inject, Injectable } from '@nestjs/common';
import { PERSON_REPOSITORY } from '../../../constants';
import type { CreatePersonInput, IPersonRepository } from '../../../domain';
import { Person } from '../../../domain';
import type { CreatePersonDto } from '../../schemas';

@Injectable()
export class CreatePersonCommand {
	constructor(
		@Inject(PERSON_REPOSITORY)
		private readonly personRepository: IPersonRepository,
	) {}

	async execute(dto: CreatePersonDto): Promise<Person> {
		// TODO: Add pre-create validation and business rules here

		// Map DTO to domain input
		const input: CreatePersonInput = {
			tenantId: dto.tenantId,
			email: dto.email,
			firstName: dto.firstName,
			lastName: dto.lastName,
		};

		const created = await this.personRepository.create(input);

		// TODO: Add post-create side effects here (events, notifications, etc.)

		return created;
	}
}
