/**
 * Update Person Command
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add business logic here):
 * - Validation: Add domain validation rules (e.g., state transitions)
 * - Authorization: Check if user can modify this specific record
 * - Conflict detection: Optimistic locking, version checks
 * - Side effects: Emit events, invalidate caches, notify subscribers
 * - Audit: Log changes for compliance/debugging
 */

import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { PERSON_REPOSITORY } from '../../../constants';
import type { IPersonRepository, UpdatePersonInput } from '../../../domain';
import { Person } from '../../../domain';
import type { UpdatePersonDto } from '../../schemas';

@Injectable()
export class UpdatePersonCommand {
	constructor(
		@Inject(PERSON_REPOSITORY)
		private readonly personRepository: IPersonRepository,
	) {}

	async execute(id: string, dto: UpdatePersonDto): Promise<Person> {
		const existing = await this.personRepository.findById(id);
		if (!existing) {
			throw new NotFoundException(`Person with id ${id} not found`);
		}

		// TODO: Add pre-update validation and business rules here
		// e.g., check state transitions, verify user permissions on this record

		// Map DTO to domain input (only include defined fields)
		const input: UpdatePersonInput = {
			...(dto.tenantId !== undefined && { tenantId: dto.tenantId }),
			...(dto.email !== undefined && { email: dto.email }),
			...(dto.firstName !== undefined && { firstName: dto.firstName }),
			...(dto.lastName !== undefined && { lastName: dto.lastName }),
		};

		const updated = await this.personRepository.update(id, input);
		if (!updated) {
			throw new NotFoundException(`Person with id ${id} not found`);
		}

		// TODO: Add post-update side effects here (events, cache invalidation, etc.)

		return updated;
	}
}
