// @generated by @pattern-stack/codegen from test/fixtures/opportunity.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Get Opportunity By ID Query
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add query logic here):
 * - Authorization: Check if user can access this specific record
 * - Enrichment: Add computed fields or related data
 * - Caching: Add cache layer for frequently accessed records
 */

import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { OPPORTUNITY_REPOSITORY } from '../../../constants';
import type { IOpportunityRepository } from '../../../domain';
import { Opportunity } from '../../../domain';

@Injectable()
export class GetOpportunityByIdQuery {
	constructor(
		@Inject(OPPORTUNITY_REPOSITORY)
		private readonly opportunityRepository: IOpportunityRepository,
	) {}

	async execute(id: string): Promise<Opportunity> {
		// TODO: Add authorization check if needed (row-level security)

		const entity = await this.opportunityRepository.findById(id);
		if (!entity) {
			throw new NotFoundException(`Opportunity with id ${id} not found`);
		}

		// TODO: Add enrichment or computed fields if needed

		return entity;
	}
}
