/**
 * List Opportunities Query
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add query logic here):
 * - Filtering: Add where clauses based on query parameters
 * - Authorization: Filter results based on user permissions (row-level security)
 * - Pagination: Add limit/offset or cursor-based pagination
 * - Sorting: Add order by clauses
 * - Caching: Add cache layer for frequently accessed lists
 */

import { Inject, Injectable } from '@nestjs/common';
import { OPPORTUNITY_REPOSITORY } from '../../../constants';
import type { IOpportunityRepository, OpportunityWith } from '../../../domain';
import { Opportunity } from '../../../domain';

@Injectable()
export class ListOpportunitiesQuery {
	constructor(
		@Inject(OPPORTUNITY_REPOSITORY)
		private readonly opportunityRepository: IOpportunityRepository,
	) {}

	async execute(include?: OpportunityWith): Promise<Opportunity[]> {
		// TODO: Add filtering, pagination, sorting as needed
		return this.opportunityRepository.findAll(include);
	}
}
