// @generated by @pattern-stack/codegen from test/fixtures/contact-v2.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Contact Repository Implementation
 * Generated by entity codegen - do not edit directly
 */

import { Inject, Injectable } from '@nestjs/common';
import { eq, isNull, isNotNull, and, desc, asc } from 'drizzle-orm';
import { DRIZZLE } from '../../../constants/tokens';
import type { DrizzleTransaction } from '@shared/subsystems/events';
import type {
	CreateContactInput,
	IContactRepository,
	UpdateContactInput,
} from '../../../domain';
import { Contact } from '../../../domain';
import type { DrizzleDB } from '../database.module';
import { contacts } from '@repo/db/server/schema';

@Injectable()
export class ContactRepository implements IContactRepository {
	constructor(@Inject(DRIZZLE) private readonly db: DrizzleDB) {}

	async create(input: CreateContactInput, tx?: DrizzleTransaction): Promise<Contact> {
		const now = new Date();
		const runner = tx ?? this.db;
		const result = await runner
			.insert(contacts)
			.values({
				userId: input.userId,
				accountId: input.accountId,
				firstName: input.firstName,
				lastName: input.lastName,
				email: input.email,
				title: input.title,
				phone: input.phone,
				linkedinUrl: input.linkedinUrl,
				createdAt: now,
				updatedAt: now,
			})
			.returning();

		const record = result[0] as typeof contacts.$inferSelect;
		return Contact.fromRecord(record);
	}

	async findById(id: string): Promise<Contact | null> {
		const result = await this.baseQuery()
			.where(eq(contacts.id, id))
			.limit(1);

		const record = result[0];
		return record ? Contact.fromRecord(record) : null;
	}

	async findAll(): Promise<Contact[]> {
		const records = await this.baseQuery();
		return records.map(Contact.fromRecord);
	}

	async update(id: string, input: UpdateContactInput): Promise<Contact | null> {
		const result = await this.db
			.update(contacts)
			.set({
				...input,
				updatedAt: new Date(),
			})
			.where(eq(contacts.id, id))
			.returning();

		const record = result[0];
		return record ? Contact.fromRecord(record) : null;
	}

	async delete(id: string): Promise<Contact | null> {
		// Soft delete - set deletedAt timestamp
		const result = await this.db
			.update(contacts)
			.set({ deletedAt: new Date() })
			.where(eq(contacts.id, id))
			.returning();

		const record = result[0];
		return record ? Contact.fromRecord(record) : null;
	}

	async restore(id: string): Promise<Contact | null> {
		const result = await this.db
			.update(contacts)
			.set({ deletedAt: null })
			.where(eq(contacts.id, id))
			.returning();

		const record = result[0];
		return record ? Contact.fromRecord(record) : null;
	}

	async findWithDeleted(): Promise<Contact[]> {
		const records = await this.db.select().from(contacts);
		return records.map(Contact.fromRecord);
	}

	async findOnlyDeleted(): Promise<Contact[]> {
		const records = await this.db
			.select()
			.from(contacts)
			.where(isNotNull(contacts.deletedAt));
		return records.map(Contact.fromRecord);
	}

	private baseQuery() {
		return this.db.select().from(contacts).where(isNull(contacts.deletedAt));
	}

	async findByAccountId(id: string, opts?: { cursor?: string; limit?: number }): Promise<Contact[]> {
		let q = this.baseQuery()
			.where(eq(contacts.accountId, id));
		if (opts?.limit) q = (q as any).limit(opts.limit);
		const records = await q;
		return records.map(Contact.fromRecord);
	}

	async findByUserId(id: string, opts?: { cursor?: string; limit?: number }): Promise<Contact[]> {
		let q = this.baseQuery()
			.where(eq(contacts.userId, id));
		if (opts?.limit) q = (q as any).limit(opts.limit);
		const records = await q;
		return records.map(Contact.fromRecord);
	}

	// ═══════════════════════════════════════════════════════════════════════
	// Declarative queries (from queries: block in entity YAML)
	// ═══════════════════════════════════════════════════════════════════════

	async findByEmail(email: string): Promise<Contact | null> {
		const records = await this.baseQuery()
			.where(eq(contacts.email, email))
			.limit(1);
		return records[0] ? Contact.fromRecord(records[0]) : null;
	}

	async findByUserIdAndAccountId(userId: string, accountId: string): Promise<Contact[]> {
		const records = await this.baseQuery()
			.where(and(eq(contacts.userId, userId), eq(contacts.accountId, accountId)));
		return records.map(Contact.fromRecord);
	}

	async findByOpportunityId(opportunityId: string): Promise<Contact[]> {
		// Junction query through opportunity_contact_link
		const junctionRecords = await this.baseQuery()
			.innerJoin(opportunityContactLink, eq(opportunityContactLink.contactId, contacts.id))
			.where(eq(opportunityContactLink.opportunityId, opportunityId));
		return junctionRecords.map(r => Contact.fromRecord(r));
	}

	async findEmailsByOpportunityId(opportunityId: string): Promise<string[]> {
		// Junction query through opportunity_contact_link
		const junctionRecords = await this.baseQuery()
			.innerJoin(opportunityContactLink, eq(opportunityContactLink.contactId, contacts.id))
			.where(eq(opportunityContactLink.opportunityId, opportunityId));
		return junctionRecords.map(r => r.email);
	}
}
