/**
 * Deal Repository Implementation
 * Generated by entity codegen - do not edit directly
 */

import { Inject, Injectable } from '@nestjs/common';
import { eq, isNull, isNotNull, and, desc, asc } from 'drizzle-orm';
import { DRIZZLE } from '../../../constants/tokens';
import type {
	CreateDealInput,
	IDealRepository,
	UpdateDealInput,
	DealWith,
} from '../../../domain';
import { Deal, User } from '../../../domain';
import type { DrizzleDB } from '../database.module';
import { deals } from '@repo/db/server/schema';

@Injectable()
export class DealRepository implements IDealRepository {
	constructor(@Inject(DRIZZLE) private readonly db: DrizzleDB) {}

	async create(input: CreateDealInput): Promise<Deal> {
		const now = new Date();
		const result = await this.db
			.insert(deals)
			.values({
				name: input.name,
				amount: input.amount,
				stage: input.stage,
				ownerId: input.ownerId,
				accountId: input.accountId,
				closeDate: input.closeDate,
				probability: input.probability,
				createdAt: now,
				updatedAt: now,
			})
			.returning();

		const record = result[0] as typeof deals.$inferSelect;
		return Deal.fromRecord(record);
	}

	async findById(id: string, include?: DealWith): Promise<Deal | null> {
		const record = await this.db.query.deals.findFirst({
			where: eq(deals.id, id),
			with: this.buildWithClause(include),
		});

		return record ? this.mapToEntity(record) : null;
	}

	async findAll(include?: DealWith): Promise<Deal[]> {
		const records = await this.db.query.deals.findMany({
			with: this.buildWithClause(include),
		});

		return records.map((r) => this.mapToEntity(r));
	}

	async update(id: string, input: UpdateDealInput): Promise<Deal | null> {
		const result = await this.db
			.update(deals)
			.set({
				...input,
				updatedAt: new Date(),
			})
			.where(eq(deals.id, id))
			.returning();

		const record = result[0];
		return record ? Deal.fromRecord(record) : null;
	}

	async delete(id: string): Promise<Deal | null> {
		// Soft delete - set deletedAt timestamp
		const result = await this.db
			.update(deals)
			.set({ deletedAt: new Date() })
			.where(eq(deals.id, id))
			.returning();

		const record = result[0];
		return record ? Deal.fromRecord(record) : null;
	}

	async restore(id: string): Promise<Deal | null> {
		const result = await this.db
			.update(deals)
			.set({ deletedAt: null })
			.where(eq(deals.id, id))
			.returning();

		const record = result[0];
		return record ? Deal.fromRecord(record) : null;
	}

	async findWithDeleted(): Promise<Deal[]> {
		const records = await this.db.select().from(deals);
		return records.map(Deal.fromRecord);
	}

	async findOnlyDeleted(): Promise<Deal[]> {
		const records = await this.db
			.select()
			.from(deals)
			.where(isNotNull(deals.deletedAt));
		return records.map(Deal.fromRecord);
	}

	private baseQuery() {
		return this.db.select().from(deals).where(isNull(deals.deletedAt));
	}

	async findByOwnerId(id: string, include?: DealWith): Promise<Deal[]> {
		const records = await this.db.query.deals.findMany({
			where: eq(deals.ownerId, id),
			with: this.buildWithClause(include),
		});

		return records.map((r) => this.mapToEntity(r));
	}

	async findByAccountId(id: string, include?: DealWith): Promise<Deal[]> {
		const records = await this.db.query.deals.findMany({
			where: eq(deals.accountId, id),
			with: this.buildWithClause(include),
		});

		return records.map((r) => this.mapToEntity(r));
	}

	// ═══════════════════════════════════════════════════════════════════════
	// Declarative queries (from queries: block in entity YAML)
	// ═══════════════════════════════════════════════════════════════════════

	async findByOwnerId(ownerId: string): Promise<Deal[]> {
		const records = await this.baseQuery()
			.where(eq(deals.ownerId, ownerId));
		return records.map(Deal.fromRecord);
	}

	async findByAccountId(accountId: string): Promise<Deal[]> {
		const records = await this.baseQuery()
			.where(eq(deals.accountId, accountId)).orderBy(desc(deals.closeDate));
		return records.map(Deal.fromRecord);
	}

	async findByStage(stage: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost'): Promise<Deal[]> {
		const records = await this.baseQuery()
			.where(eq(deals.stage, stage));
		return records.map(Deal.fromRecord);
	}

	async findByOwnerIdAndStage(ownerId: string, stage: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost'): Promise<Deal[]> {
		const records = await this.baseQuery()
			.where(and(eq(deals.ownerId, ownerId), eq(deals.stage, stage)));
		return records.map(Deal.fromRecord);
	}

	private buildWithClause(include?: DealWith) {
		if (!include) return undefined;
		// Drizzle expects `true` or object, not `false`. Only include truthy values.
		const result: Record<string, true> = {};
		if (include.owner) result.owner = true;
		if (include.account) result.account = true;
		return Object.keys(result).length > 0 ? result : undefined;
	}

	// biome-ignore lint/suspicious/noExplicitAny: Drizzle relational query returns dynamic shape
	private mapToEntity(record: any): Deal {
		return Deal.fromRecord(record, (name, data) => {
			switch (name) {
				case 'owner':
					// biome-ignore lint/suspicious/noExplicitAny: Cast for Drizzle record
					return User.fromRecord(data as any);
				default:
					return data;
			}
		});
	}
}
