/**
 * DealState Repository Implementation
 * Generated by entity codegen - do not edit directly
 */

import { Inject, Injectable } from '@nestjs/common';
import { eq } from 'drizzle-orm';
import { DRIZZLE } from '../../../constants/tokens';
import type {
	CreateDealStateInput,
	IDealStateRepository,
	UpdateDealStateInput,
} from '../../../domain';
import { DealState } from '../../../domain';
import type { DrizzleDB } from '../database.module';
import { deal_states } from '@repo/db/server/schema';

@Injectable()
export class DealStateRepository implements IDealStateRepository {
	constructor(@Inject(DRIZZLE) private readonly db: DrizzleDB) {}

	async create(input: CreateDealStateInput): Promise<DealState> {
		const result = await this.db
			.insert(deal_states)
			.values({
				tenantId: input.tenantId,
				name: input.name,
				displayName: input.displayName,
				stateType: input.stateType,
				sortOrder: input.sortOrder,
				probabilityDefault: input.probabilityDefault,
				color: input.color,
			})
			.returning();

		const record = result[0] as typeof deal_states.$inferSelect;
		return DealState.fromRecord(record);
	}

	async findById(id: string): Promise<DealState | null> {
		const result = await this.baseQuery()
			.where(eq(deal_states.id, id))
			.limit(1);

		const record = result[0];
		return record ? DealState.fromRecord(record) : null;
	}

	async findAll(): Promise<DealState[]> {
		const records = await this.baseQuery();
		return records.map(DealState.fromRecord);
	}

	async update(id: string, input: UpdateDealStateInput): Promise<DealState | null> {
		const result = await this.db
			.update(deal_states)
			.set({
				...input,
			})
			.where(eq(deal_states.id, id))
			.returning();

		const record = result[0];
		return record ? DealState.fromRecord(record) : null;
	}

	async delete(id: string): Promise<DealState | null> {
		const result = await this.db
			.delete(deal_states)
			.where(eq(deal_states.id, id))
			.returning();

		const record = result[0];
		return record ? DealState.fromRecord(record) : null;
	}

	private baseQuery() {
		return this.db.select().from(deal_states);
	}
}
