/**
 * Organization Repository Implementation
 * Generated by entity codegen - do not edit directly
 */

import { Injectable } from '@nestjs/common';
import { eq } from 'drizzle-orm';
import { BaseRepository, type BehaviorConfig } from '../base.repository';
import type {
	CreateOrganizationInput,
	IOrganizationRepository,
	UpdateOrganizationInput,
	OrganizationWith,
} from '../../../domain';
import { Organization, Opportunity } from '../../../domain';
import { organizations } from '../drizzle';

@Injectable()
export class OrganizationRepository
	extends BaseRepository<
		typeof organizations,
		Organization,
		CreateOrganizationInput,
		UpdateOrganizationInput
	>
	implements IOrganizationRepository
{
	protected readonly table = organizations;

	// Behaviors declared in YAML -> generated as config object
	protected readonly behaviors: BehaviorConfig = {
		timestamps: false,
		softDelete: false,
		userTracking: false,
	};

	protected toEntity(record: typeof organizations.$inferSelect): Organization {
		return Organization.fromRecord(record);
	}

	async findByParentId(id: string): Promise<Organization[]> {
		const records = await this.baseQuery()
			.where(eq(this.table.parentId, id));
		return records.map((r) => this.toEntity(r));
	}

	// ═══════════════════════════════════════════════════════════════════════
	// Relationship loading (extends base class)
	// ═══════════════════════════════════════════════════════════════════════

	async findByIdWithRelations(
		id: string,
		include?: OrganizationWith,
	): Promise<Organization | null> {
		const record = await this.db.query.organizations.findFirst({
			where: eq(organizations.id, id),
			with: this.buildWithClause(include),
		});
		return record ? this.mapToEntityWithRelations(record) : null;
	}

	async findAllWithRelations(include?: OrganizationWith): Promise<Organization[]> {
		const records = await this.db.query.organizations.findMany({
			with: this.buildWithClause(include),
		});
		return records.map((r) => this.mapToEntityWithRelations(r));
	}

	private buildWithClause(include?: OrganizationWith) {
		if (!include) return undefined;
		const result: Record<string, true> = {};
		if (include.parent) result.parent = true;
		if (include.children) result.children = true;
		if (include.opportunities) result.opportunities = true;
		return Object.keys(result).length > 0 ? result : undefined;
	}

	// biome-ignore lint/suspicious/noExplicitAny: Drizzle relational query returns dynamic shape
	private mapToEntityWithRelations(record: any): Organization {
		return Organization.fromRecord(record, (name, data) => {
			switch (name) {
				case 'parent':
					// biome-ignore lint/suspicious/noExplicitAny: Cast for Drizzle record
					return Organization.fromRecord(data as any);
				case 'children':
					// biome-ignore lint/suspicious/noExplicitAny: Cast for Drizzle records
					return (data as any[]).map((r) => Organization.fromRecord(r));
				case 'opportunities':
					// biome-ignore lint/suspicious/noExplicitAny: Cast for Drizzle records
					return (data as any[]).map((r) => Opportunity.fromRecord(r));
				default:
					return data;
			}
		});
	}
}
