/**
 * Organization Repository Implementation
 * Generated by entity codegen - do not edit directly
 */

import { Inject, Injectable } from '@nestjs/common';
import { eq } from 'drizzle-orm';
import { DRIZZLE } from '../../../constants/tokens';
import type {
	CreateOrganizationInput,
	IOrganizationRepository,
	UpdateOrganizationInput,
	OrganizationWith,
} from '../../../domain';
import { Organization, Opportunity } from '../../../domain';
import type { DrizzleDB } from '../database.module';
import { organizations } from '@repo/db/server/schema';

@Injectable()
export class OrganizationRepository implements IOrganizationRepository {
	constructor(@Inject(DRIZZLE) private readonly db: DrizzleDB) {}

	async create(input: CreateOrganizationInput): Promise<Organization> {
		const result = await this.db
			.insert(organizations)
			.values({
				tenantId: input.tenantId,
				name: input.name,
				domain: input.domain,
				parentId: input.parentId,
			})
			.returning();

		const record = result[0] as typeof organizations.$inferSelect;
		return Organization.fromRecord(record);
	}

	async findById(id: string, include?: OrganizationWith): Promise<Organization | null> {
		const record = await this.db.query.organizations.findFirst({
			where: eq(organizations.id, id),
			with: this.buildWithClause(include),
		});

		return record ? this.mapToEntity(record) : null;
	}

	async findAll(include?: OrganizationWith): Promise<Organization[]> {
		const records = await this.db.query.organizations.findMany({
			with: this.buildWithClause(include),
		});

		return records.map((r) => this.mapToEntity(r));
	}

	async update(id: string, input: UpdateOrganizationInput): Promise<Organization | null> {
		const result = await this.db
			.update(organizations)
			.set({
				...input,
			})
			.where(eq(organizations.id, id))
			.returning();

		const record = result[0];
		return record ? Organization.fromRecord(record) : null;
	}

	async delete(id: string): Promise<Organization | null> {
		const result = await this.db
			.delete(organizations)
			.where(eq(organizations.id, id))
			.returning();

		const record = result[0];
		return record ? Organization.fromRecord(record) : null;
	}

	private baseQuery() {
		return this.db.select().from(organizations);
	}

	async findByParentId(id: string, include?: OrganizationWith): Promise<Organization[]> {
		const records = await this.db.query.organizations.findMany({
			where: eq(organizations.parentId, id),
			with: this.buildWithClause(include),
		});

		return records.map((r) => this.mapToEntity(r));
	}

	private buildWithClause(include?: OrganizationWith) {
		if (!include) return undefined;
		// Drizzle expects `true` or object, not `false`. Only include truthy values.
		const result: Record<string, true> = {};
		if (include.parent) result.parent = true;
		if (include.children) result.children = true;
		if (include.opportunities) result.opportunities = true;
		return Object.keys(result).length > 0 ? result : undefined;
	}

	// biome-ignore lint/suspicious/noExplicitAny: Drizzle relational query returns dynamic shape
	private mapToEntity(record: any): Organization {
		return Organization.fromRecord(record, (name, data) => {
			switch (name) {
				case 'parent':
					// biome-ignore lint/suspicious/noExplicitAny: Cast for Drizzle record
					return Organization.fromRecord(data as any);
				case 'children':
					// biome-ignore lint/suspicious/noExplicitAny: Cast for Drizzle records
					return (data as any[]).map((r) => Organization.fromRecord(r));
				case 'opportunities':
					// biome-ignore lint/suspicious/noExplicitAny: Cast for Drizzle records
					return (data as any[]).map((r) => Opportunity.fromRecord(r));
				default:
					return data;
			}
		});
	}
}
