// @generated by @pattern-stack/codegen from test/fixtures/organization.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Organization Repository Implementation
 * Generated by entity codegen - do not edit directly
 */

import { Inject, Injectable } from '@nestjs/common';
import { eq } from 'drizzle-orm';
import { DRIZZLE } from '../../../constants/tokens';
import type {
	CreateOrganizationInput,
	IOrganizationRepository,
	UpdateOrganizationInput,
} from '../../../domain';
import { Organization } from '../../../domain';
import type { DrizzleDB } from '../database.module';
import { organizations } from '@repo/db/server/schema';

@Injectable()
export class OrganizationRepository implements IOrganizationRepository {
	constructor(@Inject(DRIZZLE) private readonly db: DrizzleDB) {}

	async create(input: CreateOrganizationInput): Promise<Organization> {
		const result = await this.db
			.insert(organizations)
			.values({
				tenantId: input.tenantId,
				name: input.name,
				domain: input.domain,
				parentId: input.parentId,
			})
			.returning();

		const record = result[0] as typeof organizations.$inferSelect;
		return Organization.fromRecord(record);
	}

	async findById(id: string): Promise<Organization | null> {
		const result = await this.baseQuery()
			.where(eq(organizations.id, id))
			.limit(1);

		const record = result[0];
		return record ? Organization.fromRecord(record) : null;
	}

	async findAll(): Promise<Organization[]> {
		const records = await this.baseQuery();
		return records.map(Organization.fromRecord);
	}

	async update(id: string, input: UpdateOrganizationInput): Promise<Organization | null> {
		const result = await this.db
			.update(organizations)
			.set({
				...input,
			})
			.where(eq(organizations.id, id))
			.returning();

		const record = result[0];
		return record ? Organization.fromRecord(record) : null;
	}

	async delete(id: string): Promise<Organization | null> {
		const result = await this.db
			.delete(organizations)
			.where(eq(organizations.id, id))
			.returning();

		const record = result[0];
		return record ? Organization.fromRecord(record) : null;
	}

	private baseQuery() {
		return this.db.select().from(organizations);
	}

	async findByParentId(id: string, opts?: { cursor?: string; limit?: number }): Promise<Organization[]> {
		let q = this.baseQuery()
			.where(eq(organizations.parentId, id));
		if (opts?.limit) q = (q as any).limit(opts.limit);
		const records = await q;
		return records.map(Organization.fromRecord);
	}
}
