// @generated by @pattern-stack/codegen from test/fixtures/user.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * User Repository Implementation
 * Generated by entity codegen - do not edit directly
 */

import { Inject, Injectable } from '@nestjs/common';
import { eq } from 'drizzle-orm';
import { DRIZZLE } from '../../../constants/tokens';
import type {
	CreateUserInput,
	IUserRepository,
	UpdateUserInput,
} from '../../../domain';
import { User } from '../../../domain';
import type { DrizzleDB } from '../database.module';
import { users } from '@repo/db/server/schema';

@Injectable()
export class UserRepository implements IUserRepository {
	constructor(@Inject(DRIZZLE) private readonly db: DrizzleDB) {}

	async create(input: CreateUserInput): Promise<User> {
		const result = await this.db
			.insert(users)
			.values({
				tenantId: input.tenantId,
				email: input.email,
				personId: input.personId,
			})
			.returning();

		const record = result[0] as typeof users.$inferSelect;
		return User.fromRecord(record);
	}

	async findById(id: string): Promise<User | null> {
		const result = await this.baseQuery()
			.where(eq(users.id, id))
			.limit(1);

		const record = result[0];
		return record ? User.fromRecord(record) : null;
	}

	async findAll(): Promise<User[]> {
		const records = await this.baseQuery();
		return records.map(User.fromRecord);
	}

	async update(id: string, input: UpdateUserInput): Promise<User | null> {
		const result = await this.db
			.update(users)
			.set({
				...input,
			})
			.where(eq(users.id, id))
			.returning();

		const record = result[0];
		return record ? User.fromRecord(record) : null;
	}

	async delete(id: string): Promise<User | null> {
		const result = await this.db
			.delete(users)
			.where(eq(users.id, id))
			.returning();

		const record = result[0];
		return record ? User.fromRecord(record) : null;
	}

	private baseQuery() {
		return this.db.select().from(users);
	}

	async findByPersonId(id: string, opts?: { cursor?: string; limit?: number }): Promise<User[]> {
		let q = this.baseQuery()
			.where(eq(users.personId, id));
		if (opts?.limit) q = (q as any).limit(opts.limit);
		const records = await q;
		return records.map(User.fromRecord);
	}
}
