---
to: <%= locations.frontendCollections.path %>/<%= name %>.ts
skip_if: <%= !generate.collections %>
force: true
---
/**
 * <%= className %> Collection
 * Generated by entity codegen - do not edit directly
 *
 * Real-time synced collection using TanStack DB + Electric SQL
 */

<% if (frontend.sync.columnMapper) { -%>
import { <%= frontend.sync.columnMapper %> } from '@electric-sql/client';
<% } -%>
import { <%= camelName %>Schema } from '<%= locations.dbEntities.import %>/<%= name %>';
import { electricCollectionOptions } from '@tanstack/electric-db-collection';
import { createCollection } from '@tanstack/react-db';
import { <%= frontend.auth.function %> } from './auth';

export const <%= camelName %>Collection = createCollection(
	electricCollectionOptions({
		id: '<%= plural %>',
		shapeOptions: {
<% if (frontend.sync.useTableParam) { -%>
			url: new URL(
				'<%= frontend.sync.shapeUrl %>',
				typeof window !== 'undefined'
					? window.location.origin
					: 'http://localhost:5173',
			).toString(),
			params: {
				table: '<%= plural %>',
			},
<% } else { -%>
			url: `<%= frontend.sync.shapeUrl %>/<%= plural %>`,
<% } -%>
			headers: {
				Authorization: <%= frontend.auth.function %>,
			},
			parser: {
<% Object.entries(frontend.parsers).forEach(([type, fn]) => { -%>
				<%= type %>: <%= fn %>,
<% }); -%>
			},
<% if (frontend.sync.columnMapper) { -%>
			columnMapper: <%= frontend.sync.columnMapper %>,
<% } -%>
		},
		schema: <%= camelName %>Schema,
		getKey: (item) => item.id,
	}),
);
