/**
 * Relations emitter — the HTTP include allowlist file (REL-2 §5).
 *
 * `<generated>/api-includes.ts`: one `as const satisfies` map per entity that
 * declares `api.includes`, keyed by read route and then by dot path. A generated
 * controller imports its own map and hands a looked-up fragment to the
 * repository; it never builds a tree from client input (charter I6).
 *
 * The `satisfies` is the second half of the guarantee. `buildIncludeAllowlists`
 * checks each path against the relation graph at GENERATION time; the annotation
 * re-checks the rendered fragments against the manifest's own types inside the
 * consumer project, so a drift between the graph the emitter saw and the manifest
 * it emitted is a build error in the consumer, not a runtime surprise.
 */

import type { CompiledEntityIncludes } from './build-includes';

export const API_INCLUDES_FILE = 'api-includes.ts';

const BANNER = `// @generated by @pattern-stack/codegen — do not edit.
// Run \`codegen entity new --all\` to regenerate.
//
// The HTTP include allowlist (ADR-044 §7, docs/specs/REL-2.md §5), derived from
// each entity's \`api.includes\` block. A client sends DOT PATHS
// (\`?include=contacts,opportunities.account\`); the controller looks each one up
// here and merges the fragments. A path that is not a key is a 400, and a route
// with no entry exposes nothing — closed by default.
//
// Every path was checked against the relation graph when this file was emitted,
// and the \`satisfies\` below re-checks the rendered fragments against the
// manifest's own types, so an allowlist naming a relation that does not exist
// cannot compile.
`;

/** `account` → `ACCOUNTS_API_INCLUDES` (keyed off the table, as the map is). */
export function includesConstName(table: string): string {
	return `${table.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()}_API_INCLUDES`;
}

/** A dot path is a valid identifier only when it has no dot — quote otherwise. */
function renderKey(path: string): string {
	return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(path) ? path : `'${path}'`;
}

function renderEntity(entity: CompiledEntityIncludes): string {
	const routes = entity.routes
		.map(({ route, maxDepth, paths }) => {
			const entries = paths
				.map(({ path, fragment }) => `\t\t${renderKey(path)}: ${fragment},`)
				.join('\n');
			return `\t// ${route} — max_depth ${maxDepth}\n\t${renderKey(route)}: {\n${entries}\n\t},`;
		})
		.join('\n');

	return (
		`/** \`${entity.entity}\`'s allowlisted include shapes, by read route. */\n` +
		`export const ${includesConstName(entity.table)} = {\n${routes}\n} as const satisfies ` +
		`Readonly<Record<string, RouteIncludes<'${entity.table}'>>>;\n`
	);
}

/**
 * Render the allowlist file for a set of compiled entity allowlists.
 *
 * An empty set still produces a file: the manifest's siblings are whole-set
 * writes, so a stale allowlist from a deleted `api.includes:` block has to be
 * cleared rather than left behind (charter I2).
 */
export function buildApiIncludes(
	entities: CompiledEntityIncludes[],
	relationsImport = './relations',
): string {
	if (entities.length === 0) {
		return `${BANNER}\n// No entity declares \`api.includes\` — nothing is exposed over HTTP.\nexport {};\n`;
	}

	const head =
		`${BANNER}import type { IncludeOf, Relations } from '${relationsImport}';\n\n` +
		`/** One route's allowlist: dot path → the include fragment it compiles to. */\n` +
		`type RouteIncludes<TTable extends keyof Relations> = Readonly<\n` +
		`\tRecord<string, IncludeOf<TTable>>\n` +
		`>;\n\n`;

	return head + entities.map(renderEntity).join('\n');
}
