/**
 * Relations emitter — manifest rendering (ADR-044, REL-1).
 *
 * Renders one `defineRelations()` over the generated schema barrel. Complete
 * file, `@generated` banner, deterministic order — re-running with the same
 * graph is byte-identical (charter I2).
 */

import { buildRelationGraph, type RelationGraph } from './build-graph';
import type { ColumnRef, RelationEdge, RelationsEmitContext } from './types';

export const RELATIONS_MANIFEST_FILE = 'relations.ts';

const BANNER = `// @generated by @pattern-stack/codegen — do not edit.
// Run \`codegen entity new --all\` to regenerate.
//
// The v2 Drizzle relation graph (ADR-044), derived from the entity YAML:
// \`relationships:\` blocks and \`Junction\` pairings. Every relation carries an
// explicit \`from\`/\`to\`, which is why none of them needs an \`alias\` — Drizzle
// only consults \`alias\` when it has to infer a relation's columns from the
// reverse side. See docs/specs/REL-1.md.
`;

/** `r.accounts.id` / `r.contacts.id.through(r.opportunityContacts.contactId)`. */
function renderRef(ref: ColumnRef): string {
	const base = `r.${ref.table}.${ref.column}`;
	return ref.through ? `${base}.through(r.${ref.through.table}.${ref.through.column})` : base;
}

function renderEdge(edge: RelationEdge): string {
	const config = [
		`from: ${renderRef(edge.from)}`,
		`to: ${renderRef(edge.to)}`,
		...(edge.optional === undefined ? [] : [`optional: ${edge.optional}`]),
	].join(', ');
	return `\t\t${edge.key}: r.${edge.cardinality}.${edge.targetTable}({ ${config} }),`;
}

/**
 * Render the manifest source for a graph.
 *
 * `schemaImport` is the module specifier of the generated schema barrel,
 * relative to the manifest's own directory (they are siblings, so `./schema`).
 */
export function buildRelationsManifest(
	graph: RelationGraph,
	schemaImport = './schema',
): string {
	const head =
		`${BANNER}import { defineRelations } from 'drizzle-orm';\n\n` +
		`import * as schema from '${schemaImport}';\n\n`;

	if (graph.tables.length === 0) {
		// A project with no relations still exports a manifest: the emitted
		// `database.module.ts` imports it unconditionally, and `project init`
		// writes this shape before any entity exists.
		return `${head}export const relations = defineRelations(schema, () => ({}));\n`;
	}

	const body = graph.tables
		.map(({ table, edges }) => `\t${table}: {\n${edges.map(renderEdge).join('\n')}\n\t},`)
		.join('\n');

	return `${head}export const relations = defineRelations(schema, (r) => ({\n${body}\n}));\n`;
}

/** Convenience: context → source string. */
export function buildRelationsManifestFromContext(
	ctx: RelationsEmitContext,
	schemaImport = './schema',
): { content: string; warnings: string[] } {
	const graph = buildRelationGraph(ctx);
	return { content: buildRelationsManifest(graph, schemaImport), warnings: graph.warnings };
}

/** The manifest a project with no entities gets (`project init`). */
export function emptyRelationsManifest(schemaImport = './schema'): string {
	return buildRelationsManifest({ tables: [], warnings: [] }, schemaImport);
}
