---
to: "<%= generate.dtos ? outputPaths.dto : '' %>"
skip_if: <%= !isCleanArchitecture %>
force: true
---
<%- typeof generatedBanner !== 'undefined' ? generatedBanner : '' %>
/**
 * <%= className %> DTOs
 * Generated by entity codegen - do not edit directly
 */

import { z } from 'zod';
<% if (hasEntityRefFields) { -%>
import { entityTypeSchema } from '<%= locations.dbContextEngine.import %>';
<% } -%>

export const create<%= className %>Schema = z.object({
<% fields.forEach((field) => { -%>
<% let zodChain = field.zodType; -%>
<% if (field.type === 'string' && field.maxLength) { zodChain += `.max(${field.maxLength})`; } -%>
<% if (field.type === 'string' && field.minLength) { zodChain += `.min(${field.minLength})`; } -%>
<% if (['integer', 'decimal'].includes(field.type) && field.min !== undefined) { zodChain += `.min(${field.min})`; } -%>
<% if (['integer', 'decimal'].includes(field.type) && field.max !== undefined) { zodChain += `.max(${field.max})`; } -%>
<% if (field.choices) { zodChain = `z.enum([${field.choices.map(c => `'${c}'`).join(', ')}])`; } -%>
<% if (field.nullable) { zodChain += '.nullable()'; } -%>
<% if (!field.required) { zodChain += '.optional()'; } -%>
	<%- field.camelName %>: <%- zodChain %>,
<% }) -%>
});

export type Create<%= className %>Dto = z.infer<typeof create<%= className %>Schema>;

export const update<%= className %>Schema = z.object({
<% fields.forEach((field) => { -%>
<% let zodChain = field.zodType; -%>
<% if (field.type === 'string' && field.maxLength) { zodChain += `.max(${field.maxLength})`; } -%>
<% if (field.type === 'string' && field.minLength) { zodChain += `.min(${field.minLength})`; } -%>
<% if (['integer', 'decimal'].includes(field.type) && field.min !== undefined) { zodChain += `.min(${field.min})`; } -%>
<% if (['integer', 'decimal'].includes(field.type) && field.max !== undefined) { zodChain += `.max(${field.max})`; } -%>
<% if (field.choices) { zodChain = `z.enum([${field.choices.map(c => `'${c}'`).join(', ')}])`; } -%>
<% if (field.nullable) { zodChain += '.nullable()'; } -%>
	<%- field.camelName %>: <%- zodChain %>.optional(),
<% }) -%>
});

export type Update<%= className %>Dto = z.infer<typeof update<%= className %>Schema>;

// OPENAPI-3: response schema — mirrors the select shape of this entity so
// controller `@ApiResponse({ schema: { $ref: '.../<%= className %>ResponseDto' } })`
// decorators resolve to a fully-typed document on /docs-json.
export const <%= camelName %>ResponseSchema = z.object({
	id: z.string().uuid(),
<% fields.forEach((field) => { -%>
<% let zodChain = field.zodType; -%>
<% if (field.type === 'string' && field.maxLength) { zodChain += `.max(${field.maxLength})`; } -%>
<% if (field.type === 'string' && field.minLength) { zodChain += `.min(${field.minLength})`; } -%>
<% if (['integer', 'decimal'].includes(field.type) && field.min !== undefined) { zodChain += `.min(${field.min})`; } -%>
<% if (['integer', 'decimal'].includes(field.type) && field.max !== undefined) { zodChain += `.max(${field.max})`; } -%>
<% if (field.choices) { zodChain = `z.enum([${field.choices.map(c => `'${c}'`).join(', ')}])`; } -%>
<% if (field.nullable) { zodChain += '.nullable()'; } -%>
	<%- field.camelName %>: <%- zodChain %>,
<% }) -%>
<% if (hasTimestamps) { -%>
	createdAt: z.coerce.date(),
	updatedAt: z.coerce.date(),
<% } -%>
<% if (hasSoftDelete) { -%>
	deletedAt: z.coerce.date().nullable(),
<% } -%>
<% if (hasTemporalValidity) { -%>
	validFrom: z.coerce.date().nullable(),
	validTo: z.coerce.date().nullable(),
	isActive: z.boolean(),
<% } -%>
});

export type <%= className %>ResponseDto = z.infer<typeof <%= camelName %>ResponseSchema>;
