// @generated by @pattern-stack/codegen from test/fixtures/entities/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable } from '@nestjs/common';
import { DealStateService } from '../deal-state.service';
import type { CreateDealStateDto } from '../dto/create-deal-state.dto';
import type { DealState } from '../deal-state.entity';

@Injectable()
export class CreateDealStateUseCase {
  constructor(private readonly service: DealStateService) {}

  async execute(
    dto: CreateDealStateDto,
  ): Promise<DealState> {
    return this.service.create(dto);
  }
}
