// @generated by @pattern-stack/codegen from test/fixtures/entities/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, NotFoundException } from '@nestjs/common';
import { DealStateService } from '../deal-state.service';
import type {
  DealStateInclude,
  DealStateNoInclude,
  DealStateResult,
} from '../deal-state.repository';

@Injectable()
export class FindDealStateByIdUseCase {
  constructor(private readonly service: DealStateService) {}

  /**
   * `include` is a typed include TREE, not a client string — the controller has
   * already resolved `?include=` against the route's allowlist and rejected
   * anything it does not name (REL-2 §5). An internal caller passes the tree
   * directly and gets the exact nested result type back, because `TWith` is
   * inferred at the call site.
   */
  async execute<TWith extends DealStateInclude = DealStateNoInclude>(
    id: string,
    include?: TWith,
  ): Promise<DealStateResult<TWith>> {
    const entity = await this.service.findById<TWith>(
      id,
      include === undefined ? undefined : { with: include },
    );
    if (entity === null || entity === undefined) {
      throw new NotFoundException(`DealState not found: ${id}`);
    }
    return entity;
  }
}
