/**
 * Create User Command
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add business logic here):
 * - Validation: Add domain validation rules before creating
 * - Defaults: Compute default values not handled by DTO
 * - Side effects: Emit events, send notifications, create related entities
 * - Authorization: Check user permissions beyond route-level auth
 * - Audit: Log creation for compliance/debugging
 */

import { Inject, Injectable } from '@nestjs/common';
import { USER_REPOSITORY } from '../../../constants';
import type { CreateUserInput, IUserRepository } from '../../../domain';
import { User } from '../../../domain';
import type { CreateUserDto } from '../../schemas';

@Injectable()
export class CreateUserCommand {
	constructor(
		@Inject(USER_REPOSITORY)
		private readonly userRepository: IUserRepository,
	) {}

	async execute(dto: CreateUserDto): Promise<User> {
		// TODO: Add pre-create validation and business rules here

		// Map DTO to domain input
		const input: CreateUserInput = {
			tenantId: dto.tenantId,
			email: dto.email,
			personId: dto.personId ?? null,
		};

		const created = await this.userRepository.create(input);

		// TODO: Add post-create side effects here (events, notifications, etc.)

		return created;
	}
}
