/**
 * Delete User Command
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add business logic here):
 * - Authorization: Check if user can delete this specific record
 * - Referential integrity: Check for dependent records, cascade or block
 * - Soft delete: Mark as deleted instead of hard delete
 * - Side effects: Emit events, clean up related data, notify subscribers
 * - Audit: Log deletion for compliance/debugging
 */

import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { USER_REPOSITORY } from '../../../constants';
import type { IUserRepository } from '../../../domain';
import { User } from '../../../domain';

@Injectable()
export class DeleteUserCommand {
	constructor(
		@Inject(USER_REPOSITORY)
		private readonly userRepository: IUserRepository,
	) {}

	async execute(id: string): Promise<User> {
		// TODO: Add pre-delete validation here
		// e.g., check for dependent records, verify user permissions

		const deleted = await this.userRepository.delete(id);
		if (!deleted) {
			throw new NotFoundException(`User with id ${id} not found`);
		}

		// TODO: Add post-delete side effects here (events, cleanup, etc.)

		return deleted;
	}
}
