/**
 * Update User Command
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add business logic here):
 * - Validation: Add domain validation rules (e.g., state transitions)
 * - Authorization: Check if user can modify this specific record
 * - Conflict detection: Optimistic locking, version checks
 * - Side effects: Emit events, invalidate caches, notify subscribers
 * - Audit: Log changes for compliance/debugging
 */

import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { USER_REPOSITORY } from '../../../constants';
import type { IUserRepository, UpdateUserInput } from '../../../domain';
import { User } from '../../../domain';
import type { UpdateUserDto } from '../../schemas';

@Injectable()
export class UpdateUserCommand {
	constructor(
		@Inject(USER_REPOSITORY)
		private readonly userRepository: IUserRepository,
	) {}

	async execute(id: string, dto: UpdateUserDto): Promise<User> {
		const existing = await this.userRepository.findById(id);
		if (!existing) {
			throw new NotFoundException(`User with id ${id} not found`);
		}

		// TODO: Add pre-update validation and business rules here
		// e.g., check state transitions, verify user permissions on this record

		// Map DTO to domain input (only include defined fields)
		const input: UpdateUserInput = {
			...(dto.tenantId !== undefined && { tenantId: dto.tenantId }),
			...(dto.email !== undefined && { email: dto.email }),
			...(dto.personId !== undefined && { personId: dto.personId }),
		};

		const updated = await this.userRepository.update(id, input);
		if (!updated) {
			throw new NotFoundException(`User with id ${id} not found`);
		}

		// TODO: Add post-update side effects here (events, cache invalidation, etc.)

		return updated;
	}
}
