---
to: <%= locations.dbSchemaClient.path %>
force: false
---
/**
 * Monolithic client schema (Drizzle + Zod)
 * Generated by entity codegen - do not edit directly
 */

import { createSelectSchema } from 'drizzle-zod';
import { relations } from 'drizzle-orm';
import {
	getTableConfig,
	pgTable,
	uuid,
	text,
	varchar,
	integer,
	boolean,
	timestamp,
	date,
	jsonb,
	numeric,
	pgEnum,
	index,
} from 'drizzle-orm/pg-core';
import { entityTypeEnum } from './entity-types.schema';

// Codegen tables

// Codegen exports
