/**
 * User Repository Interface
 * Generated by entity codegen - do not edit directly
 */

import type { User } from './user.entity';

/**
 * Type-safe eager loading options.
 * Pass to repository methods to include related entities.
 */
export type UserWith = {
	person?: boolean;
	owned_opportunities?: boolean;
};

/**
 * Domain-level input types for repository operations.
 */
export type CreateUserInput = {
	tenantId: string;
	email: string;
	personId?: string | null;
};

export type UpdateUserInput = Partial<CreateUserInput>;

export interface IUserRepository {
	create(input: CreateUserInput): Promise<User>;
	findById(id: string, include?: UserWith): Promise<User | null>;
	findAll(include?: UserWith): Promise<User[]>;
	update(id: string, input: UpdateUserInput): Promise<User | null>;
	delete(id: string): Promise<User | null>;
	findByPersonId(id: string, include?: UserWith): Promise<User[]>;
}
