/**
 * User Domain Entity
 * Generated by entity codegen - do not edit directly
 *
 * NOTE: Related entity imports assume a nested folder structure where each entity
 * lives in its own folder (e.g., domain/{entity}/{entity}.entity.ts). This follows
 * CLEAN architecture conventions where each aggregate root has its own bounded context.
 * All entities should follow this structure for consistent imports.
 */

export class User {
	constructor(
		public readonly id: string,
		public readonly tenantId: string,
		public readonly email: string,
		public readonly personId: string | null,
	) {}

	static fromRecord(
		// biome-ignore lint/suspicious/noExplicitAny: Drizzle records have dynamic shape
		record: Record<string, any>,
	): User {
		return new User(
			record.id,
			record.tenantId,
			record.email,
			record.personId,
		);
	}
}
