---
to: "<%= exposeElectric && databaseDialect === 'postgres' ? `${locations.dbMigrations.path}/${new Date().toISOString().replace(/[-:T]/g, '').slice(0, 14)}_Add${classNamePlural}ToElectric.sql` : '' %>"
force: true
---
-- Electric SQL setup for <%= table %>
-- Generated by entity codegen

-- Enable full row logging for Electric replication
ALTER TABLE "<%= table %>" REPLICA IDENTITY FULL;

-- Add table to Electric publication if not already a member
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'electric_publication_default' AND tablename = '<%= table %>'
    ) THEN
        ALTER PUBLICATION electric_publication_default ADD TABLE "<%= table %>";
    END IF;
END $$;
