// @generated by @pattern-stack/codegen from test/fixtures/entities/opportunity.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import {
  date,
  index,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';
import { type InferSelectModel } from 'drizzle-orm';
import { organizations } from '../organizations/organization.entity';
import { users } from '../users/user.entity';
import { deal_states } from '../deal-states/deal-state.entity';
import { tenants } from '../tenants/tenant.entity';

export const opportunities = pgTable(
  'opportunities',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    organizationId: uuid('organization_id').notNull().references((): AnyPgColumn => organizations.id, { onDelete: 'restrict' }),
    ownerId: uuid('owner_id').notNull().references((): AnyPgColumn => users.id, { onDelete: 'restrict' }),
    stateId: uuid('state_id').notNull().references((): AnyPgColumn => deal_states.id, { onDelete: 'restrict' }),
    tenantId: uuid('tenant_id').notNull().references((): AnyPgColumn => tenants.id),
    name: text('name').notNull(),
    amount: numeric('amount'),
    currency: text('currency').default('USD'),
    expectedCloseDate: date('expected_close_date', { mode: 'date' }),
    closedAt: timestamp('closed_at'),
  },
  (t) => [
    index('opportunities_organization_id_idx').on(t.organizationId),
    index('opportunities_owner_id_idx').on(t.ownerId),
    index('opportunities_state_id_idx').on(t.stateId),
    index('opportunities_tenant_id_idx').on(t.tenantId),
  ],
);

export type Opportunity = InferSelectModel<typeof opportunities>;
export type OpportunityInsert = typeof opportunities.$inferInsert;
