// @generated by @pattern-stack/codegen from test/fixtures/entities/opportunity.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, Inject, Optional } from '@nestjs/common';
import { WithAnalytics } from '@shared/base-classes/with-analytics';
import { EVENT_BUS } from '@shared/constants/tokens';
import { BaseService } from '@shared/base-classes/base-service';
import { OpportunityRepository } from './opportunity.repository';
import type {
  OpportunityInclude,
  OpportunityNoInclude,
  OpportunityResult,
} from './opportunity.repository';
import type { ListOptions } from '@shared/base-classes/base-repository';
import type { Opportunity } from './opportunity.entity';
import { OrganizationRepository } from '../organizations/organization.repository';
import type { Organization } from '../organizations/organization.entity';
import { UserRepository } from '../users/user.repository';
import type { User } from '../users/user.entity';
import { DealStateRepository } from '../deal-states/deal-state.repository';
import type { DealState } from '../deal-states/deal-state.entity';

@Injectable()
export class OpportunityService extends WithAnalytics(
  BaseService<OpportunityRepository, Opportunity>,
) {
  protected override readonly entityName = 'opportunity';

  /** Injected by NestJS when EventsModule is registered. */
  @Optional() @Inject(EVENT_BUS)
  protected override eventBus: any = undefined;

  constructor(
    protected override readonly repository: OpportunityRepository,
    private readonly organizationRepo: OrganizationRepository,
    private readonly userRepo: UserRepository,
    private readonly dealStateRepo: DealStateRepository,
  ) {
    super(repository);
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Typed `with` includes (REL-2, #587) — pass-through, not composition
  //
  // These two overrides exist so the HTTP layer can carry an allowlisted include
  // from the controller to the repository. They are DELEGATION ONLY: no join
  // logic, no sibling-repository calls, no navigator. The typed navigator and the
  // deletion of the CGP-358b composition methods below are REL-3's (#588).
  // ═══════════════════════════════════════════════════════════════════════

  override findById<TWith extends OpportunityInclude = OpportunityNoInclude>(
    id: string,
    opts?: { with?: TWith },
  ): Promise<OpportunityResult<TWith> | null> {
    return this.repository.findById<TWith>(id, opts);
  }

  override list<TWith extends OpportunityInclude = OpportunityNoInclude>(
    options?: ListOptions & { with?: TWith },
  ): Promise<Array<OpportunityResult<TWith>>> {
    return this.repository.list<TWith>(options);
  }

  // Lifecycle events (created/updated/deleted + per-field changes) are emitted
  // automatically by BaseService when the events subsystem is installed.
  //
  // Inherited from BaseService:
  //   findById, findByIds, list, count, exists, create, update, delete

  // ═══════════════════════════════════════════════════════════════════════
  // Relationship composition methods (CGP-358b / CGP-62)
  // Two queries, no SQL JOIN.
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Fetch the Organization parent for this Opportunity.
   * Two repo calls: find self by id → find target by FK.
   */
  async organization(opportunityId: string): Promise<Organization | null> {
    const entity = await this.repository.findById(opportunityId);
    if (!entity) return null;
    return entity.organizationId ? this.organizationRepo.findById(entity.organizationId) : null;
  }

  /**
   * Fetch the User parent for this Opportunity.
   * Two repo calls: find self by id → find target by FK.
   */
  async user(opportunityId: string): Promise<User | null> {
    const entity = await this.repository.findById(opportunityId);
    if (!entity) return null;
    return entity.ownerId ? this.userRepo.findById(entity.ownerId) : null;
  }

  /**
   * Fetch the DealState parent for this Opportunity.
   * Two repo calls: find self by id → find target by FK.
   */
  async deal_state(opportunityId: string): Promise<DealState | null> {
    const entity = await this.repository.findById(opportunityId);
    if (!entity) return null;
    return entity.stateId ? this.dealStateRepo.findById(entity.stateId) : null;
  }
}
