// @generated by @pattern-stack/codegen from test/fixtures/entities/demo-deal.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, NotFoundException } from '@nestjs/common';
import { DealService } from '../deal.service';
import type { Deal } from '../deal.entity';

@Injectable()
export class FindDealByIdUseCase {
  constructor(private readonly service: DealService) {}

  async execute(id: string): Promise<Deal> {
    const entity = await this.service.findById(id);
    if (entity === null || entity === undefined) {
      throw new NotFoundException(`Deal not found: ${id}`);
    }
    return entity;
  }
}
