---
to: "<%= configPath %>"
inject: true
append: true
skip_if: "openapi:"
---

openapi:
  # ── Master switch (OPENAPI-4) ──
  # When false the `main.ts` bootstrap skips Swagger setup entirely — no
  # `/docs` route, no `/docs-json`, no BearerAuth scheme. Generated
  # controllers still emit `@nestjs/swagger` decorators (see gotchas in
  # CONSUMER-SETUP §OpenAPI) so you must keep the peer dep installed
  # either way.
  enabled: true

  # ── Mount point for Swagger UI (+ the JSON spec at `<path>-json`) ──
  # '/docs' is the locked default; any path works. Conventional
  # alternatives: '/api-docs', '/openapi', '/swagger'.
  path: /docs

  # ── Document metadata rendered in Swagger UI ──
  # `title` appears as the page heading; `version` in the header badge.
  # `description` is the paragraph beneath the title.
  title: My App
  version: 0.1.0
  description: Generated by @pattern-stack/codegen

  # ── Default security scheme ──
  # 'bearer' registers `components.securitySchemes.bearer` as
  # `{ type: 'http', scheme: 'bearer', bearerFormat: 'JWT' }` and applies
  # it globally via `document.security = [{ bearer: [] }]`. Controllers
  # already emit `@ApiBearerAuth()` at the class level (OPENAPI-3), so
  # Swagger UI's "Authorize" button renders out of the box.
  auth: bearer
