/**
 * Adapter / module / barrel / surface-aggregator emission (RFC-0001 §2 + §4,
 * Track D · D3).
 *
 * Per (provider × surface) — driven by `definitions/providers/*.yaml`
 * `surfaces[]` ∩ the surfaces a `<Surface>Port` package exists for — emits the
 * layer that ties D2's provider modules, C6's `<Surface>Port`, and C7's
 * `IEntityChangeSourceRegistry` together:
 *
 *   src/integrations/<surface>/
 *     adapters/
 *       <provider>/<provider>-<surface>.adapter.ts          SCAFFOLD (emit-once)
 *       <provider>/<provider>-<surface>.adapter.module.ts   @generated (re-emit)
 *       index.ts                                            @generated barrel
 *     <surface>-adapters.tokens.ts                          @generated (minimal — D4 owns full)
 *     <surface>-adapters.module.ts                          @generated aggregator
 *
 * **Surface → port mapping.** A scaffold `implements <Surface>Port`, so a
 * surface is only emittable once its surface package exists (Track C). Today
 * only `crm` (CrmPort, C6) does; a provider serving `calendar`/`mail`/etc. is
 * recorded in `skippedSurfaces` with a clear reason until that surface's
 * package lands. This is the deliberate seam, not an omission.
 *
 * **Emit-once.** The adapter scaffold carries a `// <CODEGEN-SCAFFOLD-V1>`
 * sentinel; on re-emit an existing scaffold is detected and skipped
 * (author-owned). Everything else is fully codegen-owned and re-emitted
 * byte-identically (RFC-0001 §2 idempotency).
 *
 * **D4 boundary.** The registry tokens' full contract (multi-injection
 * semantics, the AdapterContribution fold, per-consumer typed views, removal of
 * ADR-033.2 tuples) is Track D · D4. D3 emits a *minimal* tokens file so the
 * modules compile and notes D4 owns the finalized contract — it does not pull
 * D4 forward.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { parseImportRef, type ProviderDefinition } from "../../schema/provider-definition.schema";
import type { LoadedProvider } from "../../parser/validate-providers";
import { providerConstantCase, providerPascalCase } from "./provider-module-generator";

// ============================================================================
// Surface registry — which surfaces have an emittable <Surface>Port package
// ============================================================================

interface L2PortSpec {
  /** Property name on the port (`fields`). */
  prop: string;
  /** Port interface type (`IFieldDefinitionReader`). */
  type: string;
  /** Stub method name (`list`). */
  method: string;
  /** Stub method parameter list, args underscore-prefixed (`(_integrationId, _entity)`). */
  params: string;
  /** Matching `CrmCapabilities` flag (`fieldDefinitions`). */
  capFlag: string;
}

interface SurfaceSpec {
  /** Package the port + vocab come from. */
  packageName: string;
  /** Composing port type (`CrmPort`). */
  portType: string;
  /** Capabilities type (`CrmCapabilities`). */
  capabilitiesType: string;
  /** Empty-capabilities const (`NO_CRM_CAPABILITIES`). */
  noCapsConst: string;
  /** L2 ports the adapter implements (stubbed). */
  l2Ports: L2PortSpec[];
}

/**
 * Known surfaces. Extend as Track C ships more surface packages (mail,
 * calendar, transcript, …). A provider surface absent here is skipped.
 */
export const SURFACE_REGISTRY: Record<string, SurfaceSpec> = {
  crm: {
    packageName: "@pattern-stack/codegen-crm",
    portType: "CrmPort",
    capabilitiesType: "CrmCapabilities",
    noCapsConst: "NO_CRM_CAPABILITIES",
    l2Ports: [
      {
        prop: "fields",
        type: "IFieldDefinitionReader",
        method: "list",
        params: "(_integrationId, _entity)",
        capFlag: "fieldDefinitions",
      },
      {
        prop: "picklists",
        type: "IPicklistReader",
        method: "values",
        params: "(_integrationId, _entity, _fieldId)",
        capFlag: "picklists",
      },
      {
        prop: "associations",
        type: "IAssociationReader",
        method: "list",
        params: "(_integrationId, _fromEntity, _fromId, _toEntity)",
        capFlag: "associations",
      },
    ],
  },
};

// ============================================================================
// Banner + sentinel
// ============================================================================

const SCAFFOLD_SENTINEL = "// <CODEGEN-SCAFFOLD-V1>";

function generatedBanner(sourceDesc: string): string {
  return (
    `// @generated by @pattern-stack/codegen from ${sourceDesc} — DO NOT EDIT.\n` +
    `// Hand edits are overwritten on re-emit. Regenerate with \`bun run codegen\`.`
  );
}

// ============================================================================
// Entities-by-surface
// ============================================================================

/**
 * Group entity names by their declared `surface:` (the field added in D1). The
 * union per surface populates each adapter's `capabilities.entities`.
 */
export function collectEntitiesBySurface(
  entities: Iterable<{ entity: { name: string }; surface?: string }>,
): Map<string, string[]> {
  const bySurface = new Map<string, string[]>();
  for (const e of entities) {
    if (!e.surface) continue;
    const list = bySurface.get(e.surface) ?? [];
    list.push(e.entity.name);
    bySurface.set(e.surface, list);
  }
  // Deterministic order within each surface.
  for (const [surface, list] of bySurface) {
    bySurface.set(surface, [...list].sort());
  }
  return bySurface;
}

// ============================================================================
// Naming
// ============================================================================

interface Names {
  providerPascal: string; // Hubspot
  providerConst: string; // HUBSPOT
  surfacePascal: string; // Crm
  surfaceConst: string; // CRM
  adapterClass: string; // HubspotCrmAdapter
  adapterModuleClass: string; // HubspotCrmAdapterModule
  providerModuleClass: string; // HubspotProviderModule
  aggregatorClass: string; // CrmAdaptersModule
  strategyToken: string; // HUBSPOT_AUTH_STRATEGY
  clientToken: string; // HUBSPOT_CLIENT
  contributionsToken: string; // CRM_ADAPTER_CONTRIBUTIONS
  entitySourcesToken: string; // CRM_ENTITY_SOURCES
}

function names(providerSlug: string, surface: string): Names {
  const providerPascal = providerPascalCase(providerSlug);
  const providerConst = providerConstantCase(providerSlug);
  const surfacePascal = providerPascalCase(surface);
  const surfaceConst = providerConstantCase(surface);
  return {
    providerPascal,
    providerConst,
    surfacePascal,
    surfaceConst,
    adapterClass: `${providerPascal}${surfacePascal}Adapter`,
    adapterModuleClass: `${providerPascal}${surfacePascal}AdapterModule`,
    providerModuleClass: `${providerPascal}ProviderModule`,
    aggregatorClass: `${surfacePascal}AdaptersModule`,
    strategyToken: `${providerConst}_AUTH_STRATEGY`,
    clientToken: `${providerConst}_CLIENT`,
    contributionsToken: `${surfaceConst}_ADAPTER_CONTRIBUTIONS`,
    entitySourcesToken: `${surfaceConst}_ENTITY_SOURCES`,
  };
}

// ============================================================================
// Pure emitters
// ============================================================================

/**
 * The emit-once adapter scaffold. Implements the surface port, injects L1
 * (auth strategy + client) and the entity sources registry, declares
 * capabilities (entities from `surface:`), and stubs the L2 port methods.
 */
export function generateAdapterScaffold(
  def: ProviderDefinition,
  surface: string,
  entities: string[],
): string {
  const spec = SURFACE_REGISTRY[surface];
  if (!spec) throw new Error(`no surface package for '${surface}'`);
  const n = names(def.slug, surface);
  const client = parseImportRef(def.client.class);

  const l2TypeImports = spec.l2Ports.map((p) => p.type).join(",\n  ");
  const entitiesLiteral = entities.length
    ? `[${entities.map((e) => `'${e}'`).join(", ")}]`
    : "[]";

  const capabilityLines = spec.l2Ports
    .map((p) => `    ${p.capFlag}: true,`)
    .join("\n");

  const l2Members = spec.l2Ports
    .map(
      (p) => `  /** L2 — fill in the provider-specific implementation. */
  readonly ${p.prop}: ${p.type} = {
    ${p.method}: async ${p.params} => {
      throw new Error('not implemented: ${n.adapterClass}.${p.prop}.${p.method}');
    },
  };`,
    )
    .join("\n\n");

  return `${SCAFFOLD_SENTINEL}
// Scaffolded once by @pattern-stack/codegen, then author-owned. Re-running
// codegen detects the sentinel above and SKIPS this file — your edits are safe.
// Source: definitions/providers/${def.slug}.yaml (surface: ${surface}).
import { Inject, Injectable } from '@nestjs/common';
import type {
  ${spec.portType},
  ${l2TypeImports},
  ${spec.capabilitiesType},
} from '${spec.packageName}';
import { ${spec.noCapsConst} } from '${spec.packageName}';
import type {
  IAuthStrategy,
  IEntityChangeSourceRegistry,
} from '@pattern-stack/codegen/subsystems';
import type { ${client.exportName} } from '${client.path}';
import { ${n.strategyToken}, ${n.clientToken} } from '../../../providers/${def.slug}/${def.slug}.provider.module';
import { ${n.entitySourcesToken} } from '../../${surface}-adapters.tokens';

@Injectable()
export class ${n.adapterClass} implements ${spec.portType} {
  /** Declared capabilities. \`entities\` derives from \`surface: ${surface}\` entity YAML. */
  readonly capabilities: ${spec.capabilitiesType} = {
    ...${spec.noCapsConst},
${capabilityLines}
    entities: ${entitiesLiteral},
  };

  constructor(
    @Inject(${n.strategyToken}) readonly auth: IAuthStrategy,
    @Inject(${n.clientToken}) private readonly client: ${client.exportName},
    @Inject(${n.entitySourcesToken}) readonly sources: IEntityChangeSourceRegistry,
  ) {}

${l2Members}

  // surface-only methods (optional on ${spec.portType}): add here
}
`;
}

/** Fully codegen-owned adapter module — wires the adapter + its provider module. */
export function generateAdapterModule(def: ProviderDefinition, surface: string): string {
  const n = names(def.slug, surface);
  return `${generatedBanner(`definitions/providers/${def.slug}.yaml (surface: ${surface})`)}
import { Module } from '@nestjs/common';
import { ${n.providerModuleClass} } from '../../../providers/${def.slug}/${def.slug}.provider.module';
import { ${n.contributionsToken} } from '../../${surface}-adapters.tokens';
import { ${n.adapterClass} } from './${def.slug}-${surface}.adapter';

@Module({
  imports: [${n.providerModuleClass}],
  providers: [
    ${n.adapterClass},
    // Contributes this provider's adapter to the surface registry. The
    // multi-injection + (provider, entity) source fold is finalized by D4;
    // D3 emits the contribution shape.
    {
      provide: ${n.contributionsToken},
      useFactory: (adapter: ${n.adapterClass}) => ({
        provider: '${def.slug}',
        sources: {}, // D4: populated from the adapter's per-entity change sources.
      }),
      inject: [${n.adapterClass}],
    },
  ],
  exports: [${n.adapterClass}],
})
export class ${n.adapterModuleClass} {}
`;
}

/** Auto-generated barrel re-exporting every adapter module for a surface. */
export function generateAdaptersBarrel(
  surface: string,
  providerSlugs: string[],
): string {
  const lines = [...providerSlugs]
    .sort()
    .map((slug) => {
      const n = names(slug, surface);
      return `export { ${n.adapterModuleClass} } from './${slug}/${slug}-${surface}.adapter.module';`;
    })
    .join("\n");
  return `${generatedBanner(`definitions/providers/*.yaml (surface: ${surface})`)}
${lines}
`;
}

/**
 * Minimal per-surface registry tokens (D3). The full contract — multi-injection
 * semantics, the AdapterContribution → IEntityChangeSourceRegistry fold keyed by
 * (provider, entity), collision-is-a-boot-error — is owned by Track D · D4
 * (RFC-0001 §3). Emitted here only so the adapter modules + aggregator compile.
 */
export function generateSurfaceTokens(surface: string): string {
  const n = names("__placeholder__", surface);
  return `${generatedBanner(`surface: ${surface} (minimal — Track D D4 owns the full registry contract)`)}
import type { IChangeSource } from '@pattern-stack/codegen/subsystems';

/** Multi-injection token: each adapter module contributes one AdapterContribution. */
export const ${n.contributionsToken} = Symbol.for('@app/integrations/${surface}.adapter-contributions');

/** Resolved registry token — resolves to a C7 IEntityChangeSourceRegistry. */
export const ${n.entitySourcesToken} = Symbol.for('@app/integrations/${surface}.entity-sources');

/** One provider-adapter's contribution to the surface registry. D4 finalizes. */
export interface AdapterContribution {
  /** Provider slug. */
  provider: string;
  /** Entities this provider serves on this surface → their change sources. */
  sources: Record<string, IChangeSource<unknown>>;
}
`;
}

/**
 * The thin factory aggregator — folds all adapter contributions into one
 * `IEntityChangeSourceRegistry` bound under `<SURFACE>_ENTITY_SOURCES`
 * (RFC-0001 §3). The multi-injection wiring is finalized by D4; D3 emits the
 * fold + the module shape.
 */
export function generateSurfaceAggregator(
  surface: string,
  providerSlugs: string[],
): string {
  const n = names("__placeholder__", surface);
  const moduleClasses = [...providerSlugs]
    .sort()
    .map((slug) => names(slug, surface).adapterModuleClass);
  const importLines = moduleClasses
    .map((cls) => `import { ${cls} } from './adapters';`)
    .join("\n");

  return `${generatedBanner(`surface: ${surface}`)}
import { Module } from '@nestjs/common';
import {
  MemoryEntityChangeSourceRegistry,
  type IChangeSource,
  type IEntityChangeSourceRegistry,
} from '@pattern-stack/codegen/subsystems';
${importLines}
import {
  ${n.contributionsToken},
  ${n.entitySourcesToken},
  type AdapterContribution,
} from './${surface}-adapters.tokens';

/**
 * Fold every adapter contribution into one entity-keyed registry, keyed by
 * (provider, entity). A collision on (provider, entity) is a boot error. The
 * multi-injection that supplies the full \`contribs\` array is finalized by D4.
 */
function provide${n.surfacePascal}EntitySources(
  contribs: AdapterContribution[],
): IEntityChangeSourceRegistry {
  const merged = new Map<string, IChangeSource<unknown>>();
  const seen = new Set<string>();
  for (const contrib of contribs ?? []) {
    for (const [entity, source] of Object.entries(contrib.sources)) {
      const key = \`\${contrib.provider}:\${entity}\`;
      if (seen.has(key)) {
        throw new Error(\`duplicate change source for (\${contrib.provider}, \${entity})\`);
      }
      seen.add(key);
      merged.set(entity, source);
    }
  }
  return new MemoryEntityChangeSourceRegistry(merged);
}

@Module({
  imports: [${moduleClasses.join(", ")}],
  providers: [
    {
      provide: ${n.entitySourcesToken},
      // D4: inject the multi-bound ${n.contributionsToken} array here.
      useFactory: (...contribs: AdapterContribution[]) =>
        provide${n.surfacePascal}EntitySources(contribs),
      inject: [${n.contributionsToken}],
    },
  ],
  exports: [${n.entitySourcesToken}],
})
export class ${n.aggregatorClass} {}
`;
}

// ============================================================================
// Orchestration
// ============================================================================

export interface EmitAdaptersOptions {
  providers: LoadedProvider[];
  /** Entity definitions carrying `surface:` (for capabilities.entities). */
  entities: Array<{ entity: { name: string }; surface?: string }>;
  /** Output root — `<backend_src>/integrations`. */
  outputRoot: string;
  /** When true, compute the plan but write nothing. */
  dryRun?: boolean;
}

export interface EmitAdaptersResult {
  /** @generated files written (modules, barrels, tokens, aggregators). */
  written: string[];
  /** New scaffolds written this run. */
  scaffoldsWritten: string[];
  /** Existing scaffolds skipped (author-owned). */
  scaffoldsSkipped: string[];
  /** (provider, surface) pairs skipped because the surface has no port package. */
  skippedSurfaces: Array<{ provider: string; surface: string; reason: string }>;
}

/**
 * Emit the adapter/module/barrel/aggregator layer for every (provider ×
 * emittable surface). Emit-once scaffolds are never overwritten; everything
 * else is re-emitted byte-identically.
 */
export function emitAdapters(opts: EmitAdaptersOptions): EmitAdaptersResult {
  const result: EmitAdaptersResult = {
    written: [],
    scaffoldsWritten: [],
    scaffoldsSkipped: [],
    skippedSurfaces: [],
  };
  const entitiesBySurface = collectEntitiesBySurface(opts.entities);

  // surface → provider slugs that serve it AND have an emittable port.
  const bySurface = new Map<string, string[]>();
  for (const { definition } of opts.providers) {
    for (const surface of definition.surfaces) {
      if (!SURFACE_REGISTRY[surface]) {
        result.skippedSurfaces.push({
          provider: definition.slug,
          surface,
          reason: `no surface package for '${surface}' yet — add codegen-${surface} (Track C) to emit its adapters`,
        });
        continue;
      }
      const list = bySurface.get(surface) ?? [];
      list.push(definition.slug);
      bySurface.set(surface, list);
    }
  }

  const defBySlug = new Map(opts.providers.map((p) => [p.definition.slug, p.definition]));

  for (const [surface, slugs] of bySurface) {
    const surfaceDir = join(opts.outputRoot, surface);
    const adaptersDir = join(surfaceDir, "adapters");

    // Per-provider adapter scaffold (emit-once) + adapter module (@generated).
    for (const slug of slugs) {
      const def = defBySlug.get(slug)!;
      const providerDir = join(adaptersDir, slug);
      const scaffoldPath = join(providerDir, `${slug}-${surface}.adapter.ts`);
      const modulePath = join(providerDir, `${slug}-${surface}.adapter.module.ts`);

      // Emit-once: never overwrite an existing scaffold.
      if (existsSync(scaffoldPath)) {
        result.scaffoldsSkipped.push(scaffoldPath);
      } else {
        const content = generateAdapterScaffold(
          def,
          surface,
          entitiesBySurface.get(surface) ?? [],
        );
        if (!opts.dryRun) writeFile(scaffoldPath, content);
        result.scaffoldsWritten.push(scaffoldPath);
      }

      const moduleContent = generateAdapterModule(def, surface);
      if (!opts.dryRun) writeIfChanged(modulePath, moduleContent);
      result.written.push(modulePath);
    }

    // Per-surface barrel + tokens + aggregator (@generated).
    const barrelPath = join(adaptersDir, "index.ts");
    const tokensPath = join(surfaceDir, `${surface}-adapters.tokens.ts`);
    const aggregatorPath = join(surfaceDir, `${surface}-adapters.module.ts`);
    const files: Array<[string, string]> = [
      [barrelPath, generateAdaptersBarrel(surface, slugs)],
      [tokensPath, generateSurfaceTokens(surface)],
      [aggregatorPath, generateSurfaceAggregator(surface, slugs)],
    ];
    for (const [path, content] of files) {
      if (!opts.dryRun) writeIfChanged(path, content);
      result.written.push(path);
    }
  }

  return result;
}

function writeFile(outPath: string, content: string): void {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, content);
}

function writeIfChanged(outPath: string, content: string): void {
  if (existsSync(outPath) && statSync(outPath).isFile() && readFileSync(outPath, "utf-8") === content) {
    return;
  }
  writeFile(outPath, content);
}
