/**
 * `<paths.generated>/app-config.ts` — the `codegen.config.yaml` values the
 * consumer's app reads at boot, written by the generator (CFG-1, #643).
 *
 * The app never parses `codegen.config.yaml`. Every key it needs at boot is a
 * generation-time fact: `openapi.*` (document metadata + mount point),
 * `auth.devAllowAnonymous` (the ADR-043 localhost escape hatch) and
 * `jobs.pools` (whose names the generated jobs wiring already bakes in). The
 * parsed, validated config (CFG-0) is emitted here; the generated `main.ts`,
 * the `project upgrade-*` blocks, `<generated>/subsystems.ts` and the
 * standalone `worker.ts` import it. Editing the YAML changes the app on the
 * next regeneration, as for every other key (I2).
 *
 * Written by `project init`, next to the subsystem barrel on every
 * `regenerateSubsystemBarrel` (every `entity new`, `subsystem install` /
 * `remove`), by `subsystem install openapi-config`, and by both codemods.
 */

import fs from 'node:fs';
import path from 'node:path';

import { OpenApiConfigSchema, type CodegenConfig } from '../../schema/codegen-config.schema.js';

/** Placeholder serialised as a bare `undefined` (JSON has none). */
const UNDEFINED = '\u0000undefined\u0000';

/** File name under `<paths.generated>`; import it as `<generated>/app-config`. */
export const APP_CONFIG_FILE = 'app-config.ts';

/** The module's content for a parsed config (`null` ⇒ no config file ⇒ the schema defaults). */
export function buildAppConfigContent(config: CodegenConfig | null): string {
	// Every declared key is emitted — an optional one as `undefined` — so the
	// `as const` type carries it whether or not the YAML set it.
	const { description, ...openapiRest } = OpenApiConfigSchema.parse(config?.openapi ?? {});
	const openapi = { ...openapiRest, description: description ?? UNDEFINED };
	const auth = { devAllowAnonymous: config?.auth.devAllowAnonymous ?? false };
	const jobPools = config?.jobs?.pools ?? {};
	const literal = (value: unknown) =>
		JSON.stringify(value, null, 2).replaceAll(JSON.stringify(UNDEFINED), 'undefined');
	return `// @generated by @pattern-stack/codegen from codegen.config.yaml. DO NOT EDIT.
// Regenerated by \`codegen entity new\`, \`codegen subsystem install\` and
// \`codegen project init\`. Edit codegen.config.yaml and regenerate — the app
// never reads the YAML itself (CFG-1).

/** \`openapi:\` — Swagger UI + the \`<path>-json\` document (OPENAPI-4). */
export const openapiConfig = ${literal(openapi)} as const;

/**
 * \`auth:\` — \`devAllowAnonymous\` lets an app with no IUserContext bound serve an
 * UNAUTHENTICATED data plane instead of refusing to boot (ADR-043 §4).
 * LOCALHOST DEV ONLY.
 */
export const authConfig = ${literal(auth)} as const;

/**
 * \`jobs.pools\` — overrides merged onto the five framework pools by
 * \`JobsDomainModule.forRoot({ pools })\` (validated at generation).
 */
export const jobPools = ${literal(jobPools)} as const;
`;
}

/** Write `<generatedDir>/app-config.ts`. Returns the absolute path. */
export function writeAppConfig(generatedDir: string, config: CodegenConfig | null): string {
	const target = path.join(generatedDir, APP_CONFIG_FILE);
	fs.mkdirSync(generatedDir, { recursive: true });
	fs.writeFileSync(target, buildAppConfigContent(config));
	return target;
}

/**
 * Write `<generatedDir>/app-config.ts` unless its content is already current
 * (or `dryRun`). Returns what the write would do — for the codemods' reports.
 */
export function syncAppConfig(
	generatedDir: string,
	config: CodegenConfig | null,
	dryRun: boolean,
): 'created' | 'updated' | 'unchanged' {
	const target = path.join(generatedDir, APP_CONFIG_FILE);
	const content = buildAppConfigContent(config);
	const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf-8') : null;
	if (existing === content) return 'unchanged';
	if (!dryRun) {
		fs.mkdirSync(generatedDir, { recursive: true });
		fs.writeFileSync(target, content);
	}
	return existing === null ? 'created' : 'updated';
}
