/**
 * Event codegen generator — writes codegen-owned TypeScript artifacts derived
 * from `events/*.yaml` plus entity `events:` block desugaring.
 *
 * Output: runtime/subsystems/events/generated/{types,schemas,registry,bus,index}.ts
 *
 * Consumer usage:
 *   import { TypedEventBus, eventPayloadSchemas, getEventMetadata } from
 *     './runtime/subsystems/events/generated';
 *   import type { AppDomainEvent, EventTypeName, PayloadOfType }
 *     from './runtime/subsystems/events/generated';
 *
 * Pattern mirrors scope-entity-type-generator.ts: HEADER constant, pure
 * content-builders unit-tested in isolation, one orchestrating entrypoint that
 * handles disk I/O with dryRun semantics.
 *
 * See EVT-3 spec, ADR-024 §"Generated artifacts".
 */

import fs from 'node:fs';
import path from 'node:path';

import type { AnalysisIssue } from '../../analyzer/types.js';
import { loadEntityFromYaml } from '../../utils/yaml-loader.js';
import {
	desugarEntityEvents,
	loadEvents,
	type LoadEventsResult,
} from '../../parser/load-events.js';
import type {
	EventDefinition,
	EventFieldType,
	EventPayloadField,
} from '../../schema/event-definition.schema.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface EventCodegenGeneratorOptions {
	/** Absolute path to the entities directory (used for desugaring entity events: blocks). */
	entitiesDir: string;
	/** Absolute path to the events directory (top-level events/*.yaml files). */
	eventsDir: string;
	/** Absolute path to the generator's output directory. */
	outputDir: string;
	/** If true, compute content but don't write to disk. */
	dryRun?: boolean;
}

export interface EventCodegenFileOutput {
	/** Absolute path. */
	outputPath: string;
	/** File basename (e.g. 'types.ts'). */
	name: string;
	/** Content actually written (or planned in dry-run). */
	content: string;
}

export interface EventCodegenResult {
	outputDir: string;
	/** Number of events actually rendered into the generated files. */
	eventCount: number;
	/** Merged + deduplicated EventDefinitions used to render. */
	events: EventDefinition[];
	/** Issues surfaced during load / merge. */
	issues: AnalysisIssue[];
	/** Whether files were written to disk. */
	written: boolean;
	/** All five file outputs — always populated (content available for dry-run reports). */
	files: EventCodegenFileOutput[];
}

// ---------------------------------------------------------------------------
// Header — mirrors scope-entity-type-generator and barrel-generator.
// ---------------------------------------------------------------------------

const HEADER =
	`// AUTO-GENERATED by @pattern-stack/codegen. Do not edit.\n` +
	`// Run \`codegen entity new --all\` to refresh.\n`;

// ---------------------------------------------------------------------------
// Case helpers — intentionally local to avoid a dependency on
// case-converters.mjs from a TS module (matches barrel-generator.ts convention).
// ---------------------------------------------------------------------------

/** `contact_id` → `contactId`, `a_b_c` → `aBC`. Assumes valid snake_case input. */
export function toCamelCase(input: string): string {
	const parts = input.split('_').filter(Boolean);
	if (parts.length === 0) return input;
	const [first, ...rest] = parts;
	return (
		(first ?? '') +
		rest.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('')
	);
}

/** `contact_created` → `ContactCreated`. */
export function toPascalCase(input: string): string {
	return input
		.split('_')
		.filter(Boolean)
		.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
		.join('');
}

// ---------------------------------------------------------------------------
// TS-type and Zod mapping tables (EventFieldType → TS / Zod)
// ---------------------------------------------------------------------------

const TS_TYPE_BY_FIELD: Record<EventFieldType, string> = {
	uuid: 'string',
	string: 'string',
	number: 'number',
	boolean: 'boolean',
	date: 'Date',
	json: 'Record<string, unknown>',
};

const ZOD_EXPR_BY_FIELD: Record<EventFieldType, string> = {
	uuid: 'z.string().uuid()',
	string: 'z.string()',
	number: 'z.number()',
	boolean: 'z.boolean()',
	date: 'z.coerce.date()',
	json: 'z.record(z.unknown())',
};

function tsTypeForField(field: EventPayloadField): string {
	const base = TS_TYPE_BY_FIELD[field.type];
	return field.nullable ? `${base} | null` : base;
}

function zodExprForField(field: EventPayloadField): string {
	const base = ZOD_EXPR_BY_FIELD[field.type];
	return field.nullable ? `${base}.nullable()` : base;
}

/**
 * `aggregateType` literal for a generated interface.
 *
 * Per ADR-024: aggregate ?? source ?? destination ?? type. The generator
 * computes the same precedence as `TypedEventBus.publish()`'s runtime
 * fallback, so the type-level literal matches the value stamped into
 * `DomainEvent.aggregateType` at publish time.
 */
function aggregateTypeLiteral(ev: EventDefinition): string {
	return ev.aggregate ?? ev.source ?? ev.destination ?? ev.type;
}

// ---------------------------------------------------------------------------
// Event discovery + merge
// ---------------------------------------------------------------------------

/**
 * Walk `entitiesDir`, load each entity, and desugar its `events:` block into
 * `EventDefinition[]`. Entities that fail to load are silently skipped — the
 * entity loader / validator reports those elsewhere in the pipeline, and we
 * don't want a single bad entity to block event generation for the rest.
 */
export function collectEntityEvents(entitiesDir: string): {
	events: EventDefinition[];
	issues: AnalysisIssue[];
} {
	const events: EventDefinition[] = [];
	const issues: AnalysisIssue[] = [];

	if (!fs.existsSync(entitiesDir)) {
		return { events, issues };
	}

	const files = fs
		.readdirSync(entitiesDir)
		.filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
		.map((f) => path.join(entitiesDir, f))
		.sort();

	for (const filePath of files) {
		const result = loadEntityFromYaml(filePath);
		if (!result.success) continue;
		try {
			events.push(...desugarEntityEvents(result.definition));
		} catch (err) {
			issues.push({
				severity: 'error',
				type: 'entity_event_desugar_failed',
				message: err instanceof Error ? err.message : String(err),
				path: filePath,
			});
		}
	}

	return { events, issues };
}

/**
 * Merge top-level events (from `events/*.yaml`) with entity-sugar events.
 *
 * Merge policy: top-level events win on `type` collision. A `warning` issue
 * is emitted per collision so authors can see they're overriding sugar.
 * This is the first concrete implementation of the policy declared in the
 * EVT-3 plan and the EVT-7 spec.
 */
export function mergeEvents(
	topLevel: EventDefinition[],
	entitySugar: EventDefinition[],
): { events: EventDefinition[]; issues: AnalysisIssue[] } {
	const issues: AnalysisIssue[] = [];
	const byType = new Map<string, EventDefinition>();

	// Sugar first — top-level can override.
	for (const ev of entitySugar) {
		byType.set(ev.type, ev);
	}

	for (const ev of topLevel) {
		if (byType.has(ev.type)) {
			issues.push({
				severity: 'warning',
				type: 'event_merge_override',
				message: `event '${ev.type}' is declared both in an entity \`events:\` block and a top-level \`events/${ev.type}.yaml\` — top-level definition wins`,
			});
		}
		byType.set(ev.type, ev);
	}

	const events = Array.from(byType.values()).sort((a, b) =>
		a.type.localeCompare(b.type),
	);

	return { events, issues };
}

// ---------------------------------------------------------------------------
// Content builder: types.ts
// ---------------------------------------------------------------------------

export function buildTypesContent(events: EventDefinition[]): string {
	const sorted = [...events].sort((a, b) => a.type.localeCompare(b.type));

	if (sorted.length === 0) {
		return (
			HEADER +
			'\n' +
			`import type { DomainEvent } from '../event-bus.protocol';\n` +
			'\n' +
			`export type AppDomainEvent = never;\n` +
			'\n' +
			`export type EventTypeName = string;\n` +
			`export type EventOfType<T extends EventTypeName> = never;\n` +
			`export type PayloadOfType<T extends EventTypeName> = never;\n`
		);
	}

	const chunks: string[] = [];
	chunks.push(HEADER);
	chunks.push('');
	chunks.push(`import type { DomainEvent } from '../event-bus.protocol';`);
	chunks.push('');

	for (const ev of sorted) {
		const interfaceName = `${toPascalCase(ev.type)}Event`;
		const aggregateLit = aggregateTypeLiteral(ev);

		if (ev.description) {
			chunks.push(`/** ${ev.description} */`);
		}
		chunks.push(`export interface ${interfaceName} extends DomainEvent {`);
		chunks.push(`\treadonly type: '${ev.type}';`);
		chunks.push(`\treadonly aggregateType: '${aggregateLit}';`);

		const payloadKeys = Object.keys(ev.payload).sort();
		if (payloadKeys.length === 0) {
			chunks.push(`\treadonly payload: Record<string, never>;`);
		} else {
			chunks.push(`\treadonly payload: {`);
			for (const key of payloadKeys) {
				const field = ev.payload[key];
				if (!field) continue;
				if (field.description) {
					chunks.push(`\t\t/** ${field.description} */`);
				}
				chunks.push(`\t\t${toCamelCase(key)}: ${tsTypeForField(field)};`);
			}
			chunks.push(`\t};`);
		}
		chunks.push(`}`);
		chunks.push('');
	}

	// Union + helpers
	const unionMembers = sorted.map((ev) => `${toPascalCase(ev.type)}Event`);
	chunks.push(`export type AppDomainEvent =`);
	chunks.push(`\t| ${unionMembers.join('\n\t| ')};`);
	chunks.push('');
	chunks.push(`export type EventTypeName = AppDomainEvent['type'];`);
	chunks.push(
		`export type EventOfType<T extends EventTypeName> = Extract<AppDomainEvent, { type: T }>;`,
	);
	chunks.push(
		`export type PayloadOfType<T extends EventTypeName> = EventOfType<T>['payload'];`,
	);
	chunks.push('');

	return chunks.join('\n');
}

// ---------------------------------------------------------------------------
// Content builder: schemas.ts
// ---------------------------------------------------------------------------

export function buildSchemasContent(events: EventDefinition[]): string {
	const sorted = [...events].sort((a, b) => a.type.localeCompare(b.type));

	if (sorted.length === 0) {
		return (
			HEADER +
			'\n' +
			`import { z } from 'zod';\n` +
			`import type { EventTypeName } from './types';\n` +
			'\n' +
			`export const eventPayloadSchemas = {} as Record<EventTypeName, z.ZodType>;\n`
		);
	}

	const chunks: string[] = [];
	chunks.push(HEADER);
	chunks.push('');
	chunks.push(`import { z } from 'zod';`);
	chunks.push(`import type { EventTypeName } from './types';`);
	chunks.push('');

	for (const ev of sorted) {
		const schemaConst = `${toCamelCase(ev.type)}PayloadSchema`;
		const payloadKeys = Object.keys(ev.payload).sort();

		if (payloadKeys.length === 0) {
			chunks.push(`export const ${schemaConst} = z.object({}).strict();`);
			chunks.push('');
			continue;
		}

		chunks.push(`export const ${schemaConst} = z.object({`);
		for (const key of payloadKeys) {
			const field = ev.payload[key];
			if (!field) continue;
			chunks.push(`\t${toCamelCase(key)}: ${zodExprForField(field)},`);
		}
		chunks.push(`}).strict();`);
		chunks.push('');
	}

	chunks.push(`export const eventPayloadSchemas = {`);
	for (const ev of sorted) {
		chunks.push(`\t'${ev.type}': ${toCamelCase(ev.type)}PayloadSchema,`);
	}
	chunks.push(`} as const satisfies Record<EventTypeName, z.ZodType>;`);
	chunks.push('');

	return chunks.join('\n');
}

// ---------------------------------------------------------------------------
// Content builder: registry.ts
// ---------------------------------------------------------------------------

const REGISTRY_INTERFACE = [
	'export interface EventMetadata {',
	'\ttype: EventTypeName;',
	"\tdirection: 'inbound' | 'change' | 'outbound';",
	"\tpool: 'events_inbound' | 'events_change' | 'events_outbound';",
	'\taggregate?: string;',
	'\tsource?: string;',
	'\tdestination?: string;',
	'\tversion: number;',
	"\tretry: { attempts: number; backoff: 'linear' | 'exponential' };",
	'}',
].join('\n');

/**
 * The same `getEventMetadata` body is emitted in empty and non-empty cases.
 * Keeping the function uniform lets consumers rely on "throws on unknown type"
 * regardless of whether the registry was populated at codegen time.
 */
const REGISTRY_GETTER = [
	'export function getEventMetadata<T extends EventTypeName>(type: T): EventMetadata {',
	'\tconst meta = eventRegistry[type];',
	'\tif (!meta) {',
	"\t\tthrow new Error(`No registry entry for event type '${String(type)}' — declare events under events/*.yaml and re-run \\`codegen entity new --all\\`.`);",
	'\t}',
	'\treturn meta;',
	'}',
].join('\n');

export function buildRegistryContent(events: EventDefinition[]): string {
	const sorted = [...events].sort((a, b) => a.type.localeCompare(b.type));

	const chunks: string[] = [];
	chunks.push(HEADER);
	chunks.push('');
	chunks.push(`import type { EventTypeName } from './types';`);
	chunks.push('');
	chunks.push(REGISTRY_INTERFACE);
	chunks.push('');

	if (sorted.length === 0) {
		chunks.push(
			`export const eventRegistry = {} as Record<EventTypeName, EventMetadata>;`,
		);
		chunks.push('');
		chunks.push(REGISTRY_GETTER);
		chunks.push('');
		return chunks.join('\n');
	}

	chunks.push(`export const eventRegistry = {`);
	for (const ev of sorted) {
		chunks.push(`\t'${ev.type}': {`);
		chunks.push(`\t\ttype: '${ev.type}',`);
		chunks.push(`\t\tdirection: '${ev.direction}',`);
		chunks.push(`\t\tpool: '${ev.pool}',`);
		if (ev.aggregate !== undefined) {
			chunks.push(`\t\taggregate: '${ev.aggregate}',`);
		}
		if (ev.source !== undefined) {
			chunks.push(`\t\tsource: '${ev.source}',`);
		}
		if (ev.destination !== undefined) {
			chunks.push(`\t\tdestination: '${ev.destination}',`);
		}
		chunks.push(`\t\tversion: ${ev.version},`);
		chunks.push(
			`\t\tretry: { attempts: ${ev.retry.attempts}, backoff: '${ev.retry.backoff}' },`,
		);
		chunks.push(`\t},`);
	}
	chunks.push(
		`} as const satisfies Record<EventTypeName, EventMetadata>;`,
	);
	chunks.push('');
	chunks.push(REGISTRY_GETTER);
	chunks.push('');

	return chunks.join('\n');
}

// ---------------------------------------------------------------------------
// Content builder: bus.ts
// ---------------------------------------------------------------------------

/**
 * Class body is fully static — no YAML-derived content. Kept in a single
 * template string so empty/non-empty cases emit byte-identical output beyond
 * the shared header.
 */
const BUS_BODY = `import { Injectable, Inject } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { EVENT_BUS, EVENTS_MULTI_TENANT } from '../events.tokens';
import { MissingTenantIdError } from '../events-errors';
import type { IEventBus, DrizzleTransaction } from '../event-bus.protocol';
import { eventPayloadSchemas } from './schemas';
import { getEventMetadata } from './registry';
import type { EventTypeName, EventOfType, PayloadOfType } from './types';

/**
 * Typed facade over IEventBus.
 *
 * Stamps \`pool\`, \`direction\`, and \`version\` into \`event.metadata\` from
 * the generated \`eventRegistry\` before delegating to \`IEventBus.publish()\`.
 * Downstream backends (DrizzleEventBus) read those values to populate the
 * explicit \`domain_events\` columns.
 *
 * Validation gating (EVT-Q5): \`CODEGEN_EVENT_VALIDATE\` env flag, default on.
 * Uses \`safeParse\` + \`console.warn\` — never throws, so a bad publish does
 * not crash a hot path.
 *
 * Multi-tenancy (EVT-6): when the EventsModule is configured with
 * \`multiTenant: true\`, every publish must supply \`opts.metadata.tenantId\`
 * — otherwise \`publish()\` throws \`MissingTenantIdError\`. When \`multiTenant\`
 * is \`false\` (default), no tenantId is required. If a tenantId IS supplied,
 * it is preserved on \`event.metadata\` and the Drizzle backend writes it to
 * \`domain_events.tenant_id\` (EVT-4).
 */
@Injectable()
export class TypedEventBus {
\tconstructor(
\t\t@Inject(EVENT_BUS) private readonly bus: IEventBus,
\t\t@Inject(EVENTS_MULTI_TENANT) private readonly multiTenant: boolean,
\t) {}

\tasync publish<T extends EventTypeName>(
\t\ttype: T,
\t\taggregateId: string,
\t\tpayload: PayloadOfType<T>,
\t\topts?: { tx?: DrizzleTransaction; metadata?: Record<string, unknown> },
\t): Promise<void> {
\t\tconst meta = getEventMetadata(type);

\t\tconst flag = process.env['CODEGEN_EVENT_VALIDATE'];
\t\tconst shouldValidate =
\t\t\tflag === undefined ? true : flag !== 'false' && flag !== '0';
\t\tif (shouldValidate) {
\t\t\tconst check = eventPayloadSchemas[type].safeParse(payload);
\t\t\tif (!check.success) {
\t\t\t\tconsole.warn(
\t\t\t\t\t\`[TypedEventBus] payload validation failed for \${String(type)}:\`,
\t\t\t\t\tcheck.error.issues,
\t\t\t\t);
\t\t\t}
\t\t}

\t\tconst tenantId = opts?.metadata?.['tenantId'];
\t\tif (this.multiTenant && (tenantId === undefined || tenantId === null)) {
\t\t\tthrow new MissingTenantIdError(type as string);
\t\t}

\t\tconst aggregateType =
\t\t\tmeta.aggregate ?? meta.source ?? meta.destination ?? (type as string);

\t\tawait this.bus.publish(
\t\t\t{
\t\t\t\tid: randomUUID(),
\t\t\t\ttype,
\t\t\t\taggregateId,
\t\t\t\taggregateType,
\t\t\t\tpayload: payload as Record<string, unknown>,
\t\t\t\toccurredAt: new Date(),
\t\t\t\tmetadata: {
\t\t\t\t\t...(opts?.metadata ?? {}),
\t\t\t\t\tpool: meta.pool,
\t\t\t\t\tdirection: meta.direction,
\t\t\t\t\tversion: meta.version,
\t\t\t\t},
\t\t\t},
\t\t\topts?.tx,
\t\t);
\t}

\tsubscribe<T extends EventTypeName>(
\t\ttype: T,
\t\thandler: (event: EventOfType<T>) => Promise<void>,
\t): () => void {
\t\treturn this.bus.subscribe<EventOfType<T>>(type, handler as never);
\t}
}
`;

export function buildBusContent(_events: EventDefinition[]): string {
	// Body is identical for empty and non-empty projects; the behaviour
	// difference lives in registry.ts (empty throws on any lookup).
	return HEADER + '\n' + BUS_BODY;
}

// ---------------------------------------------------------------------------
// Content builder: index.ts
// ---------------------------------------------------------------------------

export function buildIndexContent(_events: EventDefinition[]): string {
	return (
		HEADER +
		'\n' +
		`export * from './types';\n` +
		`export * from './schemas';\n` +
		`export * from './registry';\n` +
		`export * from './bus';\n`
	);
}

// ---------------------------------------------------------------------------
// Public entrypoint
// ---------------------------------------------------------------------------

const OUTPUT_FILE_NAMES = [
	'types.ts',
	'schemas.ts',
	'registry.ts',
	'bus.ts',
	'index.ts',
] as const;

export async function generateEventCodegen(
	opts: EventCodegenGeneratorOptions,
): Promise<EventCodegenResult> {
	const { entitiesDir, eventsDir, outputDir, dryRun = false } = opts;

	// 1. Gather entity names (for loadEvents cross-validation).
	let entityNames: string[] = [];
	if (fs.existsSync(entitiesDir)) {
		const entityFiles = fs
			.readdirSync(entitiesDir)
			.filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
			.map((f) => path.join(entitiesDir, f))
			.sort();
		for (const f of entityFiles) {
			const result = loadEntityFromYaml(f);
			if (result.success) entityNames.push(result.definition.entity.name);
		}
	}

	// 2. Load top-level events and desugar entity events.
	const topLevelResult: LoadEventsResult = loadEvents(eventsDir, entityNames);
	const { events: entitySugar, issues: sugarIssues } =
		collectEntityEvents(entitiesDir);

	// 3. Merge (top-level wins on collision).
	const { events: merged, issues: mergeIssues } = mergeEvents(
		topLevelResult.events,
		entitySugar,
	);

	const issues: AnalysisIssue[] = [
		// `no_events_dir` / `no_files` warnings from loadEvents are retained —
		// the generator still emits stub files, matching JOB-7's empty case.
		...topLevelResult.issues,
		...sugarIssues,
		...mergeIssues,
	];

	// 4. Build all file contents.
	const builders: Record<
		(typeof OUTPUT_FILE_NAMES)[number],
		(events: EventDefinition[]) => string
	> = {
		'types.ts': buildTypesContent,
		'schemas.ts': buildSchemasContent,
		'registry.ts': buildRegistryContent,
		'bus.ts': buildBusContent,
		'index.ts': buildIndexContent,
	};

	const files: EventCodegenFileOutput[] = OUTPUT_FILE_NAMES.map((name) => ({
		name,
		outputPath: path.join(outputDir, name),
		content: builders[name](merged),
	}));

	// 5. Write (or not) — fail-loud on `severity: 'error'` issues.
	const hasError = issues.some((i) => i.severity === 'error');
	let written = false;
	if (!dryRun && !hasError) {
		fs.mkdirSync(outputDir, { recursive: true });
		for (const file of files) {
			fs.writeFileSync(file.outputPath, file.content);
		}
		written = true;
	}

	return {
		outputDir,
		eventCount: merged.length,
		events: merged,
		issues,
		written,
		files,
	};
}
