/**
 * Orchestration generator (ADR-032 Phase 3-2 + 3-3).
 *
 * Pure-TS template-literal emitter — mirrors `event-codegen-generator.ts`
 * and `bridge-registry-generator.ts`. NO Hygen, NO EJS (operator gate
 * O-2). Pure content-builders are unit-testable in isolation; the single
 * orchestrating entrypoint handles disk I/O with `dryRun` semantics.
 *
 * Emits one directory per `OrchestrationPatternDefinition` under
 * `${paths.orchestration_src}/${slug}/`:
 *
 *   tokens.ts              — unique Symbol() per registry, typed map aliases
 *   registry.providers.ts  — buildXRegistryProviders() factory, frozen Map
 *   dispatcher.ts          — overload signatures + runtime select() impl
 *   module.ts              — DynamicModule with forRoot({ overrides, ... })
 *   index.ts               — barrel re-exports
 *
 * Co-keyed siblings (ADR-032 Phase 3-2 §1.1, O-1) are addressed by an
 * EXPLICIT `name:` field per sibling. The emitter uppercases that name
 * for token suffix and PascalCases it for method/option-key suffix. NO
 * auto-stripping of "I" prefix or "Strategy/Port/Adapter/Provider"
 * suffixes — authors pick the identifier that reads right.
 *
 * Risk flags (ADR-032 Phase 3-2 §6):
 *   R-1 — TS overload ordering: emit specific overloads first, then the
 *         widening signature, then the implementation signature LAST.
 *   R-3 — `Partial<Record<K, V>>` requires a literal-union `K`. Reject
 *         `keyType` of `string | number | any | unknown | symbol` at
 *         emission time.
 *   R-4 — Constructor-injected registry fields are `protected readonly`
 *         (NOT `private`) so subclasses can reach them per Decision 5.
 */

import fs from 'node:fs';
import path from 'node:path';

import type { OrchestrationPatternDefinition, OrchestrationRegistrySpec } from '../../patterns/pattern-definition.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface OrchestrationGeneratorOptions {
	/** Patterns to emit (typically `getAllOrchestrationPatterns()`). */
	patterns: ReadonlyArray<OrchestrationPatternDefinition>;
	/**
	 * Absolute path to the orchestration root (resolves to e.g.
	 * `${cwd}/${paths.orchestration_src}`). Each pattern emits into a
	 * `${slug}/` subdirectory.
	 */
	outputRoot: string;
	/** If true, compute content but don't write to disk. */
	dryRun?: boolean;
}

export interface OrchestrationFileOutput {
	outputPath: string;
	relativePath: string;
	name: string;
	content: string;
}

export interface OrchestrationPatternResult {
	patternName: string;
	slug: string;
	outputDir: string;
	files: OrchestrationFileOutput[];
}

export interface OrchestrationGeneratorResult {
	outputRoot: string;
	patterns: OrchestrationPatternResult[];
	files: OrchestrationFileOutput[];
	written: boolean;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

export class OrchestrationEmissionError extends Error {
	override readonly name = 'OrchestrationEmissionError';
	constructor(
		public readonly issueType: string,
		public readonly patternName: string,
		message: string,
	) {
		super(`[${issueType}] ${patternName}: ${message}`);
	}
}

// ---------------------------------------------------------------------------
// Header
// ---------------------------------------------------------------------------

const HEADER =
	`// AUTO-GENERATED by @pattern-stack/codegen. Do not edit.\n` +
	`// See ADR-032 — Orchestration Patterns.\n`;

// ---------------------------------------------------------------------------
// Case helpers — local to avoid pulling .mjs into a TS module (mirrors the
// barrel-generator and event-codegen-generator convention).
// ---------------------------------------------------------------------------

function splitWords(str: string): string[] {
	return str
		.replace(/([a-z])([A-Z])/g, '$1 $2')
		.replace(/[_-]/g, ' ')
		.split(/\s+/)
		.filter((w) => w.length > 0)
		.map((w) => w.toLowerCase());
}

export function toKebabCase(str: string): string {
	return splitWords(str).join('-');
}

export function toPascalCase(str: string): string {
	return splitWords(str)
		.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
		.join('');
}

export function toCamelCase(str: string): string {
	const words = splitWords(str);
	if (words.length === 0) return '';
	const [first, ...rest] = words;
	return (
		(first ?? '') + rest.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('')
	);
}

export function toScreamingSnake(str: string): string {
	return splitWords(str).join('_').toUpperCase();
}

// ---------------------------------------------------------------------------
// Validation — emission-time guards (R-3 + O-3 + O-8)
// ---------------------------------------------------------------------------

const FORBIDDEN_KEY_TYPES = new Set([
	'string',
	'number',
	'symbol',
	'any',
	'unknown',
]);

function assertEmittable(pattern: OrchestrationPatternDefinition): void {
	const allRegistries: OrchestrationRegistrySpec[] = [
		pattern.registry,
		...(pattern.coKeyedRegistries ?? []),
	];

	// Co-keyed siblings MUST carry an explicit `name` (O-1).
	for (const sibling of pattern.coKeyedRegistries ?? []) {
		if (typeof sibling.name !== 'string' || sibling.name.length === 0) {
			throw new OrchestrationEmissionError(
				'pattern_cokeyed_missing_name',
				pattern.name,
				`Co-keyed registry (valueType '${sibling.valueType}') is missing the ` +
					`required 'name' field. Each co-keyed sibling must declare an ` +
					`explicit name; the emitter uppercases it for the token suffix and ` +
					`PascalCases it for the dispatcher method (e.g. name: 'auth' ⇒ ` +
					`'\${PATTERN_CONST}_AUTH_REGISTRY' + 'selectAuth(...)'). ADR-032 O-1.`,
			);
		}
	}

	for (const reg of allRegistries) {
		// R-3: Partial<Record<K, V>> requires a literal-union K. Reject the
		// primitive-type keyTypes that would silently accept any string at
		// runtime + collapse the per-key narrowing in the dispatcher.
		if (FORBIDDEN_KEY_TYPES.has(reg.keyType)) {
			throw new OrchestrationEmissionError(
				'pattern_keytype_unresolved',
				pattern.name,
				`registry keyType '${reg.keyType}' is a primitive — Partial<Record<K, V>> ` +
					`requires a literal-union K, and per-overload narrowing requires a ` +
					`closed enum/union. Use a string-literal union or a TypeScript enum.`,
			);
		}

		// O-3 / O-8: import-path fields must be present at emission time.
		if (typeof reg.keyTypeImport !== 'string' || reg.keyTypeImport.length === 0) {
			throw new OrchestrationEmissionError(
				'pattern_missing_import_path',
				pattern.name,
				`registry (keyType '${reg.keyType}') is missing 'keyTypeImport'. ` +
					`Phase 3-2 emission requires every keyType to carry a module specifier.`,
			);
		}
		if (typeof reg.valueTypeImport !== 'string' || reg.valueTypeImport.length === 0) {
			throw new OrchestrationEmissionError(
				'pattern_missing_import_path',
				pattern.name,
				`registry (valueType '${reg.valueType}') is missing 'valueTypeImport'.`,
			);
		}
		for (const e of reg.entries) {
			if (typeof e.providerImport !== 'string' || e.providerImport.length === 0) {
				throw new OrchestrationEmissionError(
					'pattern_missing_import_path',
					pattern.name,
					`entry '${e.key}' provider '${e.provider}' is missing 'providerImport'.`,
				);
			}
		}
	}
}

// ---------------------------------------------------------------------------
// Identifier helpers
// ---------------------------------------------------------------------------

interface RegistryNames {
	/** Token symbol identifier (e.g. `CRM_PORTS_REGISTRY`, `CRM_PORTS_AUTH_REGISTRY`). */
	tokenConst: string;
	/** Map type alias (e.g. `CrmPortsRegistryMap`, `CrmPortsAuthRegistryMap`). */
	mapType: string;
	/** Dispatcher method name (e.g. `select`, `selectAuth`). */
	method: string;
	/** ForRoot options field (e.g. `overrides`, `authOverrides`). */
	overrideField: string;
	/** Builder factory function name (`buildCrmPortsRegistryProviders`). */
	builderFn: string;
}

function patternNames(pattern: OrchestrationPatternDefinition) {
	const slug = toKebabCase(pattern.name);
	const pascal = toPascalCase(pattern.name);
	const screaming = toScreamingSnake(pattern.name);
	return { slug, pascal, screaming };
}

function registryNames(
	pattern: OrchestrationPatternDefinition,
	reg: OrchestrationRegistrySpec,
	isPrimary: boolean,
): RegistryNames {
	const { pascal, screaming } = patternNames(pattern);
	if (isPrimary) {
		return {
			tokenConst: `${screaming}_REGISTRY`,
			mapType: `${pascal}RegistryMap`,
			method: 'select',
			overrideField: 'overrides',
			builderFn: `build${pascal}RegistryProviders`,
		};
	}
	const namePascal = toPascalCase(reg.name!);
	const nameScreaming = toScreamingSnake(reg.name!);
	const nameCamel = toCamelCase(reg.name!);
	return {
		tokenConst: `${screaming}_${nameScreaming}_REGISTRY`,
		mapType: `${pascal}${namePascal}RegistryMap`,
		method: `select${namePascal}`,
		overrideField: `${nameCamel}Overrides`,
		builderFn: `build${pascal}RegistryProviders`,
	};
}

function dispatcherClassName(pattern: OrchestrationPatternDefinition): string {
	return pattern.dispatcher?.className ?? `${toPascalCase(pattern.name)}Dispatcher`;
}

function moduleClassName(pattern: OrchestrationPatternDefinition): string {
	return `${toPascalCase(pattern.name)}OrchestrationModule`;
}

function forRootOptionsTypeName(pattern: OrchestrationPatternDefinition): string {
	return `${toPascalCase(pattern.name)}ForRootOptions`;
}

// ---------------------------------------------------------------------------
// Import-grouping helpers (deterministic ordering)
// ---------------------------------------------------------------------------

interface TypeImport {
	specifier: string;
	name: string;
}

/** Group `import type { Name } from 'spec'` statements by specifier. */
function emitTypeImports(imports: TypeImport[]): string[] {
	const grouped = new Map<string, Set<string>>();
	for (const i of imports) {
		const set = grouped.get(i.specifier) ?? new Set();
		set.add(i.name);
		grouped.set(i.specifier, set);
	}
	const out: string[] = [];
	for (const specifier of [...grouped.keys()].sort()) {
		const names = [...grouped.get(specifier)!].sort();
		out.push(`import type { ${names.join(', ')} } from '${specifier}';`);
	}
	return out;
}

interface ValueImport {
	specifier: string;
	name: string;
}

/** Group `import { Name } from 'spec'` statements by specifier. */
function emitValueImports(imports: ValueImport[]): string[] {
	const grouped = new Map<string, Set<string>>();
	for (const i of imports) {
		const set = grouped.get(i.specifier) ?? new Set();
		set.add(i.name);
		grouped.set(i.specifier, set);
	}
	const out: string[] = [];
	for (const specifier of [...grouped.keys()].sort()) {
		const names = [...grouped.get(specifier)!].sort();
		out.push(`import { ${names.join(', ')} } from '${specifier}';`);
	}
	return out;
}

function allRegistries(
	pattern: OrchestrationPatternDefinition,
): Array<{ reg: OrchestrationRegistrySpec; names: RegistryNames; isPrimary: boolean }> {
	const list: Array<{ reg: OrchestrationRegistrySpec; names: RegistryNames; isPrimary: boolean }> = [];
	list.push({
		reg: pattern.registry,
		names: registryNames(pattern, pattern.registry, true),
		isPrimary: true,
	});
	for (const sibling of pattern.coKeyedRegistries ?? []) {
		list.push({
			reg: sibling,
			names: registryNames(pattern, sibling, false),
			isPrimary: false,
		});
	}
	return list;
}

// ---------------------------------------------------------------------------
// Content builders (pure functions — unit-testable without disk)
// ---------------------------------------------------------------------------

export function buildTokensTs(pattern: OrchestrationPatternDefinition): string {
	const registries = allRegistries(pattern);

	const typeImports: TypeImport[] = [];
	for (const { reg } of registries) {
		typeImports.push({ specifier: reg.keyTypeImport!, name: reg.keyType });
		typeImports.push({ specifier: reg.valueTypeImport!, name: reg.valueType });
	}

	const lines: string[] = [];
	lines.push(HEADER.trimEnd());
	lines.push('');
	for (const i of emitTypeImports(typeImports)) lines.push(i);
	lines.push('');
	for (const { names } of registries) {
		lines.push(`export const ${names.tokenConst} = Symbol('${names.tokenConst}');`);
	}
	lines.push('');
	for (const { reg, names } of registries) {
		lines.push(
			`export type ${names.mapType} = Map<${reg.keyType}, ${reg.valueType}>;`,
		);
	}
	lines.push('');
	return lines.join('\n');
}

export function buildProvidersTs(pattern: OrchestrationPatternDefinition): string {
	const registries = allRegistries(pattern);

	// Provider class imports (concrete classes used by useFactory).
	const providerImports: ValueImport[] = [];
	for (const { reg } of registries) {
		for (const e of reg.entries) {
			providerImports.push({ specifier: e.providerImport!, name: e.provider });
		}
	}

	// Tokens + map types come from local ./tokens.js
	const tokenValueImports = registries.map(({ names }) => names.tokenConst);
	const mapTypeImports = registries.map(({ names }) => names.mapType);

	// Key-type + value-type imports — both used by `as` casts inside the
	// useFactory body and the new Map<K, V> annotation.
	const typeImports: TypeImport[] = [];
	for (const { reg } of registries) {
		typeImports.push({ specifier: reg.keyTypeImport!, name: reg.keyType });
		typeImports.push({ specifier: reg.valueTypeImport!, name: reg.valueType });
	}

	const optsType = forRootOptionsTypeName(pattern);

	const lines: string[] = [];
	lines.push(HEADER.trimEnd());
	lines.push('');
	lines.push(`import type { Provider } from '@nestjs/common';`);
	for (const i of emitTypeImports(typeImports)) lines.push(i);
	for (const i of emitValueImports(providerImports)) lines.push(i);
	// Local ./tokens import — combine values + type-only into one statement
	// in alphabetical order across both kinds. Use the standard split form:
	// `import { CONST, type MapType } from './tokens.js'`.
	const tokenLine = [
		...tokenValueImports.sort(),
		...mapTypeImports.sort().map((m) => `type ${m}`),
	].join(', ');
	lines.push(`import { ${tokenLine} } from './tokens.js';`);
	lines.push(`import type { ${optsType} } from './module.js';`);
	lines.push('');

	const { pascal } = patternNames(pattern);
	lines.push(
		`export function build${pascal}RegistryProviders(opts?: ${optsType}): Provider[] {`,
	);
	lines.push('\treturn [');
	for (const { reg, names } of registries) {
		const factoryArgs = reg.entries
			.map((e, i) => `${camelArg(e.provider, i)}: ${e.provider}`)
			.join(', ');
		lines.push('\t\t{');
		lines.push(`\t\t\tprovide: ${names.tokenConst},`);
		lines.push(`\t\t\tuseFactory: (${factoryArgs}) => {`);
		lines.push(`\t\t\t\tconst base: ${names.mapType} = new Map<${reg.keyType}, ${reg.valueType}>([`);
		for (const [i, e] of reg.entries.entries()) {
			lines.push(
				`\t\t\t\t\t['${e.key}' as ${reg.keyType}, ${camelArg(e.provider, i)}],`,
			);
		}
		lines.push('\t\t\t\t]);');
		lines.push(`\t\t\t\tif (opts?.${names.overrideField}) {`);
		lines.push(`\t\t\t\t\tfor (const [k, v] of Object.entries(opts.${names.overrideField})) {`);
		lines.push(`\t\t\t\t\t\tif (v !== undefined) base.set(k as ${reg.keyType}, v as ${reg.valueType});`);
		lines.push('\t\t\t\t\t}');
		lines.push('\t\t\t\t}');
		lines.push(`\t\t\t\treturn base as ${names.mapType};`);
		lines.push('\t\t\t},');
		const injectList = reg.entries.map((e) => e.provider).join(', ');
		lines.push(`\t\t\tinject: [${injectList}],`);
		lines.push('\t\t},');
	}
	lines.push('\t];');
	lines.push('}');
	lines.push('');
	return lines.join('\n');
}

/** Stable per-entry factory argument name. */
function camelArg(provider: string, index: number): string {
	const camel = provider.charAt(0).toLowerCase() + provider.slice(1);
	// Disambiguate if two entries (across registries) share a class name.
	return `${camel}_${index}`;
}

export function buildDispatcherTs(pattern: OrchestrationPatternDefinition): string {
	const registries = allRegistries(pattern);
	const className = dispatcherClassName(pattern);
	const errorClass = `${className}Error`;

	// Imports
	const typeImports: TypeImport[] = [];
	for (const { reg } of registries) {
		typeImports.push({ specifier: reg.keyTypeImport!, name: reg.keyType });
		typeImports.push({ specifier: reg.valueTypeImport!, name: reg.valueType });
	}
	const providerImports: ValueImport[] = [];
	for (const { reg } of registries) {
		for (const e of reg.entries) {
			providerImports.push({ specifier: e.providerImport!, name: e.provider });
		}
	}
	const tokenValues = registries.map(({ names }) => names.tokenConst);
	const mapTypes = registries.map(({ names }) => names.mapType);

	const lines: string[] = [];
	lines.push(HEADER.trimEnd());
	lines.push('');
	lines.push(`import { Inject, Injectable } from '@nestjs/common';`);
	for (const i of emitTypeImports(typeImports)) lines.push(i);
	for (const i of emitValueImports(providerImports)) lines.push(i);
	const tokenLine = [
		...tokenValues.sort(),
		...mapTypes.sort().map((m) => `type ${m}`),
	].join(', ');
	lines.push(`import { ${tokenLine} } from './tokens.js';`);
	lines.push('');
	lines.push(`export class ${errorClass} extends Error {}`);
	lines.push('');
	lines.push('@Injectable()');
	lines.push(`export class ${className} {`);
	// Constructor — protected readonly registry fields (R-4)
	lines.push('\tconstructor(');
	for (const { names } of registries) {
		const fieldName = names.method === 'select' ? 'registry' : `${camelFromMethod(names.method)}Registry`;
		lines.push(
			`\t\t@Inject(${names.tokenConst}) protected readonly ${fieldName}: ${names.mapType},`,
		);
	}
	lines.push('\t) {}');
	lines.push('');

	// Per-registry select method (R-1: specific overloads first, then
	// widening signature, then implementation signature, then body).
	for (const { reg, names } of registries) {
		const fieldName =
			names.method === 'select' ? 'registry' : `${camelFromMethod(names.method)}Registry`;
		// Specific overloads
		for (const e of reg.entries) {
			lines.push(`\t${names.method}(key: '${e.key}'): ${e.provider};`);
		}
		// Widening overload
		lines.push(`\t${names.method}(key: ${reg.keyType}): ${reg.valueType};`);
		// Implementation signature
		lines.push(`\t${names.method}(key: ${reg.keyType}): ${reg.valueType} {`);
		lines.push(`\t\tconst entry = this.${fieldName}.get(key);`);
		lines.push(
			`\t\tif (!entry) throw new ${errorClass}(\`Unknown ${reg.keyType}: \${String(key)}\`);`,
		);
		lines.push(`\t\treturn entry;`);
		lines.push('\t}');
		lines.push('');
	}

	// Decision 5 documentation comment for assemblySlot.
	if (pattern.dispatcher?.assemblySlot) {
		lines.push(
			`\t// ADR-032 Decision 5 — \`assemblySlot: '${pattern.dispatcher.assemblySlot}'\` is a`,
		);
		lines.push(
			`\t// subclass contract, not emitted here. Consumers subclass and add the`,
		);
		lines.push(
			`\t// \`${pattern.dispatcher.assemblySlot}(...)\` method themselves.`,
		);
	}
	lines.push('}');
	lines.push('');
	return lines.join('\n');
}

function camelFromMethod(method: string): string {
	// `selectAuth` -> `auth`
	if (method.startsWith('select') && method.length > 'select'.length) {
		const tail = method.slice('select'.length);
		return tail.charAt(0).toLowerCase() + tail.slice(1);
	}
	return method;
}

export function buildModuleTs(pattern: OrchestrationPatternDefinition): string {
	const registries = allRegistries(pattern);
	const className = dispatcherClassName(pattern);
	const moduleName = moduleClassName(pattern);
	const optsType = forRootOptionsTypeName(pattern);
	const { pascal } = patternNames(pattern);

	const typeImports: TypeImport[] = [];
	for (const { reg } of registries) {
		typeImports.push({ specifier: reg.keyTypeImport!, name: reg.keyType });
		typeImports.push({ specifier: reg.valueTypeImport!, name: reg.valueType });
	}
	const tokenValues = registries.map(({ names }) => names.tokenConst);

	const lines: string[] = [];
	lines.push(HEADER.trimEnd());
	lines.push('');
	lines.push(`import { type DynamicModule, Module } from '@nestjs/common';`);
	for (const i of emitTypeImports(typeImports)) lines.push(i);
	lines.push(`import { ${className} } from './dispatcher.js';`);
	lines.push(`import { build${pascal}RegistryProviders } from './registry.providers.js';`);
	lines.push(`import { ${tokenValues.sort().join(', ')} } from './tokens.js';`);
	lines.push('');

	lines.push(`export interface ${optsType} {`);
	for (const { reg, names } of registries) {
		lines.push(
			`\t${names.overrideField}?: Partial<Record<${reg.keyType}, ${reg.valueType}>>;`,
		);
	}
	lines.push('}');
	lines.push('');
	lines.push('@Module({})');
	lines.push(`export class ${moduleName} {`);
	lines.push(`\tstatic forRoot(opts?: ${optsType}): DynamicModule {`);
	lines.push('\t\treturn {');
	lines.push(`\t\t\tmodule: ${moduleName},`);
	lines.push(
		`\t\t\tproviders: [...build${pascal}RegistryProviders(opts), ${className}],`,
	);
	const exportItems = [...tokenValues.sort(), className];
	lines.push(`\t\t\texports: [${exportItems.join(', ')}],`);
	lines.push('\t\t};');
	lines.push('\t}');
	lines.push('}');
	lines.push('');
	return lines.join('\n');
}

export function buildIndexTs(pattern: OrchestrationPatternDefinition): string {
	const lines: string[] = [];
	lines.push(HEADER.trimEnd());
	lines.push('');
	lines.push(`export * from './tokens.js';`);
	lines.push(`export * from './dispatcher.js';`);
	lines.push(`export * from './module.js';`);
	lines.push(`export * from './registry.providers.js';`);
	lines.push('');
	return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Top-level barrel (O-7) — `${orchestration_src}/index.ts` re-exports every
// pattern's per-pattern barrel.
// ---------------------------------------------------------------------------

export function buildRootBarrelTs(
	patterns: ReadonlyArray<OrchestrationPatternDefinition>,
): string {
	const lines: string[] = [];
	lines.push(HEADER.trimEnd());
	lines.push('');
	if (patterns.length === 0) {
		lines.push('// No orchestration patterns registered.');
		lines.push('export {};');
		lines.push('');
		return lines.join('\n');
	}
	const slugs = patterns.map((p) => toKebabCase(p.name)).sort();
	for (const slug of slugs) {
		lines.push(`export * from './${slug}/index.js';`);
	}
	lines.push('');
	return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Per-pattern + multi-pattern emission
// ---------------------------------------------------------------------------

export function buildPatternFiles(
	pattern: OrchestrationPatternDefinition,
	outputRoot: string,
): OrchestrationPatternResult {
	assertEmittable(pattern);
	const slug = toKebabCase(pattern.name);
	const outputDir = path.join(outputRoot, slug);

	const make = (name: string, content: string): OrchestrationFileOutput => ({
		name,
		outputPath: path.join(outputDir, name),
		relativePath: path.join(slug, name),
		content,
	});

	const files: OrchestrationFileOutput[] = [
		make('tokens.ts', buildTokensTs(pattern)),
		make('registry.providers.ts', buildProvidersTs(pattern)),
		make('dispatcher.ts', buildDispatcherTs(pattern)),
		make('module.ts', buildModuleTs(pattern)),
		make('index.ts', buildIndexTs(pattern)),
	];

	return {
		patternName: pattern.name,
		slug,
		outputDir,
		files,
	};
}

export function generateOrchestrationModules(
	opts: OrchestrationGeneratorOptions,
): OrchestrationGeneratorResult {
	const { patterns, outputRoot, dryRun = false } = opts;
	const perPattern: OrchestrationPatternResult[] = [];
	const allFiles: OrchestrationFileOutput[] = [];

	for (const pattern of patterns) {
		const result = buildPatternFiles(pattern, outputRoot);
		perPattern.push(result);
		allFiles.push(...result.files);
	}

	// Top-level barrel (O-7).
	const rootBarrel: OrchestrationFileOutput = {
		name: 'index.ts',
		outputPath: path.join(outputRoot, 'index.ts'),
		relativePath: 'index.ts',
		content: buildRootBarrelTs(patterns),
	};
	allFiles.push(rootBarrel);

	let written = false;
	// When there are zero orchestration patterns, do NOT create the
	// `${orchestration_src}/` directory — consumers without patterns
	// shouldn't see a stray empty folder + index.ts after `entity new`.
	// The dry-run plan still includes the barrel for visibility.
	if (!dryRun && patterns.length > 0) {
		fs.mkdirSync(outputRoot, { recursive: true });
		for (const r of perPattern) {
			fs.mkdirSync(r.outputDir, { recursive: true });
			for (const f of r.files) {
				fs.writeFileSync(f.outputPath, f.content);
			}
		}
		fs.writeFileSync(rootBarrel.outputPath, rootBarrel.content);
		written = true;
	}

	return {
		outputRoot,
		patterns: perPattern,
		files: allFiles,
		written,
	};
}
