/**
 * Scope-entity-type generator — writes a codegen-owned TypeScript union and
 * Zod enum from the set of all entities marked `scopeable: true` in their YAML.
 *
 * Output: runtime/subsystems/jobs/generated/scope-entity-type.ts
 *
 * Consumer usage:
 *   import type { ScopeEntityType } from '../generated/scope-entity-type';
 *   @JobHandler<OnboardingInput>('onboarding', {
 *     scope: { entity: 'account' satisfies ScopeEntityType, from: (i) => i.accountId },
 *   })
 *
 * Pattern mirrors barrel-generator.ts: HEADER constant, mkdirSync({recursive:true}),
 * fs.writeFileSync, dry-run written:false semantics, pure content-builder.
 *
 * See JOB-7 spec and ADR-022.
 */

import fs from 'node:fs';
import path from 'node:path';

import { loadEntityFromYaml } from '../../utils/yaml-loader.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ScopeEntityTypeGeneratorOptions {
	/** Absolute path to the entities directory. */
	entitiesDir: string;
	/** Absolute path of the output file. */
	outputPath: string;
	/** If true, compute content but don't write to disk. */
	dryRun?: boolean;
}

export interface ScopeEntityTypeResult {
	outputPath: string;
	/** Alphabetically sorted list of scopeable entity names. */
	scopeableNames: string[];
	/** True when the file was actually written to disk. */
	written: boolean;
	/** Generated file content — always populated (useful for dry-run reports). */
	content: string;
}

// ---------------------------------------------------------------------------
// Header (matches barrel-generator.ts convention)
// ---------------------------------------------------------------------------

const HEADER =
	`// AUTO-GENERATED by @pattern-stack/codegen. Do not edit.\n` +
	`// Run \`codegen entity new --all\` to refresh.\n`;

// ---------------------------------------------------------------------------
// Entity discovery
// ---------------------------------------------------------------------------

/**
 * Walk `entitiesDir`, load each YAML, and return the names of all entities
 * with `scopeable: true`, sorted alphabetically.
 */
export function collectScopeableNames(entitiesDir: string): string[] {
	if (!fs.existsSync(entitiesDir)) return [];

	const files = fs
		.readdirSync(entitiesDir)
		.filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
		.map((f) => path.join(entitiesDir, f))
		.sort();

	const names: string[] = [];
	for (const file of files) {
		const result = loadEntityFromYaml(file);
		if (!result.success) continue;
		if (result.definition.entity.scopeable === true) {
			names.push(result.definition.entity.name);
		}
	}

	// Alphabetical sort — deterministic regardless of directory enumeration order.
	names.sort((a, b) => a.localeCompare(b));
	return names;
}

// ---------------------------------------------------------------------------
// Content builder (pure — trivially unit-testable)
// ---------------------------------------------------------------------------

/**
 * Build the content of scope-entity-type.ts.
 *
 * Empty case: `ScopeEntityType = never`, no Zod import.
 * Non-empty case: typed union + `SCOPE_ENTITY_TYPES` tuple + Zod enum.
 */
export function buildScopeEntityTypeContent(names: string[]): string {
	if (names.length === 0) {
		return (
			HEADER +
			'\n' +
			'export type ScopeEntityType = never;\n' +
			'\n' +
			'export const SCOPE_ENTITY_TYPES = [] as const;\n'
		);
	}

	const quoted = names.map((n) => `'${n}'`);
	const unionLiteral = quoted.join(' | ');
	const tupleLiteral = quoted.join(', ');

	return (
		HEADER +
		'\n' +
		`import { z } from 'zod';\n` +
		'\n' +
		`export type ScopeEntityType = ${unionLiteral};\n` +
		'\n' +
		`export const SCOPE_ENTITY_TYPES = [${tupleLiteral}] as const;\n` +
		'\n' +
		`export const scopeEntityTypeSchema = z.enum([${tupleLiteral}]);\n`
	);
}

// ---------------------------------------------------------------------------
// Public entrypoint
// ---------------------------------------------------------------------------

export async function generateScopeEntityType(
	opts: ScopeEntityTypeGeneratorOptions,
): Promise<ScopeEntityTypeResult> {
	const { entitiesDir, outputPath, dryRun = false } = opts;

	const scopeableNames = collectScopeableNames(entitiesDir);
	const content = buildScopeEntityTypeContent(scopeableNames);

	let written = false;
	if (!dryRun) {
		fs.mkdirSync(path.dirname(outputPath), { recursive: true });
		fs.writeFileSync(outputPath, content);
		written = true;
	}

	return { outputPath, scopeableNames, written, content };
}
