/**
 * Subsystem schema barrel generator — writes `<generated>/subsystems-schema.ts`,
 * a value re-export of every installed subsystem's Drizzle tables AND pgEnums so
 * drizzle-kit discovers them with zero consumer hand-editing.
 *
 * Background (the "#9 footgun"): a subsystem's tables (`domain_events`, `job` /
 * `job_run` / `job_step`, `bridge_delivery`, `integration_*`) and its pgEnums
 * (jobs' 8, bridge's 1, integration's 5; events has none — its enum columns are
 * text-enums) are declared in the subsystem runtime, NOT in the consumer's
 * hand-authored `src/schema.ts`. drizzle-kit only emits `CREATE TABLE` / `CREATE
 * TYPE` for schema objects it can reach from its `schema` entrypoint. Before
 * this generator the consumer had to hand-re-export each table + enum or the
 * migration silently skipped them.
 *
 * The consumer folds this barrel into their drizzle-kit schema entrypoint once:
 *
 *   // src/schema.ts
 *   export * from './generated/schema';            // entity tables
 *   export * from './generated/subsystems-schema'; // subsystem tables + enums
 *
 * Mode-aware (ADR-037):
 *   - `package`  → re-exports from `@pattern-stack/codegen/runtime/subsystems/
 *     <name>/index` (events also resolves there; the single `/subsystems`
 *     barrel re-exports the same symbols but the per-subsystem index is the
 *     uniform choice for schema objects).
 *   - `vendored` → re-exports from `<subsystemsRel>/<name>` (the consumer's
 *     vendored per-subsystem barrel).
 *
 * Pattern mirrors barrel-generator.ts / subsystem-barrel-generator.ts: HEADER
 * constant, pure content-builder, mkdirSync({recursive:true}) + writeFileSync
 * with dry-run `written:false` semantics.
 */

import fs from 'node:fs';
import path from 'node:path';

import type { Context } from './context.js';
import { resolveGeneratedDir } from './barrel-generator.js';
import {
	configuredInstalledSubsystems,
	detectInstalledSubsystems,
	type InstalledSubsystem,
	type SubsystemName,
} from './subsystem-detect.js';
import { resolveSubsystemsRoot } from './subsystems-path.js';
import { resolveRuntimeMode, type RuntimeMode } from './runtime-import.js';

const PACKAGE = '@pattern-stack/codegen';

// ---------------------------------------------------------------------------
// Per-subsystem schema-symbol manifest
// ---------------------------------------------------------------------------

/**
 * The exported Drizzle SCHEMA value symbols (tables + pgEnums) per subsystem,
 * exactly as re-exported from each subsystem's public barrel. Confirmed against
 * `runtime/subsystems/{events,jobs,bridge,integration}/*.schema.ts` +
 * their `index.ts` barrels:
 *
 *   - events:      `domainEvents` table only — its status/direction/pool/tier
 *                  columns are TEXT-enums (no `pgEnum`), so NO `CREATE TYPE`.
 *   - jobs:        `job` / `job_run` / `job_step` tables + 8 pgEnums.
 *   - bridge:      `bridge_delivery` table + 1 pgEnum.
 *   - integration: `integration_subscriptions` / `integration_runs` /
 *                  `integration_run_items` tables + 5 pgEnums.
 *
 * `cache` / `storage` / `auth` etc. are intentionally absent — only the
 * subsystems whose tables drizzle-kit must create are listed. (auth's
 * `auth_oauth_state` lands via its own Hygen schema template, not here.)
 */
const SCHEMA_SYMBOLS: Partial<Record<SubsystemName, string[]>> = {
	events: ['domainEvents'],
	jobs: [
		'jobs',
		'jobRuns',
		'jobSteps',
		'jobRunStatusEnum',
		'jobStepKindEnum',
		'jobStepStatusEnum',
		'collisionModeEnum',
		'replayFromEnum',
		'parentClosePolicyEnum',
		'waitKindEnum',
		'triggerSourceEnum',
	],
	bridge: ['bridgeDelivery', 'bridgeDeliveryStatusEnum'],
	integration: [
		'integrationSubscriptions',
		'integrationRuns',
		'integrationRunItems',
		'integrationRunDirectionEnum',
		'integrationRunActionEnum',
		'integrationRunStatusEnum',
		'integrationRunItemOperationEnum',
		'integrationRunItemStatusEnum',
	],
};

/** Subsystems that contribute schema, in a deterministic emit order. */
const SCHEMA_ORDER: SubsystemName[] = ['events', 'jobs', 'bridge', 'integration'];

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SubsystemSchemaBarrelOptions {
	ctx: Context;
	/** Defaults to `resolveGeneratedDir(ctx)`. */
	generatedDir?: string;
	dryRun?: boolean;
}

export interface SubsystemSchemaBarrelResult {
	/** Absolute path to the written file (or where it would be written). */
	schemaBarrel: string;
	/** Subsystem names whose schema symbols were emitted. */
	emitted: SubsystemName[];
	content: string;
	written: boolean;
}

const HEADER = `// AUTO-GENERATED by @pattern-stack/codegen. Do not edit.
// Subsystem Drizzle schema barrel — re-exports the tables + pgEnums of every
// installed subsystem so drizzle-kit emits their CREATE TABLE / CREATE TYPE.
//
// Fold into your drizzle-kit schema entrypoint once, alongside the entity
// schema barrel:
//
//   // src/schema.ts
//   export * from './generated/schema';            // entity tables
//   export * from './generated/subsystems-schema'; // subsystem tables + enums
//
// Regenerated by every \`codegen entity new\` / \`codegen subsystem install\`.

`;

// ---------------------------------------------------------------------------
// Import-specifier resolution (mode-aware, ADR-037)
// ---------------------------------------------------------------------------

/**
 * Where a subsystem's schema barrel symbols are re-exported FROM, per mode.
 *
 *   - `package`  → `@pattern-stack/codegen/runtime/subsystems/<name>/index`
 *   - `vendored` → `<subsystemsRel>/<name>`
 */
function schemaImportFor(
	mode: RuntimeMode,
	subsystem: SubsystemName,
	subsystemsRel: string,
): string {
	return mode === 'vendored'
		? `${subsystemsRel}/${subsystem}`
		: `${PACKAGE}/runtime/subsystems/${subsystem}/index`;
}

// ---------------------------------------------------------------------------
// Pure content builder
// ---------------------------------------------------------------------------

/**
 * Build the subsystem schema barrel content. Pure — no fs / DI. Emits one
 * `export { tableA, enumB, ... } from '<import>';` line per installed subsystem
 * that contributes schema. Empty installed set → `export {};` (valid empty
 * module; mirrors the entity schema barrel's empty case).
 */
export function buildSubsystemSchemaBarrel(
	installed: InstalledSubsystem[],
	subsystemsRel: string,
	mode: RuntimeMode,
): { content: string; emitted: SubsystemName[] } {
	const actable = installed.filter((i) => i.status !== 'incomplete');
	const installedNames = new Set(actable.map((i) => i.name));
	const emitted: SubsystemName[] = [];
	const lines: string[] = [];

	for (const name of SCHEMA_ORDER) {
		if (!installedNames.has(name)) continue;
		const symbols = SCHEMA_SYMBOLS[name];
		if (!symbols || symbols.length === 0) continue;
		const importSpec = schemaImportFor(mode, name, subsystemsRel);
		lines.push(`export { ${symbols.join(', ')} } from '${importSpec}';`);
		emitted.push(name);
	}

	const body = lines.length === 0 ? 'export {};\n' : lines.join('\n') + '\n';
	return { content: HEADER + body, emitted };
}

// ---------------------------------------------------------------------------
// Public entrypoint
// ---------------------------------------------------------------------------

/**
 * Resolve the installed set + mode, then write
 * `<generated>/subsystems-schema.ts`. Same mode-aware install resolution as the
 * subsystem composition barrel (config-driven in package mode, vendored-scan in
 * vendored mode).
 */
export async function regenerateSubsystemSchemaBarrel(
	opts: SubsystemSchemaBarrelOptions,
): Promise<SubsystemSchemaBarrelResult> {
	const { ctx, dryRun = false } = opts;
	const generatedDir = opts.generatedDir ?? resolveGeneratedDir(ctx);

	const mode = resolveRuntimeMode(ctx.config);
	const installed =
		mode === 'package'
			? configuredInstalledSubsystems(
					ctx.config as Record<string, unknown> | null | undefined,
				)
			: await detectInstalledSubsystems(ctx);

	const subsystemsAbs = resolveSubsystemsRoot(ctx);
	const barrelAbs = path.resolve(generatedDir, 'subsystems-schema.ts');
	let subsystemsRel = path
		.relative(path.dirname(barrelAbs), subsystemsAbs)
		.split(path.sep)
		.join('/');
	if (!subsystemsRel.startsWith('.')) subsystemsRel = './' + subsystemsRel;

	const { content, emitted } = buildSubsystemSchemaBarrel(
		installed,
		subsystemsRel,
		mode,
	);

	let written = false;
	if (!dryRun) {
		fs.mkdirSync(path.dirname(barrelAbs), { recursive: true });
		fs.writeFileSync(barrelAbs, content);
		written = true;
	}

	return { schemaBarrel: barrelAbs, emitted, content, written };
}
