/**
 * Frontend emitter — entity hook wiring tests (ADR-038, FE-3).
 *
 * String-level (pure builders). Asserts the `createEntityHooks` wiring shape:
 * factory import, single type param, localFirst closure keyed by singular name,
 * all 6 destructured re-exports, and a sorted index barrel.
 */

import { describe, expect, it } from 'bun:test';
import {
	buildEntityHooksFile,
	buildEntitiesIndexFile,
} from '../../../emitters/frontend/emit-entities';
import { ctx, entry } from './_helpers';

describe('emit-entities — hook wiring file', () => {
	it('imports createEntityHooks from the published package', () => {
		const c = ctx([entry('deal_state', 'deal_states')]);
		const out = buildEntityHooksFile(entry('deal_state', 'deal_states'), c);
		expect(out).toContain(
			"import { createEntityHooks } from '@pattern-stack/frontend-patterns';",
		);
	});

	it('calls createEntityHooks with a SINGLE type param (no Create/Update)', () => {
		const c = ctx([entry('deal_state', 'deal_states')]);
		const out = buildEntityHooksFile(entry('deal_state', 'deal_states'), c);
		expect(out).toContain('createEntityHooks<DealState>({');
		expect(out).not.toContain('DealStateCreate');
		expect(out).not.toContain('DealStateUpdate');
	});

	it('keys name + getSyncMode by the SINGULAR entity name (matches config.ts)', () => {
		const c = ctx([entry('deal_state', 'deal_states')]);
		const out = buildEntityHooksFile(entry('deal_state', 'deal_states'), c);
		expect(out).toContain("name: 'deal_state',");
		expect(out).toContain("getSyncMode('deal_state')");
		expect(out).not.toContain("name: 'deal_states',");
	});

	it('emits the localFirst closure (api ⇒ confirmed, else local-first)', () => {
		const c = ctx([entry('deal_state', 'deal_states')]);
		const out = buildEntityHooksFile(entry('deal_state', 'deal_states'), c);
		expect(out).toContain(
			"localFirst: () => getSyncMode('deal_state') !== 'api',",
		);
	});

	it('imports the entity type plain from dbEntities and the collection + api', () => {
		const c = ctx([entry('deal_state', 'deal_states')], {
			dbEntitiesImport: '@repo/db/entities',
		});
		const out = buildEntityHooksFile(entry('deal_state', 'deal_states'), c);
		expect(out).toContain(
			"import type { DealState } from '@repo/db/entities/deal_state';",
		);
		expect(out).toContain(
			"import { dealStateCollection } from '../collections/deal_state';",
		);
		expect(out).toContain("import { dealStateApi } from '../api/deal_state';");
	});

	it('destructures all 6 per-entity re-exports with pts naming', () => {
		const c = ctx([entry('deal_state', 'deal_states')]);
		const out = buildEntityHooksFile(entry('deal_state', 'deal_states'), c);
		expect(out).toContain('useList: useDealStateList,');
		expect(out).toContain('useGet: useDealState,');
		expect(out).toContain('useCreate: useCreateDealState,');
		expect(out).toContain('useUpdate: useUpdateDealState,');
		expect(out).toContain('useDelete: useDeleteDealState,');
		expect(out).toContain('keys: dealStateKeys,');
	});

	it('emits no state-machine block', () => {
		const c = ctx([entry('deal_state', 'deal_states')]);
		const out = buildEntityHooksFile(entry('deal_state', 'deal_states'), c);
		expect(out).not.toContain('useTransition');
		expect(out).not.toContain('useMutation');
	});

	it('starts with the @generated banner and is deterministic', () => {
		const c = ctx([entry('deal_state', 'deal_states')]);
		const a = buildEntityHooksFile(entry('deal_state', 'deal_states'), c);
		const b = buildEntityHooksFile(entry('deal_state', 'deal_states'), c);
		expect(a.startsWith('// @generated by @pattern-stack/codegen')).toBe(true);
		expect(a).toBe(b);
	});
});

describe('emit-entities — index barrel', () => {
	it('re-exports the hooks + 6 named hooks per entity, sorted by name', () => {
		const c = ctx([entry('zeta', 'zetas'), entry('alpha', 'alphas')]);
		const out = buildEntitiesIndexFile(c);
		expect(out).toContain('alphaHooks,');
		expect(out).toContain('useAlphaList,');
		expect(out).toContain('alphaKeys,');
		expect(out).toContain("} from './alpha';");
		const alphaIdx = out.indexOf("from './alpha'");
		const zetaIdx = out.indexOf("from './zeta'");
		expect(alphaIdx).toBeGreaterThan(-1);
		expect(zetaIdx).toBeGreaterThan(alphaIdx);
	});
});
