/**
 * Frontend emitter — REST api client tests (ADR-038, FE-2).
 *
 * Covers client.ts baseURL variants + auth on/off + 204 handling, per-entity
 * routes/verbs (clean → PUT, clean-lite-ps → PATCH), the plain entity-type
 * import, and the index barrel.
 */

import { describe, expect, it } from 'bun:test';
import {
	buildApiIndexFile,
	buildClientFile,
	buildEntityApiFile,
} from '../../../emitters/frontend/emit-api';
import { ctx, entry } from './_helpers';

describe('emit-api — client.ts', () => {
	it('uses the literal apiUrl as baseURL by default', () => {
		const out = buildClientFile(ctx([], { apiUrl: '/api' }));
		expect(out).toContain("const BASE_URL = '/api';");
		expect(out).not.toContain('API_BASE_URL');
	});

	it('uses API_BASE_URL import when apiBaseUrlImport is set', () => {
		const out = buildClientFile(ctx([], { apiBaseUrlImport: '@/config' }));
		expect(out).toContain("import { API_BASE_URL } from '@/config';");
		expect(out).toContain('const BASE_URL = API_BASE_URL;');
	});

	it('emits an Authorization header when authFunction is set', () => {
		const out = buildClientFile(
			ctx([], { authFunction: 'getAuthorizationHeader', authImport: '@/auth' }),
		);
		expect(out).toContain("import { getAuthorizationHeader } from '@/auth';");
		expect(out).toContain('Authorization: getAuthorizationHeader(),');
	});

	it('emits no auth header lines when authFunction is null', () => {
		const out = buildClientFile(ctx([], { authFunction: null }));
		expect(out).not.toContain('Authorization');
	});

	it('throws with METHOD path → status on non-ok, returns undefined for 204', () => {
		const out = buildClientFile(ctx([]));
		expect(out).toContain(
			'throw new Error(`${method} ${path} → ${res.status} ${res.statusText}`);',
		);
		expect(out).toContain('if (res.status === 204) {');
		expect(out).toContain('return undefined as T;');
	});

	it('starts with the house banner', () => {
		const out = buildClientFile(ctx([]));
		expect(out.startsWith('// @generated by @pattern-stack/codegen')).toBe(true);
	});
});

describe('emit-api — <entity>.ts routes + verbs', () => {
	it('emits list/get/create/update/delete against the plural routes', () => {
		const out = buildEntityApiFile(entry('contact', 'contacts'), ctx([]));
		expect(out).toContain("list: (): Promise<Contact[]> => request<Contact[]>('GET', '/contacts')");
		expect(out).toContain("request<Contact>('GET', `/contacts/${id}`)");
		expect(out).toContain("request<Contact>('POST', '/contacts', data)");
		expect(out).toContain("request<void>('DELETE', `/contacts/${id}`)");
	});

	it('clean architecture uses PUT for update', () => {
		const out = buildEntityApiFile(entry('contact', 'contacts'), ctx([], { architecture: 'clean' }));
		expect(out).toContain("request<Contact>('PUT', `/contacts/${id}`, data)");
		expect(out).not.toContain("'PATCH'");
	});

	it('clean-lite-ps architecture uses PATCH for update', () => {
		const out = buildEntityApiFile(
			entry('contact', 'contacts'),
			ctx([], { architecture: 'clean-lite-ps' }),
		);
		expect(out).toContain("request<Contact>('PATCH', `/contacts/${id}`, data)");
		expect(out).not.toContain("'PUT'");
	});

	it('imports the plain entity type (not <Class>Entity) from dbEntities/<name>', () => {
		const out = buildEntityApiFile(
			entry('deal_state', 'deal_states'),
			ctx([], { dbEntitiesImport: '@repo/db/entities' }),
		);
		expect(out).toContain("import type { DealState } from '@repo/db/entities/deal_state';");
		expect(out).not.toContain('DealStateEntity');
		expect(out).toContain('export const dealStateApi = {');
	});

	it('attributes the per-entity file to its source YAML in the banner', () => {
		const out = buildEntityApiFile(entry('contact', 'contacts'), ctx([]));
		expect(out).toContain('from entities/contact.yaml');
	});
});

describe('emit-api — index barrel', () => {
	it('re-exports the client and each entity api, sorted', () => {
		const out = buildApiIndexFile(ctx([entry('zeta', 'zetas'), entry('alpha', 'alphas')]));
		const clientIdx = out.indexOf("export * from './client';");
		const alphaIdx = out.indexOf("export * from './alpha';");
		const zetaIdx = out.indexOf("export * from './zeta';");
		expect(clientIdx).toBeGreaterThan(-1);
		expect(alphaIdx).toBeGreaterThan(clientIdx);
		expect(zetaIdx).toBeGreaterThan(alphaIdx);
	});
});
