/**
 * Frontend emitter — providers catalog tests (ADR-038 follow-on).
 *
 * providers.ts: flat PROVIDERS (slug-sorted, active + planned), category-
 * grouped PROVIDER_CATALOG (config order; display.category join), planned
 * flag, name fallback, hint/blurb passthrough, skip-when-empty, and the
 * conditional root-barrel export.
 */

import { describe, expect, it } from 'bun:test';
import { buildProvidersFile } from '../../../emitters/frontend/emit-providers';
import { buildRootIndexFile } from '../../../emitters/frontend/emit-index';
import type { ProviderCatalogInput } from '../../../emitters/frontend/types';
import { ctx, entry } from './_helpers';

const google: ProviderCatalogInput = {
	slug: 'google',
	displayName: 'Google Workspace',
	surfaces: ['calendar', 'mail', 'transcript'],
	status: 'active',
	display: { category: 'google-workspace' },
};

const slack: ProviderCatalogInput = {
	slug: 'slack',
	displayName: 'Slack',
	surfaces: ['messaging'],
	status: 'active',
	display: { category: 'messaging' },
};

const github: ProviderCatalogInput = {
	slug: 'github',
	displayName: 'GitHub',
	surfaces: ['source_control'],
	status: 'planned',
	display: { category: 'source-control' },
};

const linear: ProviderCatalogInput = {
	slug: 'linear',
	displayName: 'Linear',
	surfaces: ['task_management'],
	status: 'planned',
	display: { category: 'source-control', hint: 'connect' },
};

const CATEGORIES = [
	{ id: 'source-control', name: 'Source Control & Issues', blurb: 'Repos and planning' },
	{ id: 'messaging', name: 'Messaging', blurb: 'Channels and DMs' },
	{ id: 'google-workspace', name: 'Google Workspace', blurb: 'One OAuth, three surfaces' },
];

function catalogCtx(providers: ProviderCatalogInput[]) {
	return ctx([entry('connection', 'connections')], { catalogCategories: CATEGORIES }, undefined, providers);
}

describe('emit-providers — PROVIDERS (flat)', () => {
	it('lists every provider slug-sorted with planned flags and surfaces', () => {
		const out = buildProvidersFile(catalogCtx([slack, google, github]));
		const gh = out.indexOf("provider: 'github'");
		const go = out.indexOf("provider: 'google'");
		const sl = out.indexOf("provider: 'slack'");
		expect(gh).toBeGreaterThan(-1);
		expect(gh).toBeLessThan(go);
		expect(go).toBeLessThan(sl);
		expect(out).toContain("surfaces: ['calendar', 'mail', 'transcript'],");
		expect(out).toContain('planned: true,');
		expect(out).toContain('planned: false,');
	});

	it('falls back to the slug when display_name is absent', () => {
		const bare: ProviderCatalogInput = { slug: 'acme', surfaces: ['crm'], status: 'active' };
		const out = buildProvidersFile(catalogCtx([bare]));
		expect(out).toContain("name: 'acme',");
	});

	it('passes hint and blurb through when declared', () => {
		const out = buildProvidersFile(catalogCtx([linear]));
		expect(out).toContain("hint: 'connect',");
	});
});

describe('emit-providers — PROVIDER_CATALOG (grouped)', () => {
	it('renders categories in config order with display.category-joined vendors', () => {
		const out = buildProvidersFile(catalogCtx([google, slack, github, linear]));
		const sc = out.indexOf("id: 'source-control'");
		const msg = out.indexOf("id: 'messaging'");
		const gw = out.indexOf("id: 'google-workspace'");
		expect(sc).toBeGreaterThan(-1);
		expect(sc).toBeLessThan(msg);
		expect(msg).toBeLessThan(gw);
		// github + linear grouped under source-control, slug-sorted.
		const scBlock = out.slice(sc, msg);
		expect(scBlock).toContain("provider: 'github'");
		expect(scBlock).toContain("provider: 'linear'");
		expect(scBlock.indexOf("provider: 'github'")).toBeLessThan(
			scBlock.indexOf("provider: 'linear'"),
		);
	});

	it('keeps an uncategorized provider out of the catalog but in PROVIDERS', () => {
		const stray: ProviderCatalogInput = { slug: 'stray', surfaces: ['crm'], status: 'active' };
		const out = buildProvidersFile(catalogCtx([stray]));
		const flatEnd = out.indexOf('PROVIDER_CATALOG');
		expect(out.slice(0, flatEnd)).toContain("provider: 'stray'");
		expect(out.slice(flatEnd)).not.toContain("provider: 'stray'");
	});

	it('emits a declared category even when no provider joins it', () => {
		const out = buildProvidersFile(catalogCtx([google]));
		expect(out).toContain("id: 'messaging',");
		expect(out).toContain('vendors: [],');
	});

	it('is deterministic and carries the banner', () => {
		const c = catalogCtx([google, slack]);
		expect(buildProvidersFile(c)).toBe(buildProvidersFile(c));
		expect(buildProvidersFile(c).startsWith('// @generated by @pattern-stack/codegen')).toBe(
			true,
		);
	});
});

describe('emit-providers — root barrel gating', () => {
	it('exports ./providers from the barrel only when providers exist', () => {
		const withProviders = ctx([entry('connection', 'connections')], {}, undefined, [google]);
		const without = ctx([entry('connection', 'connections')]);
		expect(buildRootIndexFile(withProviders)).toContain("export * from './providers';");
		expect(buildRootIndexFile(without)).not.toContain("export * from './providers';");
	});
});
