// @generated by @pattern-stack/codegen from test/fixtures/entities/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, Inject, Optional } from '@nestjs/common';
import { WithAnalytics } from '@shared/base-classes/with-analytics';
import { EVENT_BUS } from '@shared/constants/tokens';
import { BaseService } from '@shared/base-classes/base-service';
import { DealStateRepository } from './deal-state.repository';
import type {
  DealStateInclude,
  DealStateNoInclude,
  DealStateResult,
} from './deal-state.repository';
import type { ListOptions } from '@shared/base-classes/base-repository';
import type { DealState } from './deal-state.entity';
import { OpportunityRepository } from '../opportunities/opportunity.repository';
import type { Opportunity } from '../opportunities/opportunity.entity';

@Injectable()
export class DealStateService extends WithAnalytics(
  BaseService<DealStateRepository, DealState>,
) {
  protected override readonly entityName = 'deal_state';

  /** Injected by NestJS when EventsModule is registered. */
  @Optional() @Inject(EVENT_BUS)
  protected override eventBus: any = undefined;

  constructor(
    protected override readonly repository: DealStateRepository,
    private readonly opportunityRepo: OpportunityRepository,
  ) {
    super(repository);
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Typed `with` includes (REL-2, #587) — pass-through, not composition
  //
  // These two overrides exist so the HTTP layer can carry an allowlisted include
  // from the controller to the repository. They are DELEGATION ONLY: no join
  // logic, no sibling-repository calls, no navigator. The typed navigator and the
  // deletion of the CGP-358b composition methods below are REL-3's (#588).
  // ═══════════════════════════════════════════════════════════════════════

  override findById<TWith extends DealStateInclude = DealStateNoInclude>(
    id: string,
    opts?: { with?: TWith },
  ): Promise<DealStateResult<TWith> | null> {
    return this.repository.findById<TWith>(id, opts);
  }

  override list<TWith extends DealStateInclude = DealStateNoInclude>(
    options?: ListOptions & { with?: TWith },
  ): Promise<Array<DealStateResult<TWith>>> {
    return this.repository.list<TWith>(options);
  }

  // Lifecycle events (created/updated/deleted + per-field changes) are emitted
  // automatically by BaseService when the events subsystem is installed.
  //
  // Inherited from BaseService:
  //   findById, findByIds, list, count, exists, create, update, delete

  // ═══════════════════════════════════════════════════════════════════════
  // Relationship composition methods (CGP-358b / CGP-62)
  // Two queries, no SQL JOIN.
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Fetch opportunities for this DealState by FK traversal.
   * Single repo call with optional cursor/limit pagination.
   */
  async opportunities(dealStateId: string, opts?: { cursor?: string; limit?: number }): Promise<Opportunity[]> {
    return this.opportunityRepo.findByStateId(dealStateId, opts);
  }
}
