// @generated by @pattern-stack/codegen from test/fixtures/entities/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Controller, Get, Post, Patch, Delete, Body, NotFoundException, Param, ParseUUIDPipe, Query } from '@nestjs/common';
import { ApiBearerAuth, ApiBody, ApiOperation, ApiParam, ApiQuery, ApiResponse } from '@nestjs/swagger';
import { ZodValidationPipe } from '@shared/pipes/zod-validation.pipe';
import type { Page } from '@shared/http/page';
import { ListDealStatesQuerySchema } from './dto/list-deal-states.query';
import type { ListDealStatesQueryDto } from './dto/list-deal-states.query';
import { FindDealStateByIdUseCase } from './use-cases/find-deal-state-by-id.use-case';
import { ListDealStatesUseCase } from './use-cases/list-deal-states.use-case';
import { CreateDealStateUseCase } from './use-cases/create-deal-state.use-case';
import { UpdateDealStateUseCase } from './use-cases/update-deal-state.use-case';
import { DeleteDealStateUseCase } from './use-cases/delete-deal-state.use-case';
import { CreateDealStateSchema } from './dto/create-deal-state.dto';
import type { CreateDealStateDto } from './dto/create-deal-state.dto';
import { UpdateDealStateSchema } from './dto/update-deal-state.dto';
import type { UpdateDealStateDto } from './dto/update-deal-state.dto';
import type { DealState } from './deal-state.entity';

// OPENAPI-3: decorators reference registered schemas by `$ref` because
// the DTOs are Zod-derived types (OPENAPI-2 registers them by name at
// onModuleInit). `ErrorResponseDto` is auto-registered by the shared
// registry.
@ApiBearerAuth()
@Controller('deal_states')
export class DealStateController {
  constructor(
    // All routes go through use cases (ADR-003 — no controller → service shortcuts)
    private readonly findByIdUseCase: FindDealStateByIdUseCase,
    private readonly listUseCase: ListDealStatesUseCase,
    private readonly createUseCase: CreateDealStateUseCase,
    private readonly updateUseCase: UpdateDealStateUseCase,
    private readonly deleteUseCase: DeleteDealStateUseCase,
  ) {}

  @ApiOperation({ summary: 'List deal_states', operationId: 'listDealStates' })
  @ApiQuery({ name: 'page', required: false, type: 'integer', description: '1-based page number (default 1).' })
  @ApiQuery({ name: 'pageSize', required: false, type: 'integer', description: 'Page size (default 50, max 200).' })
  @ApiQuery({ name: 'cursor', required: false, type: 'string', description: 'Opaque keyset cursor (accepted; v1 paginates by offset).' })
  @ApiQuery({ name: 'sort_by', required: false, type: 'string', description: "Sort column (default 'created_at')." })
  @ApiQuery({ name: 'sort_order', required: false, enum: ['asc', 'desc'], description: "Sort direction (default 'desc')." })
  @ApiResponse({
    status: 200,
    schema: {
      type: 'object',
      properties: {
        items: { type: 'array', items: { $ref: '#/components/schemas/DealStateOutputDto' } },
        page: { type: 'integer' },
        pageCount: { type: 'integer' },
        total: { type: 'integer' },
        pageSize: { type: 'integer' },
        nextCursor: { type: 'string', nullable: true },
      },
      required: ['items', 'page', 'pageCount', 'total', 'pageSize', 'nextCursor'],
    },
  })
  @ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @Get()
  async getAll(
    @Query(new ZodValidationPipe(ListDealStatesQuerySchema)) query: ListDealStatesQueryDto,
  ): Promise<Page<DealState>> {
    return this.listUseCase.execute(query);
  }

  @ApiOperation({ summary: 'Find deal_state by id', operationId: 'findDealStateById' })
  @ApiResponse({ status: 200, schema: { $ref: '#/components/schemas/DealStateOutputDto' } })
  @ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @ApiParam({ name: 'id', type: 'string', format: 'uuid' })
  @Get(':id')
  async getById(@Param('id', ParseUUIDPipe) id: string): Promise<DealState> {
    // Use case throws NotFoundException on null/undefined (D2)
    return this.findByIdUseCase.execute(id);
  }


  @ApiOperation({ summary: 'Create deal_state', operationId: 'createDealState' })
  @ApiBody({ schema: { $ref: '#/components/schemas/CreateDealStateDto' } })
  @ApiResponse({ status: 201, schema: { $ref: '#/components/schemas/DealStateOutputDto' } })
  @ApiResponse({ status: 400, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @Post()
  async create(
    @Body(new ZodValidationPipe(CreateDealStateSchema)) dto: CreateDealStateDto,
  ): Promise<DealState> {
    return this.createUseCase.execute(dto);
  }

  @ApiOperation({ summary: 'Update deal_state', operationId: 'updateDealState' })
  @ApiBody({ schema: { $ref: '#/components/schemas/UpdateDealStateDto' } })
  @ApiResponse({ status: 200, schema: { $ref: '#/components/schemas/DealStateOutputDto' } })
  @ApiResponse({ status: 400, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @ApiParam({ name: 'id', type: 'string', format: 'uuid' })
  @Patch(':id')
  async update(
    @Param('id', ParseUUIDPipe) id: string,
    @Body(new ZodValidationPipe(UpdateDealStateSchema)) dto: UpdateDealStateDto,
  ): Promise<DealState> {
    const entity = await this.updateUseCase.execute(id, dto);
    if (!entity) throw new NotFoundException(`DealState ${id} not found`);
    return entity;
  }

  @ApiOperation({ summary: 'Delete deal_state', operationId: 'deleteDealState' })
  @ApiResponse({ status: 204 })
  @ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
  @ApiParam({ name: 'id', type: 'string', format: 'uuid' })
  @Delete(':id')
  async remove(
    @Param('id', ParseUUIDPipe) id: string,
  ): Promise<void> {
    return this.deleteUseCase.execute(id);
  }

}
