---
to: "<%= generate.commands ? outputPaths.commandsIndex : '' %>"
skip_if: <%= !isCleanArchitecture %>
force: true
---
<%- typeof generatedBanner !== 'undefined' ? generatedBanner : '' %>
<% if (outputPaths.commandsIndex) { -%>
/**
 * <%= className %> Commands Barrel Export
 * Generated by entity codegen - do not edit directly
 */

export * from './<%= fileNames.createCommand.replace('.ts', '') %>';
export * from './<%= fileNames.updateCommand.replace('.ts', '') %>';
export * from './<%= fileNames.deleteCommand.replace('.ts', '') %>';
<% } -%>
