/**
 * DealState Domain Entity
 * Generated by entity codegen - do not edit directly
 *
 * NOTE: Related entity imports assume a nested folder structure where each entity
 * lives in its own folder (e.g., domain/{entity}/{entity}.entity.ts). This follows
 * CLEAN architecture conventions where each aggregate root has its own bounded context.
 * All entities should follow this structure for consistent imports.
 */

import type { Opportunity } from '../opportunity/opportunity.entity';

export class DealState {
	constructor(
		public readonly id: string,
		public readonly tenantId: string | null,
		public readonly name: string,
		public readonly displayName: string,
		public readonly stateType: 'open' | 'won' | 'lost' | 'stalled',
		public readonly sortOrder: number,
		public readonly probabilityDefault: number | null,
		public readonly color: string | null,
		// Loaded relations (optional, populated when eager-loaded)
		public readonly opportunities?: Opportunity[],
	) {}

	static fromRecord(
		// biome-ignore lint/suspicious/noExplicitAny: Drizzle records have dynamic shape
		record: Record<string, any>,
		// biome-ignore lint/suspicious/noExplicitAny: Returns different entity types
		mapRelation?: (name: string, data: unknown) => any,
	): DealState {
		return new DealState(
			record.id,
			record.tenantId,
			record.name,
			record.displayName,
			record.stateType,
			record.sortOrder,
			record.probabilityDefault,
			record.color,
			record.opportunities ? mapRelation?.('opportunities', record.opportunities) : undefined,
		);
	}
}
