/**
 * DealState Repository Interface
 * Generated by entity codegen - do not edit directly
 */

import type { DealState } from './deal_state.entity';

/**
 * Type-safe eager loading options.
 * Pass to repository methods to include related entities.
 */
export type DealStateWith = {
	opportunities?: boolean;
};

/**
 * Domain-level input types for repository operations.
 */
export type CreateDealStateInput = {
	tenantId?: string | null;
	name: string;
	displayName: string;
	stateType: 'open' | 'won' | 'lost' | 'stalled';
	sortOrder: number;
	probabilityDefault?: number | null;
	color?: string | null;
};

export type UpdateDealStateInput = Partial<CreateDealStateInput>;

export interface IDealStateRepository {
	create(input: CreateDealStateInput): Promise<DealState>;
	findById(id: string, include?: DealStateWith): Promise<DealState | null>;
	findAll(include?: DealStateWith): Promise<DealState[]>;
	update(id: string, input: UpdateDealStateInput): Promise<DealState | null>;
	delete(id: string): Promise<DealState | null>;
}
