// @generated by @pattern-stack/codegen from test/fixtures/entities/demo-deal.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Controller, Get, Query } from '@nestjs/common';
import { z } from 'zod';
import { ZodValidationPipe } from '@shared/pipes/zod-validation.pipe';
import { ListQuerySchema, type Page } from '@shared/http/page';
import { SearchDealsUseCase } from './use-cases/search-deals.use-case';
import type { Deal } from './deal.entity';

/**
 * The list endpoint's query (page / pageSize / cursor / sort_by / sort_order)
 * extended with the filters declared in deal.yaml — so search pages
 * and sorts exactly as `GET /deals` does (#744).
 */
const DealFiltersSchema = ListQuerySchema.extend({
  stage: z.enum(['prospecting', 'qualification', 'proposal', 'negotiation', 'closed_won', 'closed_lost']).optional(),
  ownerId: z.string().uuid().optional(),
  search: z.string().optional(),
});

/**
 * Filtered search controller — generated from the `queries: - name: search`
 * block in deal.yaml. Returns the same `Page<T>` envelope as the
 * list endpoint.
 */
@Controller('deals')
export class DealSearchController {
  constructor(private readonly searchUseCase: SearchDealsUseCase) {}

  @Get('search')
  async search(
    @Query(new ZodValidationPipe(DealFiltersSchema))
    query: z.infer<typeof DealFiltersSchema>,
  ): Promise<Page<Deal>> {
    return this.searchUseCase.execute(query);
  }
}
