// @generated by @pattern-stack/codegen from test/fixtures/entities/demo-deal.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, Inject, Optional } from '@nestjs/common';
import { WithAnalytics } from '@shared/base-classes/with-analytics';
import { EVENT_BUS } from '@shared/constants/tokens';
import { IntegratedEntityService } from '@shared/base-classes/integrated-entity-service';
import { DealRepository } from './deal.repository';
import type {
  DealInclude,
  DealNoInclude,
  DealResult,
} from './deal.repository';
import type { ListOptions } from '@shared/base-classes/base-repository';
import type { Deal } from './deal.entity';
import { UserRepository } from '../users/user.repository';
import type { User } from '../users/user.entity';
import { AccountRepository } from '../accounts/account.repository';
import type { Account } from '../accounts/account.entity';

@Injectable()
export class DealService extends WithAnalytics(
  IntegratedEntityService<DealRepository, Deal>,
) {
  protected override readonly entityName = 'deal';

  /** Injected by NestJS when EventsModule is registered. */
  @Optional() @Inject(EVENT_BUS)
  protected override eventBus: any = undefined;

  constructor(
    protected override readonly repository: DealRepository,
    private readonly userRepo: UserRepository,
    private readonly accountRepo: AccountRepository,
  ) {
    super(repository);
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Typed `with` includes (REL-2, #587) — pass-through, not composition
  //
  // These two overrides exist so the HTTP layer can carry an allowlisted include
  // from the controller to the repository. They are DELEGATION ONLY: no join
  // logic, no sibling-repository calls, no navigator. The typed navigator and the
  // deletion of the CGP-358b composition methods below are REL-3's (#588).
  // ═══════════════════════════════════════════════════════════════════════

  override findById<TWith extends DealInclude = DealNoInclude>(
    id: string,
    opts?: { with?: TWith },
  ): Promise<DealResult<TWith> | null> {
    return this.repository.findById<TWith>(id, opts);
  }

  override list<TWith extends DealInclude = DealNoInclude>(
    options?: ListOptions & { with?: TWith },
  ): Promise<Array<DealResult<TWith>>> {
    return this.repository.list<TWith>(options);
  }

  // Lifecycle events (created/updated/deleted + per-field changes) are emitted
  // automatically by BaseService when the events subsystem is installed.
  //
  // Inherited from IntegratedEntityService:
  //   findById, findByIds, list, count, exists, create, update, delete
  //   findByExternalId, findAllByUserId, findVisibleByUserId

  // ═══════════════════════════════════════════════════════════════════════
  // Declarative queries (from queries: block in entity YAML)
  // Pass-through to repository — keeps use-cases on the service layer so
  // cross-cutting concerns (analytics, events) stay uniform.
  // ═══════════════════════════════════════════════════════════════════════

  async findByOwnerId(ownerId: string): Promise<Deal[]> {
    return this.repository.findByOwnerId(ownerId);
  }

  async findByAccountId(accountId: string): Promise<Deal[]> {
    return this.repository.findByAccountId(accountId);
  }

  async findByStage(stage: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost'): Promise<Deal[]> {
    return this.repository.findByStage(stage);
  }

  async findByOwnerIdAndStage(ownerId: string, stage: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost'): Promise<Deal[]> {
    return this.repository.findByOwnerIdAndStage(ownerId, stage);
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Relationship composition methods (CGP-358b / CGP-62)
  // Two queries, no SQL JOIN.
  // ═══════════════════════════════════════════════════════════════════════

  /**
   * Fetch the User parent for this Deal.
   * Two repo calls: find self by id → find target by FK.
   */
  async user(dealId: string): Promise<User | null> {
    const entity = await this.repository.findById(dealId);
    if (!entity) return null;
    return entity.ownerId ? this.userRepo.findById(entity.ownerId) : null;
  }

  /**
   * Fetch the Account parent for this Deal.
   * Two repo calls: find self by id → find target by FK.
   */
  async account(dealId: string): Promise<Account | null> {
    const entity = await this.repository.findById(dealId);
    if (!entity) return null;
    return entity.accountId ? this.accountRepo.findById(entity.accountId) : null;
  }
}
