/**
 * Unit tests for the per-entity assembly module + tokens emitter
 * (RFC-0002 §2/§4, Track D · E2).
 *
 * Pure-emitter assertions only (no filesystem wiring — that is exercised by the
 * integration-emit snapshot). Locks the Option A factory line, the module class
 * + token naming, the import set, and the exports.
 */

import { describe, expect, test } from "bun:test";
import {
  generateAssemblyModule,
  generateIntegrationAggregator,
  generateIntegrationTokens,
  assemblyModuleClass,
  integrationUseCaseToken,
  resolveEntityModuleImports,
  type AssemblyEmitInput,
  type IntegrationAssemblyEntry,
  type IntegrationTokenEntry,
} from "../../cli/shared/assembly-emission-generator";

const meetingGoogle: AssemblyEmitInput = {
  surface: "calendar",
  provider: "google",
  entityName: "meeting",
  entityClass: "Meeting",
  moduleImportSpecifier: "@modules/meetings/meetings.module",
  moduleClass: "MeetingsModule",
  repoImportSpecifier: "@modules/meetings/meeting.repository",
  repoClass: "MeetingRepository",
  sourceDesc: "definitions/providers/google.yaml",
};

describe("assembly-emission-generator — names", () => {
  test("module class name is <Entity>IntegrationModule__<Provider>", () => {
    expect(assemblyModuleClass("meeting", "google")).toBe(
      "MeetingIntegrationModule__Google",
    );
    // snake_case entity + kebab provider slug each pascalize their parts
    expect(assemblyModuleClass("call_recording", "ms-graph")).toBe(
      "CallRecordingIntegrationModule__MsGraph",
    );
  });

  test("token const name is <ENTITY>_INTEGRATION_USE_CASE__<PROVIDER>", () => {
    expect(integrationUseCaseToken("meeting", "google")).toBe(
      "MEETING_INTEGRATION_USE_CASE__GOOGLE",
    );
    expect(integrationUseCaseToken("call_recording", "ms-graph")).toBe(
      "CALL_RECORDING_INTEGRATION_USE_CASE__MS_GRAPH",
    );
  });
});

describe("generateAssemblyModule — Option A assembly", () => {
  const out = generateAssemblyModule(meetingGoogle);

  test("carries the @generated banner (re-emit, never hand-edit)", () => {
    expect(out).toContain(
      "// @generated by @pattern-stack/codegen from definitions/providers/google.yaml — DO NOT EDIT.",
    );
  });

  test("module class name", () => {
    expect(out).toContain("export class MeetingIntegrationModule__Google {}");
  });

  test("imports only the entity module + adapter module (Option A — no aggregator)", () => {
    expect(out).toContain("imports: [MeetingsModule, GoogleCalendarAdapterModule],");
    // no surface adapters aggregator import
    expect(out).not.toContain("CalendarAdaptersModule");
    expect(out).not.toContain("RawLandingModule");
    expect(out).not.toContain("InteractionModule");
  });

  test("Option A change-source factory binds adapter.changeSources['<entity>']", () => {
    expect(out).toContain(
      "useFactory: (adapter: GoogleCalendarAdapter) => adapter.changeSources['meeting'],",
    );
    expect(out).toContain("inject: [GoogleCalendarAdapter],");
  });

  test("sink factory binds a provider-bound <Entity>Sink over the repo", () => {
    expect(out).toContain(
      "useFactory: (repo: MeetingRepository) => new MeetingSink(repo, 'google'),",
    );
    expect(out).toContain("inject: [MeetingRepository],");
  });

  test("provides a local ExecuteIntegrationUseCase aliased under the unique token", () => {
    expect(out).toContain("ExecuteIntegrationUseCase,");
    expect(out).toContain(
      "{ provide: MEETING_INTEGRATION_USE_CASE__GOOGLE, useExisting: ExecuteIntegrationUseCase },",
    );
  });

  test("exports only the unique token (the bare class is ambiguous at app root)", () => {
    expect(out).toContain("exports: [MEETING_INTEGRATION_USE_CASE__GOOGLE],");
  });

  test("subsystem symbols imported from @pattern-stack/codegen/subsystems", () => {
    expect(out).toContain(
      "import {\n  ExecuteIntegrationUseCase,\n  INTEGRATION_CHANGE_SOURCE,\n  INTEGRATION_SINK,\n} from '@pattern-stack/codegen/subsystems';",
    );
  });

  test("adapter + sink imports use the ../../ relative convention from modules/<provider>/", () => {
    expect(out).toContain(
      "import { GoogleCalendarAdapter } from '../../adapters/google/google-calendar.adapter';",
    );
    expect(out).toContain(
      "import { GoogleCalendarAdapterModule } from '../../adapters/google/google-calendar.adapter.module';",
    );
    expect(out).toContain("import { MeetingSink } from '../../sinks/meeting.sink';");
    expect(out).toContain(
      "import { MEETING_INTEGRATION_USE_CASE__GOOGLE } from '../../calendar-integration.tokens';",
    );
  });

  test("entity repo + module imports use the caller-computed specifiers (alias form)", () => {
    expect(out).toContain(
      "import { MeetingRepository } from '@modules/meetings/meeting.repository';",
    );
    expect(out).toContain(
      "import { MeetingsModule } from '@modules/meetings/meetings.module';",
    );
  });
});

describe("generateIntegrationTokens — surface tokens file", () => {
  const entries: IntegrationTokenEntry[] = [
    { entityName: "meeting", entityClass: "Meeting", provider: "google" },
    { entityName: "meeting", entityClass: "Meeting", provider: "outlook" },
    { entityName: "event", entityClass: "Event", provider: "google" },
  ];
  const out = generateIntegrationTokens("calendar", entries);

  test("@generated banner", () => {
    expect(out).toContain("// @generated by @pattern-stack/codegen from surface: calendar");
  });

  test("one Symbol token per (entity, provider), sorted by entity then provider", () => {
    expect(out).toContain(
      "export const EVENT_INTEGRATION_USE_CASE__GOOGLE = Symbol.for('@app/integrations/calendar.event-integration-use-case.google');",
    );
    expect(out).toContain(
      "export const MEETING_INTEGRATION_USE_CASE__GOOGLE = Symbol.for('@app/integrations/calendar.meeting-integration-use-case.google');",
    );
    expect(out).toContain(
      "export const MEETING_INTEGRATION_USE_CASE__OUTLOOK = Symbol.for('@app/integrations/calendar.meeting-integration-use-case.outlook');",
    );
    // ordering: event before meeting; google before outlook
    const iEvent = out.indexOf("EVENT_INTEGRATION_USE_CASE__GOOGLE");
    const iMtgGoogle = out.indexOf("MEETING_INTEGRATION_USE_CASE__GOOGLE");
    const iMtgOutlook = out.indexOf("MEETING_INTEGRATION_USE_CASE__OUTLOOK");
    expect(iEvent).toBeLessThan(iMtgGoogle);
    expect(iMtgGoogle).toBeLessThan(iMtgOutlook);
  });

  test("each token carries a doc comment", () => {
    expect(out).toContain(
      "/** Unique handle for the meeting ← google integration use-case",
    );
  });

  test("empty surface emits a placeholder comment, no tokens", () => {
    const empty = generateIntegrationTokens("calendar", []);
    expect(empty).toContain(
      "// no (entity, provider) integration assemblies on this surface yet",
    );
    expect(empty).not.toContain("Symbol.for");
  });
});

describe("generateIntegrationAggregator — surface integration aggregator (E3)", () => {
  const entries: IntegrationAssemblyEntry[] = [
    { entityName: "meeting", provider: "google" },
    { entityName: "email", provider: "google" },
  ];
  const out = generateIntegrationAggregator("calendar", entries);

  test("@generated banner (re-emit, never hand-edit)", () => {
    expect(out).toContain(
      "// @generated by @pattern-stack/codegen from surface: calendar",
    );
  });

  test("class name is <Surface>IntegrationModule (PascalCase surface)", () => {
    expect(out).toContain("export class CalendarIntegrationModule {}");
  });

  test("imports one assembly module per (provider, entity), sorted provider then entity", () => {
    // google provider; email before meeting (entity sort within provider).
    expect(out).toContain(
      "import { EmailIntegrationModule__Google } from './modules/google/email-integration.module';",
    );
    expect(out).toContain(
      "import { MeetingIntegrationModule__Google } from './modules/google/meeting-integration.module';",
    );
    const iEmail = out.indexOf("EmailIntegrationModule__Google } from");
    const iMeeting = out.indexOf("MeetingIntegrationModule__Google } from");
    expect(iEmail).toBeLessThan(iMeeting);
  });

  test("imports AND exports the SAME assembly modules (re-export so tokens propagate)", () => {
    // A Nest module that imports+exports a sub-module re-exposes its exports —
    // the assembly's <ENTITY>_INTEGRATION_USE_CASE__<PROVIDER> token reaches the app.
    expect(out).toContain(
      "imports: [EmailIntegrationModule__Google, MeetingIntegrationModule__Google],",
    );
    expect(out).toContain(
      "exports: [EmailIntegrationModule__Google, MeetingIntegrationModule__Google],",
    );
  });

  test("deterministic ordering: sort by provider, then entity (independent of input order)", () => {
    const shuffled = generateIntegrationAggregator("calendar", [
      { entityName: "meeting", provider: "zoom" },
      { entityName: "meeting", provider: "google" },
      { entityName: "email", provider: "google" },
    ]);
    // google (email, meeting) before zoom (meeting)
    const order = ["EmailIntegrationModule__Google", "MeetingIntegrationModule__Google", "MeetingIntegrationModule__Zoom"];
    const idxs = order.map((c) => shuffled.indexOf(`${c} } from`));
    expect(idxs[0]).toBeLessThan(idxs[1]);
    expect(idxs[1]).toBeLessThan(idxs[2]);
  });

  test("doc comment encodes the §7q3 intent: AppModule imports THIS, not <Surface>AdaptersModule", () => {
    expect(out).toContain("AppModule");
    expect(out).toContain("imports THIS (not CalendarAdaptersModule)");
    expect(out).toContain("RFC-0002 §7 q3");
    expect(out).toContain("collision-prone CalendarAdaptersModule");
    // re-export rationale: tokens available to the app
    expect(out).toContain("<ENTITY>_INTEGRATION_USE_CASE__<PROVIDER> tokens");
  });

  test("imports only @nestjs/common Module — no adapter/registry imports (off the fold graph)", () => {
    expect(out).toContain("import { Module } from '@nestjs/common';");
    expect(out).not.toContain("AdaptersModule } from");
    expect(out).not.toContain("ENTITY_SOURCES");
  });
});

describe("resolveEntityModuleImports — entity repo/module import resolution", () => {
  const base = {
    entityName: "meeting",
    entityPlural: "meetings",
    surface: "calendar",
    provider: "google",
    backendSrcAbs: "/proj/src",
  };

  test("prefers a tsconfig alias whose target dir contains the module folder", () => {
    const loc = resolveEntityModuleImports({
      ...base,
      context: null,
      aliases: { "@modules": "/proj/src/modules" },
    });
    // repo: <src>/modules/meetings/meeting.repository.ts → @modules/meetings/meeting.repository
    expect(loc.repoImportSpecifier).toBe("@modules/meetings/meeting.repository");
    expect(loc.moduleImportSpecifier).toBe("@modules/meetings/meetings.module");
    expect(loc.repoClass).toBe("MeetingRepository");
    expect(loc.moduleClass).toBe("MeetingsModule");
    expect(loc.entityClass).toBe("Meeting");
  });

  test("nests under the bounded-context segment when context is set", () => {
    const loc = resolveEntityModuleImports({
      ...base,
      context: "integration",
      aliases: { "@modules": "/proj/src/modules" },
    });
    expect(loc.repoImportSpecifier).toBe(
      "@modules/integration/meetings/meeting.repository",
    );
    expect(loc.moduleImportSpecifier).toBe(
      "@modules/integration/meetings/meetings.module",
    );
  });

  test("falls back to a correct relative path when no alias matches", () => {
    const loc = resolveEntityModuleImports({ ...base, context: null, aliases: {} });
    // from <src>/integrations/calendar/modules/google → <src>/modules/meetings/...
    expect(loc.repoImportSpecifier).toBe(
      "../../../../modules/meetings/meeting.repository",
    );
    expect(loc.moduleImportSpecifier).toBe(
      "../../../../modules/meetings/meetings.module",
    );
  });

  test("snake_case entity names pascalize correctly for class names", () => {
    const loc = resolveEntityModuleImports({
      entityName: "call_recording",
      entityPlural: "call_recordings",
      context: null,
      surface: "transcript",
      provider: "google",
      backendSrcAbs: "/proj/src",
      aliases: { "@modules": "/proj/src/modules" },
    });
    expect(loc.entityClass).toBe("CallRecording");
    expect(loc.repoClass).toBe("CallRecordingRepository");
    expect(loc.moduleClass).toBe("CallRecordingsModule");
    expect(loc.repoImportSpecifier).toBe(
      "@modules/call_recordings/call_recording.repository",
    );
  });
});
