/**
 * Barrel generator tests.
 *
 * Cover:
 *   - content shape (imports, exports array, header)
 *   - deterministic ordering (insertion order independent)
 *   - full regeneration (delete a YAML → barrel no longer references it)
 *   - architecture-specific paths (clean vs clean-lite-ps)
 *   - dry-run does not write files
 *   - configurable generated dir
 */

import { describe, test, expect, afterEach } from 'bun:test';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

import {
	regenerateBarrels,
	buildModulesBarrel,
	buildSchemaBarrel,
	resolveArchitecture,
	resolveGeneratedDir,
} from '../../cli/shared/barrel-generator.js';
import { loadContext } from '../../cli/shared/context.js';

const tempDirs: string[] = [];

function mkProject(opts: {
	entities: Array<{ name: string; plural: string; file?: string; context?: string }>;
	config?: string;
}): string {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'barrel-'));
	tempDirs.push(dir);
	fs.mkdirSync(path.join(dir, 'entities'), { recursive: true });

	for (const ent of opts.entities) {
		const filename = ent.file ?? `${ent.name}.yaml`;
		fs.writeFileSync(
			path.join(dir, 'entities', filename),
			[
				'entity:',
				`  name: ${ent.name}`,
				`  plural: ${ent.plural}`,
				`  table: ${ent.plural}`,
				// #403: `entity.context:` nests the module folder.
				...(ent.context ? [`  context: ${ent.context}`] : []),
				'fields:',
				'  id:',
				'    type: uuid',
				'    required: true',
				'  title:',
				'    type: string',
				'    required: true',
				'    max_length: 200',
				'',
			].join('\n')
		);
	}

	const config =
		opts.config ??
		['paths:', '  entities: entities', '  generated: src/generated', ''].join('\n');
	fs.writeFileSync(path.join(dir, 'codegen.config.yaml'), config);
	return dir;
}

afterEach(() => {
	for (const d of tempDirs) {
		try {
			fs.rmSync(d, { recursive: true, force: true });
		} catch {}
	}
	tempDirs.length = 0;
});

describe('buildModulesBarrel — content shape', () => {
	test('emits header + imports + GENERATED_MODULES array (clean-lite-ps)', () => {
		const entities = [
			{ name: 'account', plural: 'accounts' },
			{ name: 'contact', plural: 'contacts' },
		];
		const out = buildModulesBarrel(entities, 'src/generated/modules.ts', 'clean-lite-ps');

		expect(out).toContain('AUTO-GENERATED by @pattern-stack/codegen');
		expect(out).toContain(
			"import { AccountsModule } from '../../app/backend/src/modules/accounts/accounts.module';"
		);
		expect(out).toContain(
			"import { ContactsModule } from '../../app/backend/src/modules/contacts/contacts.module';"
		);
		expect(out).toContain('export const GENERATED_MODULES = [');
		expect(out).toContain('AccountsModule,');
		expect(out).toContain('ContactsModule,');
		expect(out).toContain('] as const;');
	});

	test('emits header + imports for clean architecture defaults', () => {
		const entities = [{ name: 'account', plural: 'accounts' }];
		const out = buildModulesBarrel(
			entities,
			'src/generated/modules.ts',
			'clean',
			'app/backend/src'
		);

		expect(out).toContain(
			"from '../../app/backend/src/infrastructure/modules/accounts.module'"
		);
		expect(out).toContain('AccountsModule');
	});

	test('empty entity list yields an empty array (not an error)', () => {
		const out = buildModulesBarrel([], 'src/generated/modules.ts', 'clean-lite-ps');
		expect(out).toContain('export const GENERATED_MODULES = [] as const;');
		expect(out).not.toContain('import {');
	});
});

describe('#403 — context: nests the module folder', () => {
	test('clean-lite-ps: context entity imports from modules/<context>/<plural>/', () => {
		const entities = [
			{ name: 'transcript', plural: 'transcripts', context: 'integration' },
			{ name: 'account', plural: 'accounts' }, // untagged → flat
		];
		const out = buildModulesBarrel(entities, 'src/generated/modules.ts', 'clean-lite-ps');

		// Context-tagged entity nests under the context segment.
		expect(out).toContain(
			"import { TranscriptsModule } from '../../app/backend/src/modules/integration/transcripts/transcripts.module';"
		);
		// Untagged entity stays flat — byte-identical to pre-#403.
		expect(out).toContain(
			"import { AccountsModule } from '../../app/backend/src/modules/accounts/accounts.module';"
		);
	});

	test('clean-lite-ps schema barrel nests the context entity too', () => {
		const entities = [
			{ name: 'transcript', plural: 'transcripts', context: 'integration' },
			{ name: 'account', plural: 'accounts' },
		];
		const out = buildSchemaBarrel(entities, 'src/generated/schema.ts', 'clean-lite-ps');

		expect(out).toContain(
			"export * from '../../app/backend/src/modules/integration/transcripts/transcript.entity';"
		);
		expect(out).toContain(
			"export * from '../../app/backend/src/modules/accounts/account.entity';"
		);
	});

	test('end-to-end: context entity YAML validates and lands under the context subfolder', async () => {
		const root = mkProject({
			entities: [
				{ name: 'transcript', plural: 'transcripts', context: 'integration' },
				{ name: 'account', plural: 'accounts' },
			],
		});
		const ctx = await loadContext({ cwd: root, skipDetection: true });

		const result = await regenerateBarrels({
			ctx,
			entitiesDir: path.join(root, 'entities'),
			generatedDir: path.join(root, 'src/generated'),
			architecture: 'clean-lite-ps',
		});

		// Both entities discovered (YAML with context: validated — schema accepts it).
		expect(result.entityCount).toBe(2);
		const modulesContent = fs.readFileSync(result.modulesBarrel, 'utf-8');
		expect(modulesContent).toContain(
			"from '../../app/backend/src/modules/integration/transcripts/transcripts.module'"
		);
		expect(modulesContent).toContain(
			"from '../../app/backend/src/modules/accounts/accounts.module'"
		);
	});
});

describe('buildSchemaBarrel — content shape', () => {
	test('re-exports every entity schema (clean-lite-ps)', () => {
		const entities = [
			{ name: 'contact', plural: 'contacts' },
			{ name: 'account', plural: 'accounts' },
		];
		const out = buildSchemaBarrel(entities, 'src/generated/schema.ts', 'clean-lite-ps');

		expect(out).toContain('AUTO-GENERATED');
		expect(out).toContain(
			"export * from '../../app/backend/src/modules/accounts/account.entity';"
		);
		expect(out).toContain(
			"export * from '../../app/backend/src/modules/contacts/contact.entity';"
		);
	});

	test('re-exports drizzle schema files for clean architecture', () => {
		const entities = [{ name: 'account', plural: 'accounts' }];
		const out = buildSchemaBarrel(
			entities,
			'src/generated/schema.ts',
			'clean',
			'app/backend/src'
		);
		expect(out).toContain(
			"export * from '../../app/backend/src/infrastructure/persistence/drizzle/accounts.schema';"
		);
	});
});

describe('regenerateBarrels — end-to-end', () => {
	test('writes both barrels with correct content', async () => {
		const root = mkProject({
			entities: [
				{ name: 'account', plural: 'accounts' },
				{ name: 'contact', plural: 'contacts' },
			],
		});
		const ctx = await loadContext({ cwd: root, skipDetection: true });

		const result = await regenerateBarrels({
			ctx,
			entitiesDir: path.join(root, 'entities'),
			generatedDir: path.join(root, 'src/generated'),
			architecture: 'clean-lite-ps',
		});

		expect(result.written).toBe(true);
		expect(result.entityCount).toBe(2);
		expect(fs.existsSync(result.modulesBarrel)).toBe(true);
		expect(fs.existsSync(result.schemaBarrel)).toBe(true);

		const modulesContent = fs.readFileSync(result.modulesBarrel, 'utf-8');
		expect(modulesContent).toContain('AccountsModule');
		expect(modulesContent).toContain('ContactsModule');

		const schemaContent = fs.readFileSync(result.schemaBarrel, 'utf-8');
		expect(schemaContent).toContain(
			"export * from '../../app/backend/src/modules/accounts/account.entity';"
		);
		expect(schemaContent).toContain(
			"export * from '../../app/backend/src/modules/contacts/contact.entity';"
		);
	});

	test('dry-run leaves filesystem untouched', async () => {
		const root = mkProject({
			entities: [{ name: 'account', plural: 'accounts' }],
		});
		const ctx = await loadContext({ cwd: root, skipDetection: true });

		const result = await regenerateBarrels({
			ctx,
			entitiesDir: path.join(root, 'entities'),
			generatedDir: path.join(root, 'src/generated'),
			architecture: 'clean-lite-ps',
			dryRun: true,
		});

		expect(result.written).toBe(false);
		expect(result.modulesContent).toContain('AccountsModule');
		expect(fs.existsSync(result.modulesBarrel)).toBe(false);
		expect(fs.existsSync(result.schemaBarrel)).toBe(false);
	});

	test('deterministic ordering regardless of filesystem enumeration', async () => {
		// Create files in reverse alphabetical order to prove we don't rely on
		// directory iteration order.
		const root = mkProject({
			entities: [
				{ name: 'zebra', plural: 'zebras', file: '1-zebra.yaml' },
				{ name: 'apple', plural: 'apples', file: '2-apple.yaml' },
				{ name: 'mango', plural: 'mangos', file: '3-mango.yaml' },
			],
		});
		const ctx = await loadContext({ cwd: root, skipDetection: true });

		const result = await regenerateBarrels({
			ctx,
			entitiesDir: path.join(root, 'entities'),
			generatedDir: path.join(root, 'src/generated'),
			architecture: 'clean-lite-ps',
		});

		const content = result.modulesContent;
		const appleIdx = content.indexOf('ApplesModule');
		const mangoIdx = content.indexOf('MangosModule');
		const zebraIdx = content.indexOf('ZebrasModule');
		// Alphabetical by singular name: apple < mango < zebra.
		expect(appleIdx).toBeGreaterThan(-1);
		expect(mangoIdx).toBeGreaterThan(appleIdx);
		expect(zebraIdx).toBeGreaterThan(mangoIdx);
	});

	test('removing a YAML removes it from barrels on next run (full regen)', async () => {
		const root = mkProject({
			entities: [
				{ name: 'account', plural: 'accounts' },
				{ name: 'contact', plural: 'contacts' },
			],
		});
		const ctx = await loadContext({ cwd: root, skipDetection: true });
		const args = {
			ctx,
			entitiesDir: path.join(root, 'entities'),
			generatedDir: path.join(root, 'src/generated'),
			architecture: 'clean-lite-ps' as const,
		};

		const first = await regenerateBarrels(args);
		expect(first.entityCount).toBe(2);
		expect(first.modulesContent).toContain('ContactsModule');

		// Remove one entity and rerun.
		fs.unlinkSync(path.join(root, 'entities', 'contact.yaml'));
		const second = await regenerateBarrels(args);
		expect(second.entityCount).toBe(1);
		expect(second.modulesContent).toContain('AccountsModule');
		expect(second.modulesContent).not.toContain('ContactsModule');

		// Written content on disk also reflects removal.
		const onDisk = fs.readFileSync(second.modulesBarrel, 'utf-8');
		expect(onDisk).not.toContain('ContactsModule');
	});
});

describe('resolver helpers', () => {
	test('resolveArchitecture reads generate.architecture', async () => {
		const root = mkProject({
			entities: [{ name: 'account', plural: 'accounts' }],
			config: [
				'paths:',
				'  entities: entities',
				'generate:',
				'  architecture: clean-lite-ps',
				'',
			].join('\n'),
		});
		const ctx = await loadContext({ cwd: root, skipDetection: true });
		expect(resolveArchitecture(ctx)).toBe('clean-lite-ps');
	});

	test('resolveArchitecture defaults to clean', async () => {
		const root = mkProject({
			entities: [{ name: 'account', plural: 'accounts' }],
			config: 'paths:\n  entities: entities\n',
		});
		const ctx = await loadContext({ cwd: root, skipDetection: true });
		expect(resolveArchitecture(ctx)).toBe('clean');
	});

	test('resolveGeneratedDir honors paths.generated', async () => {
		const root = mkProject({
			entities: [{ name: 'account', plural: 'accounts' }],
			config: [
				'paths:',
				'  entities: entities',
				'  generated: custom/out',
				'',
			].join('\n'),
		});
		const ctx = await loadContext({ cwd: root, skipDetection: true });
		expect(resolveGeneratedDir(ctx)).toBe(path.resolve(root, 'custom/out'));
	});

	test('resolveGeneratedDir defaults to src/generated', async () => {
		const root = mkProject({
			entities: [{ name: 'account', plural: 'accounts' }],
			config: 'paths:\n  entities: entities\n',
		});
		const ctx = await loadContext({ cwd: root, skipDetection: true });
		expect(resolveGeneratedDir(ctx)).toBe(path.resolve(root, 'src/generated'));
	});
});
