/**
 * Unit tests for scope-entity-type-generator.ts (JOB-7).
 *
 * Covers:
 *   - buildScopeEntityTypeContent: empty, single, multi-member cases
 *   - collectScopeableNames: fixture YAMLs, only scopeable entities returned
 *   - generateScopeEntityType: dry-run (written: false), actual write
 */

import { describe, test, expect, afterEach } from 'bun:test';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

import {
	buildScopeEntityTypeContent,
	collectScopeableNames,
	generateScopeEntityType,
} from '../../cli/shared/scope-entity-type-generator.js';

// ---------------------------------------------------------------------------
// Temp-dir helpers (mirrors barrel-generator.test.ts pattern)
// ---------------------------------------------------------------------------

const tempDirs: string[] = [];

function mkEntitiesDir(
	entities: Array<{ name: string; plural?: string; scopeable?: boolean }>,
): string {
	const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'scope-gen-'));
	tempDirs.push(dir);
	fs.mkdirSync(path.join(dir, 'entities'), { recursive: true });

	for (const ent of entities) {
		const plural = ent.plural ?? `${ent.name}s`;
		const scopeableLine =
			ent.scopeable !== undefined ? `  scopeable: ${ent.scopeable}\n` : '';
		const yaml = [
			'entity:',
			`  name: ${ent.name}`,
			`  plural: ${plural}`,
			`  table: ${plural}`,
			scopeableLine,
			'fields:',
			'  id:',
			'    type: uuid',
			'    required: true',
			'',
		].join('\n');
		fs.writeFileSync(path.join(dir, 'entities', `${ent.name}.yaml`), yaml);
	}

	return path.join(dir, 'entities');
}

afterEach(() => {
	for (const d of tempDirs) {
		try {
			fs.rmSync(d, { recursive: true, force: true });
		} catch {}
	}
	tempDirs.length = 0;
});

// ---------------------------------------------------------------------------
// buildScopeEntityTypeContent — pure function tests
// ---------------------------------------------------------------------------

describe('buildScopeEntityTypeContent — empty case', () => {
	test('generates never type with no Zod import', () => {
		const content = buildScopeEntityTypeContent([]);

		expect(content).toContain('// AUTO-GENERATED by @pattern-stack/codegen. Do not edit.');
		expect(content).toContain('// Run `codegen entity new --all` to refresh.');
		expect(content).toContain('export type ScopeEntityType = never;');
		expect(content).toContain('export const SCOPE_ENTITY_TYPES = [] as const;');
		expect(content).not.toContain("import { z } from 'zod'");
		expect(content).not.toContain('scopeEntityTypeSchema');
	});
});

describe('buildScopeEntityTypeContent — single entity', () => {
	test('generates union + tuple + Zod enum with Zod import', () => {
		const content = buildScopeEntityTypeContent(['account']);

		expect(content).toContain("import { z } from 'zod';");
		expect(content).toContain("export type ScopeEntityType = 'account';");
		expect(content).toContain("export const SCOPE_ENTITY_TYPES = ['account'] as const;");
		expect(content).toContain("export const scopeEntityTypeSchema = z.enum(['account']);");
	});
});

describe('buildScopeEntityTypeContent — multiple entities', () => {
	test('generates union, tuple, and Zod enum for multiple names', () => {
		const content = buildScopeEntityTypeContent(['account', 'opportunity']);

		expect(content).toContain("import { z } from 'zod';");
		expect(content).toContain("export type ScopeEntityType = 'account' | 'opportunity';");
		expect(content).toContain(
			"export const SCOPE_ENTITY_TYPES = ['account', 'opportunity'] as const;",
		);
		expect(content).toContain(
			"export const scopeEntityTypeSchema = z.enum(['account', 'opportunity']);",
		);
	});

	test('output is stable — names are emitted in the order provided', () => {
		// collectScopeableNames guarantees alphabetical order; this test ensures
		// the builder doesn't re-sort (it trusts the caller to pre-sort).
		const content = buildScopeEntityTypeContent(['account', 'opportunity']);
		const accountIdx = content.indexOf("'account'");
		const opportunityIdx = content.indexOf("'opportunity'");
		expect(accountIdx).toBeGreaterThan(-1);
		expect(opportunityIdx).toBeGreaterThan(accountIdx);
	});
});

// ---------------------------------------------------------------------------
// collectScopeableNames — directory walk with fixture YAMLs
// ---------------------------------------------------------------------------

describe('collectScopeableNames', () => {
	test('returns only scopeable: true entities, sorted alphabetically', () => {
		const dir = mkEntitiesDir([
			{ name: 'zebra', scopeable: true },
			{ name: 'account', scopeable: true },
			{ name: 'contact', scopeable: false },
			{ name: 'user' }, // scopeable omitted → defaults to false
		]);

		const names = collectScopeableNames(dir);
		expect(names).toEqual(['account', 'zebra']);
	});

	test('returns empty array when no entities are scopeable', () => {
		const dir = mkEntitiesDir([
			{ name: 'contact', scopeable: false },
			{ name: 'user' },
		]);

		const names = collectScopeableNames(dir);
		expect(names).toEqual([]);
	});

	test('returns empty array when directory does not exist', () => {
		const names = collectScopeableNames('/nonexistent/path/entities');
		expect(names).toEqual([]);
	});

	test('returns all entities when all are scopeable', () => {
		const dir = mkEntitiesDir([
			{ name: 'contact', scopeable: true },
			{ name: 'account', scopeable: true },
		]);

		const names = collectScopeableNames(dir);
		expect(names).toEqual(['account', 'contact']);
	});
});

// ---------------------------------------------------------------------------
// generateScopeEntityType — integration (tmpdir write + dry-run)
// ---------------------------------------------------------------------------

describe('generateScopeEntityType', () => {
	test('dry-run returns written: false with correct content, no file created', async () => {
		const entitiesDir = mkEntitiesDir([{ name: 'account', scopeable: true }]);
		const parentDir = path.dirname(entitiesDir);
		const outputPath = path.join(parentDir, 'runtime/subsystems/jobs/generated/scope-entity-type.ts');

		const result = await generateScopeEntityType({
			entitiesDir,
			outputPath,
			dryRun: true,
		});

		expect(result.written).toBe(false);
		expect(result.scopeableNames).toEqual(['account']);
		expect(result.content).toContain("export type ScopeEntityType = 'account';");
		expect(fs.existsSync(outputPath)).toBe(false);
	});

	test('writes file with correct content when not dry-run', async () => {
		const entitiesDir = mkEntitiesDir([
			{ name: 'opportunity', scopeable: true },
			{ name: 'account', scopeable: true },
			{ name: 'contact', scopeable: false },
		]);
		const parentDir = path.dirname(entitiesDir);
		const outputPath = path.join(parentDir, 'runtime/subsystems/jobs/generated/scope-entity-type.ts');

		const result = await generateScopeEntityType({
			entitiesDir,
			outputPath,
		});

		expect(result.written).toBe(true);
		expect(result.scopeableNames).toEqual(['account', 'opportunity']);
		expect(fs.existsSync(outputPath)).toBe(true);

		const onDisk = fs.readFileSync(outputPath, 'utf-8');
		expect(onDisk).toBe(result.content);
		expect(onDisk).toContain("export type ScopeEntityType = 'account' | 'opportunity';");
		expect(onDisk).not.toContain("'contact'");
	});

	test('creates nested output directories as needed', async () => {
		const entitiesDir = mkEntitiesDir([{ name: 'account', scopeable: true }]);
		const parentDir = path.dirname(entitiesDir);
		const outputPath = path.join(parentDir, 'deeply/nested/output/scope-entity-type.ts');

		const result = await generateScopeEntityType({ entitiesDir, outputPath });

		expect(result.written).toBe(true);
		expect(fs.existsSync(outputPath)).toBe(true);
	});

	test('empty scope → written never-form, no Zod import on disk', async () => {
		const entitiesDir = mkEntitiesDir([{ name: 'contact' }, { name: 'user', scopeable: false }]);
		const parentDir = path.dirname(entitiesDir);
		const outputPath = path.join(parentDir, 'runtime/subsystems/jobs/generated/scope-entity-type.ts');

		const result = await generateScopeEntityType({ entitiesDir, outputPath });

		expect(result.written).toBe(true);
		expect(result.scopeableNames).toEqual([]);
		const onDisk = fs.readFileSync(outputPath, 'utf-8');
		expect(onDisk).toContain('export type ScopeEntityType = never;');
		expect(onDisk).not.toContain("import { z }");
	});
});
