// @generated by @pattern-stack/codegen from test/fixtures/entities/user.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable } from '@nestjs/common';
import { UserService } from '../user.service';
import type { UpdateUserDto } from '../dto/update-user.dto';
import type { User } from '../user.entity';

@Injectable()
export class UpdateUserUseCase {
  constructor(private readonly service: UserService) {}

  async execute(
    id: string,
    dto: UpdateUserDto,
  ): Promise<User | null> {
    return this.service.update(id, dto);
  }
}
