// @generated by @pattern-stack/codegen from the entity set — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

/**
 * The client relation graph — the same declaration the Drizzle manifest
 * (`src/generated/relations.ts`) is built from, projected onto the browser's
 * collections (ADR-044 §5).
 *
 * Collection keys are `entity.plural`; relation keys are the YAML relationship
 * names camelCased. Both match the server manifest exactly, so one name works
 * on both sides of the wire. Nothing here is re-pluralized — every name is
 * resolved through the cross-entity registry.
 *
 * Accessors deliberately NOT emitted (the edges below are still declared):
 *   - user: sync: api — accessors compile to REL-2's allowlisted `?include=` request (FE-REL §4.3), which is not in this unit
 */
export const graph = {
	users: {
		person: { kind: 'one', target: 'persons', from: 'personId', to: 'id', optional: false },
	},
} as const;

/** The graph's type, for deriving include and result types from. */
export type Graph = typeof graph;
