#!/usr/bin/env bun
/**
 * Junction smoke test harness — end-to-end regression check for the
 * junction codegen pipeline.
 *
 * Accepts a `--scenario` flag:
 *   --scenario junction              (default) intra-domain: opportunity × contact
 *   --scenario junction-cross-domain cross-domain: opportunity × activity
 *
 * Each scenario × both architectures (clean-lite-ps by default; pass
 * --architecture clean for the second pass) = four total code paths.
 *
 * `--runtime vendored|package` (default vendored) picks the ADR-037 runtime
 * mode. `just test-smoke-junction` runs both, so the `package` default — whose
 * imports no junction gate compiled before #624 — cannot regress.
 *
 * `--layout default|custom` (default `default`, PATH-0). `custom` sets every
 * path non-default (`paths.backend_src: apps/backend/src`, `paths.generated`,
 * `paths.entities`) in a config written BEFORE `project init`, runs
 * `subsystem install events` + `jobs`, and asserts nothing lands at the default locations —
 * the #566 / #612 gate. `just test-smoke-junction` runs it in both modes.
 *
 * Bootstrap (tmp project, deps, codegen run) is delegated to
 * `test/junction/_helpers.ts` so snapshot tests can share the same path.
 * This file owns the compile + grep gate.
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { consumerErrors as scopeToConsumer } from './_consumer-errors';

import {
  bootstrapJunctionProject,
  CUSTOM_LAYOUT_APP_PATTERN,
  LAYOUT_PATHS,
  SCENARIO_META,
  VALID_ARCHITECTURES,
  VALID_LAYOUTS,
  VALID_RUNTIMES,
  VALID_SCENARIOS,
  type Architecture,
  type Layout,
  type LayoutPaths,
  type RuntimeMode,
  type Scenario,
} from '../junction/_helpers';

// ---------------------------------------------------------------------------
// Arg parsing
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Ordering contract (CGP-60)
// ---------------------------------------------------------------------------
// The junction fan-out templates inject methods + property-injection +
// imports into parent service / module files generated by the *entity*
// pipeline. The entity pipeline MUST run before the junction pipeline:
//
//   1. `codegen entity new --all` → writes parent service files with
//      `force: true`, including the `// Inherited from <ServiceBaseClass>:`
//      anchor that the junction inject templates anchor against.
//   2. `codegen junction new --all` → injects fan-out methods before the
//      anchor, idempotently (per-junction unique `// junction:<name>:<side>-fan-out`
//      marker).
//
// Running junction codegen before entity codegen surfaces a Hygen
// missing-anchor error verbatim — acceptable failure mode for end users
// (per CGP-60 spec §Risks (c)).
//
// This harness invokes the two pipelines in the correct order via steps
// 5 → 7 below. The grep assertions verify both pipelines' contributions
// to the resulting parent service files (entity-pipeline relationship
// methods + junction-pipeline fan-out methods coexist without conflict).
// ---------------------------------------------------------------------------

const argv = process.argv.slice(2);
function getArg(flag: string, fallback: string): string {
  const idx = argv.indexOf(flag);
  if (idx >= 0 && argv[idx + 1]) return argv[idx + 1];
  return fallback;
}

const scenarioArg = getArg('--scenario', 'junction') as Scenario;
if (!VALID_SCENARIOS.includes(scenarioArg)) {
  console.error(`Unknown --scenario: ${scenarioArg}. Valid: ${VALID_SCENARIOS.join(', ')}`);
  process.exit(2);
}

const architectureArg = getArg('--architecture', 'clean-lite-ps') as Architecture;
if (!VALID_ARCHITECTURES.includes(architectureArg)) {
  console.error(`Unknown --architecture: ${architectureArg}. Valid: ${VALID_ARCHITECTURES.join(', ')}`);
  process.exit(2);
}

const runtimeArg = getArg('--runtime', 'vendored') as RuntimeMode;
if (!VALID_RUNTIMES.includes(runtimeArg)) {
  console.error(`Unknown --runtime: ${runtimeArg}. Valid: ${VALID_RUNTIMES.join(', ')}`);
  process.exit(2);
}

const layoutArg = getArg('--layout', 'default') as Layout;
if (!VALID_LAYOUTS.includes(layoutArg)) {
  console.error(`Unknown --layout: ${layoutArg}. Valid: ${VALID_LAYOUTS.join(', ')}`);
  process.exit(2);
}
const P: LayoutPaths = LAYOUT_PATHS[layoutArg];

// ---------------------------------------------------------------------------
// Logging
// ---------------------------------------------------------------------------

const t0 = Date.now();
function elapsed(): string {
  const s = ((Date.now() - t0) / 1000).toFixed(1);
  return `[+${s.padStart(5)}s]`;
}
function log(msg: string): void { console.log(`${elapsed()} ${msg}`); }
function logError(msg: string): void { console.error(`${elapsed()} [FAIL] ${msg}`); }

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function runSilent(cmd: string, cwd: string): { code: number; out: string; err: string } {
  const parts = cmd.split(' ');
  const r = spawnSync(parts[0], parts.slice(1), { cwd, encoding: 'utf-8' });
  return {
    code: r.status ?? 0,
    out: r.stdout ?? '',
    err: r.stderr ?? '',
  };
}

function pascalCase(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase());
}

function camelCase(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Assertion helpers
// ---------------------------------------------------------------------------

function assertContains(haystack: string, needle: RegExp, label: string): void {
  if (!needle.test(haystack)) {
    throw new Error(
      `Smoke assertion failed [${label}]: expected to find ${needle} in generated output.\n` +
      `First 300 chars of file:\n${haystack.slice(0, 300)}`,
    );
  }
}

function assertAbsent(haystack: string, needle: RegExp, label: string): void {
  if (needle.test(haystack)) {
    throw new Error(
      `Smoke assertion failed [${label}]: expected NOT to find ${needle} in generated output.`,
    );
  }
}

function assertJunctionEmission(
  generatedSrc: string,
  scenario: Scenario,
  architecture: Architecture,
): void {
  const reads = (p: string): string => {
    const fullPath = path.join(generatedSrc, p);
    if (!fs.existsSync(fullPath)) {
      throw new Error(`Expected generated file not found: ${fullPath}`);
    }
    return fs.readFileSync(fullPath, 'utf8');
  };

  const { junctionName, leftEnt, rightEnt, hasRole } = SCENARIO_META[scenario];
  const pluralName = junctionName.endsWith('y')
    ? junctionName.slice(0, -1) + 'ies'
    : junctionName + 's';

  // Architecture-specific expected directory
  const junctionDir = architecture === 'clean-lite-ps'
    ? `${P.modules}/${pluralName}`
    : `app/backend/src/domain/${pluralName}`;

  const leftPascal = pascalCase(leftEnt);
  const rightPascal = pascalCase(rightEnt);

  // ── Entity file ──────────────────────────────────────────────────────────
  const entityFile = reads(`${junctionDir}/${junctionName}.entity.ts`);

  // Composite PK on left + right FK columns. When the junction carries a role
  // discriminator (#372), the role column joins the PK as a third member.
  assertContains(
    entityFile,
    hasRole
      ? /primaryKey\(\{\s*columns:\s*\[table\.\w+Id,\s*table\.\w+Id,\s*table\.role\]/
      : /primaryKey\(\{\s*columns:\s*\[table\.\w+Id,\s*table\.\w+Id\]/,
    'entity: composite PK',
  );

  // BaseJunctionFields: is_primary always present
  assertContains(entityFile, /is_primary|isPrimary/, 'entity: is_primary column');

  // Temporal (default: true)
  assertContains(entityFile, /started_at|startedAt/, 'entity: started_at column');
  assertContains(entityFile, /ended_at|endedAt/, 'entity: ended_at column');

  // Sourced (default: true)
  assertContains(entityFile, /sourced_from|sourcedFrom/, 'entity: sourced_from column');
  assertContains(entityFile, /confidence.*numeric|numeric.*confidence/, 'entity: confidence column');
  assertContains(entityFile, /matched_at|matchedAt/, 'entity: matched_at column');

  // DRZ-1 (#583): the v1 Drizzle `relations()` extension const is no longer
  // emitted — Drizzle 1.0 removes the v1 root export. This was a presence
  // assertion; it is inverted rather than deleted so the harness still names
  // the contract. REL-1 (#586) refills the slot with a v2 `defineRelations()`
  // manifest under ADR-044.
  assertAbsent(
    entityFile,
    new RegExp(`${camelCase(pluralName)}Relations\\s*=\\s*relations\\(`),
    'entity: no v1 relations() const (DRZ-1)',
  );
  assertAbsent(
    entityFile,
    /import\s*\{[^}]*\brelations\b[^}]*\}\s*from\s*'drizzle-orm'/,
    'entity: no drizzle-orm root `relations` import (DRZ-1)',
  );
  assertContains(
    entityFile,
    /import \{ type InferSelectModel \} from 'drizzle-orm';/,
    'entity: type-only drizzle-orm root import',
  );

  if (hasRole) {
    // Role enum declared in fixture
    assertContains(entityFile, /role.*pgEnum|pgEnum.*role/, 'entity: role pgEnum');
  }

  // ── Repository file ──────────────────────────────────────────────────────
  const repoFile = reads(
    architecture === 'clean-lite-ps'
      ? `${junctionDir}/${junctionName}.repository.ts`
      : `app/backend/src/infrastructure/persistence/drizzle/${junctionName.replace(/_/g, '-')}.repository.ts`,
  );

  // #374: junctions now extend JunctionIntegrationRepository (which extends BaseRepository)
  // to inherit the inbound-integration write surface (integrationUpsertOne/etc.).
  assertContains(repoFile, /extends JunctionIntegrationRepository</, 'repo: extends JunctionIntegrationRepository');
  assertContains(
    repoFile,
    new RegExp(`findBy${leftPascal}Id\\s*\\(`),
    'repo: findByLeftId method',
  );
  assertContains(
    repoFile,
    new RegExp(`findBy${rightPascal}Id\\s*\\(`),
    'repo: findByRightId method',
  );
  // Pagination shape { cursor?, limit? }
  assertContains(repoFile, /cursor\?:\s*string/, 'repo: cursor pagination param');
  assertContains(repoFile, /limit\?:\s*number/, 'repo: limit pagination param');

  // ── Service file ─────────────────────────────────────────────────────────
  const svcFile = reads(
    architecture === 'clean-lite-ps'
      ? `${junctionDir}/${junctionName}.service.ts`
      : `app/backend/src/application/${pluralName}/${junctionName}.service.ts`,
  );

  assertContains(svcFile, /extends WithAnalytics\(\s*BaseService</, 'service: extends WithAnalytics(BaseService<');
  assertContains(svcFile, /protected override readonly entityName/, 'service: entityName override');
  assertContains(svcFile, /@Optional\(\)\s*@Inject\(EVENT_BUS\)/, 'service: @Optional() EVENT_BUS injection');

  // ── CGP-60: junction service body emits the 4 canonical methods ─────────
  assertContains(svcFile, /async\s+attach\s*\(/, 'service: attach() method emitted');
  assertContains(svcFile, /async\s+detach\s*\(/, 'service: detach() method emitted');
  assertContains(svcFile, /async\s+listAssoc\s*\(/, 'service: listAssoc() method emitted');
  assertContains(svcFile, /async\s+setPrimary\s*\(/, 'service: setPrimary() method emitted');

  // CGP-60: list() must use two single-table queries — no Drizzle `with: {`
  assertAbsent(svcFile, /\bwith:\s*\{/, 'service: no Drizzle `with: {` in junction service');

  // CGP-60: junction service must inject left + right repos for `list`
  assertContains(
    svcFile,
    new RegExp(`private readonly \\w+Repo:\\s*${leftPascal}Repository`),
    'service: injects LeftRepository',
  );
  assertContains(
    svcFile,
    new RegExp(`private readonly \\w+Repo:\\s*${rightPascal}Repository`),
    'service: injects RightRepository',
  );

  // ── CGP-60: parent service fan-out injection (clean-lite-ps only) ───────
  if (architecture === 'clean-lite-ps') {
    const leftParentSvc = reads(`${P.modules}/${pluralize(leftEnt)}/${leftEnt}.service.ts`);
    const rightParentSvc = reads(`${P.modules}/${pluralize(rightEnt)}/${rightEnt}.service.ts`);

    // Anchor presence (Q4 anti-regression) — verifies #362's emission still
    // emits the literal `// Inherited from` comment that #60's inject
    // templates anchor against. If a future entity-template refactor
    // deletes the marker, this assertion fires before the injection silently
    // becomes a no-op.
    assertContains(leftParentSvc, /\/\/ Inherited from /, 'left parent service: anchor present');
    assertContains(rightParentSvc, /\/\/ Inherited from /, 'right parent service: anchor present');

    // Left parent — verb-flat for attach/detach, flat-noun for list/setPrimary
    assertContains(leftParentSvc, new RegExp(`attach${rightPascal}\\s*\\(`), `left parent: attach${rightPascal}`);
    assertContains(leftParentSvc, new RegExp(`detach${rightPascal}\\s*\\(`), `left parent: detach${rightPascal}`);
    assertContains(leftParentSvc, new RegExp(`${pluralize(rightEnt)}List\\s*\\(`), `left parent: ${pluralize(rightEnt)}List`);
    assertContains(leftParentSvc, new RegExp(`${pluralize(rightEnt)}SetPrimary\\s*\\(`), `left parent: ${pluralize(rightEnt)}SetPrimary`);

    // Right parent — verb-flip for addTo/removeFrom, flat-noun for list/setPrimary
    assertContains(rightParentSvc, new RegExp(`addTo${leftPascal}\\s*\\(`), `right parent: addTo${leftPascal}`);
    assertContains(rightParentSvc, new RegExp(`removeFrom${leftPascal}\\s*\\(`), `right parent: removeFrom${leftPascal}`);
    assertContains(rightParentSvc, new RegExp(`${pluralize(leftEnt)}List\\s*\\(`), `right parent: ${pluralize(leftEnt)}List`);
    assertContains(rightParentSvc, new RegExp(`${pluralize(leftEnt)}SetPrimary\\s*\\(`), `right parent: ${pluralize(leftEnt)}SetPrimary`);

    // Per-junction unique marker (Risk (a)) — prevents silent skip when a
    // second junction targets the same parent.
    assertContains(leftParentSvc, new RegExp(`junction:${junctionName}:left-fan-out`), 'left parent: per-junction marker');
    assertContains(rightParentSvc, new RegExp(`junction:${junctionName}:right-fan-out`), 'right parent: per-junction marker');

    // Coexistence: contact.service.ts (right parent in the `junction`
    // scenario) carries #358's belongs_to `account()` method AND #60's
    // junction fan-out methods. Both must be present after junction
    // codegen — the implicit coexistence test for CGP-60.
    if (scenario === 'junction' && rightEnt === 'contact') {
      assertContains(rightParentSvc, /async\s+account\s*\(/, 'right parent: #358 account() coexists');
    }
  }

  log(`assertions passed: ${scenario}/${architecture}`);
}

/**
 * #624: the junction's package-owned runtime imports follow the runtime mode —
 * `@shared/<relpath>` vendored, `@pattern-stack/codegen/runtime/<relpath>`
 * under `package`. `@shared/database/*` is consumer-local in both modes.
 */
function assertRuntimeSpecifiers(
  generatedSrc: string,
  scenario: Scenario,
  architecture: Architecture,
  runtime: RuntimeMode,
): void {
  const { junctionName } = SCENARIO_META[scenario];
  const pluralName = pluralize(junctionName);
  const files = architecture === 'clean-lite-ps'
    ? [
        `${P.modules}/${pluralName}/${junctionName}.repository.ts`,
        `${P.modules}/${pluralName}/${junctionName}.service.ts`,
      ]
    : [
        `app/backend/src/infrastructure/persistence/drizzle/${junctionName.replace(/_/g, '-')}.repository.ts`,
        `app/backend/src/application/${pluralName}/${junctionName}.service.ts`,
      ];
  const packageOwned = /'@shared\/(?:base-classes|constants|types)\//;
  const packageForm = /'@pattern-stack\/codegen\/runtime\/(?:base-classes|constants|types)\//;
  for (const rel of files) {
    const src = fs.readFileSync(path.join(generatedSrc, rel), 'utf8');
    if (runtime === 'package') {
      assertAbsent(src, packageOwned, `${rel}: no @shared/* package-owned import (package, #624)`);
      assertContains(src, packageForm, `${rel}: package-form runtime import (#624)`);
    } else {
      assertAbsent(src, packageForm, `${rel}: no package-form import (vendored)`);
      assertContains(src, packageOwned, `${rel}: @shared/* runtime import (vendored)`);
    }
  }
  log(`runtime specifier assertions passed: ${runtime}`);
}

// Naive pluralize for parent dirs (matches Hygen's pluralize for our fixtures).
function pluralize(s: string): string {
  if (s.endsWith('y')) return s.slice(0, -1) + 'ies';
  return s + 's';
}

function assertBarrelIncludes(generatedSrc: string, pluralName: string, _architecture: Architecture): void {
  const modulesBarrel = path.join(generatedSrc, P.generated, 'modules.ts');
  const schemaBarrel = path.join(generatedSrc, P.generated, 'schema.ts');

  if (!fs.existsSync(modulesBarrel)) {
    throw new Error(`modules barrel not found: ${modulesBarrel}`);
  }
  if (!fs.existsSync(schemaBarrel)) {
    throw new Error(`schema barrel not found: ${schemaBarrel}`);
  }

  const modulesContent = fs.readFileSync(modulesBarrel, 'utf8');
  const schemaContent = fs.readFileSync(schemaBarrel, 'utf8');

  const moduleClass = pascalCase(pluralName) + 'Module';
  assertContains(modulesContent, new RegExp(moduleClass), `modules barrel: includes ${moduleClass}`);
  assertContains(schemaContent, new RegExp(pluralName), `schema barrel: includes ${pluralName}`);

  log(`barrel assertions passed: ${pluralName}`);
}

/**
 * PATH-0 (#566 / #612): with every path non-default, nothing may land at a
 * default location — init, the subsystem installs, entity and junction codegen
 * all resolve from `paths.*`.
 */
function assertCustomLayout(projectDir: string): void {
  for (const stray of ['src', 'entities']) {
    if (fs.existsSync(path.join(projectDir, stray))) {
      throw new Error(`layout custom: '${stray}/' was created at the project root — a scaffold ignored paths.*`);
    }
  }
  for (const rel of [
    `${P.backendSrc}/app.module.ts`,
    `${P.backendSrc}/main.ts`,
    `${P.backendSrc}/worker.ts`,
    `${P.backendSrc}/schema.ts`,
    `${P.generated}/modules.ts`,
    `${P.generated}/subsystems.ts`,
    `${P.entities}/opportunity.yaml`,
  ]) {
    if (!fs.existsSync(path.join(projectDir, rel))) {
      throw new Error(`layout custom: expected ${rel}`);
    }
  }
  const main = fs.readFileSync(path.join(projectDir, P.backendSrc, 'main.ts'), 'utf8');
  if (!main.includes('JOBS — Embedded worker mode')) {
    throw new Error(`layout custom: the jobs main.ts hook did not land in ${P.backendSrc}/main.ts`);
  }

  // PATH-1 (#645): every clean-lite-ps module lives under `paths.modules_dir`,
  // and nothing under the default `<backend_src>/modules`.
  if (fs.existsSync(path.join(projectDir, P.backendSrc, 'modules'))) {
    throw new Error(`layout custom: '${P.backendSrc}/modules/' was created — an emitter ignored paths.modules_dir`);
  }
  const { entity, plural, mixin } = CUSTOM_LAYOUT_APP_PATTERN;
  const barrel = fs.readFileSync(path.join(projectDir, P.generated, 'modules.ts'), 'utf8');
  const fromBarrel = path.posix.relative(P.generated, P.modules);
  for (const mod of ['opportunities', 'contacts', plural]) {
    assertContains(
      barrel,
      new RegExp(`from '${fromBarrel.replace(/\./g, '\\.')}/${mod}/${mod}\\.module'`),
      `modules barrel imports ${mod} from ${P.modules}`,
    );
  }
  // PATH-1: the app pattern under `<backend_src>/patterns/` loaded through the
  // derived default glob — the ledger repository applies its mixin.
  const ledgerRepo = fs.readFileSync(path.join(projectDir, P.modules, plural, `${entity}.repository.ts`), 'utf8');
  assertContains(ledgerRepo, new RegExp(`${mixin}\\(`), `${entity} repository applies ${mixin} (app pattern loaded)`);
  assertContains(
    ledgerRepo,
    /from '@modules\/capabilities\/with-audited'/,
    `${entity} repository imports the mixin through @modules/*`,
  );
  log('layout assertions passed: custom');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<number> {
  log(`smoke-junction scenario=${scenarioArg} architecture=${architectureArg} runtime=${runtimeArg} layout=${layoutArg}`);

  let exitCode = 0;
  let result: Awaited<ReturnType<typeof bootstrapJunctionProject>> | null = null;

  try {
    result = await bootstrapJunctionProject({
      scenario: scenarioArg,
      architecture: architectureArg,
      runtime: runtimeArg,
      layout: layoutArg,
      log,
    });

    // 8. bunx tsc --noEmit --skipLibCheck
    log('running bunx tsc --noEmit --skipLibCheck');
    const tsc = runSilent('bunx tsc --noEmit --skipLibCheck', result.projectDir);
    const consumerErrors = scopeToConsumer(tsc.out + tsc.err, result.projectDir);
    if (consumerErrors.length > 0) {
      for (const line of consumerErrors) console.error(line);
      logError(`${consumerErrors.length} typecheck errors in consumer-emitted code`);
      exitCode = 1;
    } else {
      log('tsc OK');
    }

    // 9. Grep assertions on generated output
    if (exitCode === 0) {
      const { junctionName } = SCENARIO_META[scenarioArg];
      const pluralName = junctionName.endsWith('y')
        ? junctionName.slice(0, -1) + 'ies'
        : junctionName + 's';

      assertJunctionEmission(result.projectDir, scenarioArg, architectureArg);
      assertBarrelIncludes(result.projectDir, pluralName, architectureArg);
      assertRuntimeSpecifiers(result.projectDir, scenarioArg, architectureArg, runtimeArg);
      if (layoutArg === 'custom') assertCustomLayout(result.projectDir);
    }

    // 10. DI-resolution gate — boot the generated AppModule. `tsc` + grep
    // cannot catch a junction module that typechecks but fails to resolve its
    // injected parent repos at runtime (the wiring regression fixed in 0.7.8).
    // NestFactory.create + init instantiates the whole graph, so an unresolved
    // cross-module dependency throws here, not on a consumer's first boot.
    if (exitCode === 0) {
      log('booting AppModule (NestFactory DI resolution gate)');
      const boot = runSilent(
        `bun ${path.join(import.meta.dir, 'verify-boot.ts')} ${result.projectDir} ${P.backendSrc}/app.module.ts`,
        result.projectDir,
      );
      if (boot.code !== 0) {
        console.error(boot.out);
        console.error(boot.err);
        logError('AppModule boot failed — DI graph did not resolve');
        exitCode = 1;
      } else {
        log('boot OK (AppModule DI graph resolves)');
      }
    }

  } catch (err: unknown) {
    logError(err instanceof Error ? err.message : String(err));
    if (err instanceof Error && err.stack) {
      console.error(err.stack);
    }
    exitCode = 1;
  } finally {
    if (result) result.cleanup();
  }

  if (exitCode === 0) {
    log(`smoke-junction PASS (${scenarioArg}/${architectureArg}/${runtimeArg}/${layoutArg})`);
  } else {
    log(`smoke-junction FAIL (${scenarioArg}/${architectureArg}/${runtimeArg}/${layoutArg})`);
  }
  return exitCode;
}

main().then((code) => process.exit(code));
