#!/usr/bin/env bun
/**
 * Junction smoke test harness — end-to-end regression check for the
 * junction codegen pipeline.
 *
 * Accepts a `--scenario` flag:
 *   --scenario junction              (default) intra-domain: opportunity × contact
 *   --scenario junction-cross-domain cross-domain: opportunity × activity
 *
 * Each scenario × both architectures (clean-lite-ps by default; pass
 * --architecture clean for the second pass) = four total code paths.
 *
 * Bootstrap (tmp project, deps, codegen run) is delegated to
 * `test/junction/_helpers.ts` so snapshot tests can share the same path.
 * This file owns the compile + grep gate.
 */

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

import {
  bootstrapJunctionProject,
  SCENARIO_META,
  VALID_ARCHITECTURES,
  VALID_SCENARIOS,
  type Architecture,
  type Scenario,
} from '../junction/_helpers';

// ---------------------------------------------------------------------------
// Arg parsing
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Ordering contract (CGP-60)
// ---------------------------------------------------------------------------
// The junction fan-out templates inject methods + property-injection +
// imports into parent service / module files generated by the *entity*
// pipeline. The entity pipeline MUST run before the junction pipeline:
//
//   1. `codegen entity new --all` → writes parent service files with
//      `force: true`, including the `// Inherited from <ServiceBaseClass>:`
//      anchor that the junction inject templates anchor against.
//   2. `codegen junction new --all` → injects fan-out methods before the
//      anchor, idempotently (per-junction unique `// junction:<name>:<side>-fan-out`
//      marker).
//
// Running junction codegen before entity codegen surfaces a Hygen
// missing-anchor error verbatim — acceptable failure mode for end users
// (per CGP-60 spec §Risks (c)).
//
// This harness invokes the two pipelines in the correct order via steps
// 5 → 7 below. The grep assertions verify both pipelines' contributions
// to the resulting parent service files (entity-pipeline relationship
// methods + junction-pipeline fan-out methods coexist without conflict).
// ---------------------------------------------------------------------------

const argv = process.argv.slice(2);
function getArg(flag: string, fallback: string): string {
  const idx = argv.indexOf(flag);
  if (idx >= 0 && argv[idx + 1]) return argv[idx + 1];
  return fallback;
}

const scenarioArg = getArg('--scenario', 'junction') as Scenario;
if (!VALID_SCENARIOS.includes(scenarioArg)) {
  console.error(`Unknown --scenario: ${scenarioArg}. Valid: ${VALID_SCENARIOS.join(', ')}`);
  process.exit(2);
}

const architectureArg = getArg('--architecture', 'clean-lite-ps') as Architecture;
if (!VALID_ARCHITECTURES.includes(architectureArg)) {
  console.error(`Unknown --architecture: ${architectureArg}. Valid: ${VALID_ARCHITECTURES.join(', ')}`);
  process.exit(2);
}

// ---------------------------------------------------------------------------
// Logging
// ---------------------------------------------------------------------------

const t0 = Date.now();
function elapsed(): string {
  const s = ((Date.now() - t0) / 1000).toFixed(1);
  return `[+${s.padStart(5)}s]`;
}
function log(msg: string): void { console.log(`${elapsed()} ${msg}`); }
function logError(msg: string): void { console.error(`${elapsed()} [FAIL] ${msg}`); }

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function runSilent(cmd: string, cwd: string): { code: number; out: string; err: string } {
  const parts = cmd.split(' ');
  const r = spawnSync(parts[0], parts.slice(1), { cwd, encoding: 'utf-8' });
  return {
    code: r.status ?? 0,
    out: r.stdout ?? '',
    err: r.stderr ?? '',
  };
}

function filterConsumerErrors(output: string): string[] {
  const lines = output.split('\n').filter((l) => l.trim());
  const errors: string[] = [];
  for (const line of lines) {
    if (line.includes('../') || line.includes('/codegen-patterns/runtime/')) continue;
    if (line.includes('node_modules/')) continue;
    if (line.includes('TS5101')) continue;
    if (!/error TS\d+:/.test(line)) continue;
    if (/\.schema\.ts\(\d+,\d+\): error/.test(line)) continue;
    if (line.includes("Property 'table' in type") && line.includes('not assignable')) continue;
    if (line.includes("Cannot assign an abstract constructor")) continue;
    if (/Argument of type .* is not assignable to parameter of type 'Constructor<\{\}>'/.test(line)) continue;
    if (/Property '(findBy[A-Z]\w*|findById|findAll|list|findWithDeleted|findOnlyDeleted)'/.test(line)) continue;
    if (line.includes("'@pattern-stack/codegen/")) continue;
    errors.push(line);
  }
  return errors;
}

function pascalCase(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase())
    .replace(/^./, (c) => c.toUpperCase());
}

function camelCase(s: string): string {
  return s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());
}

// ---------------------------------------------------------------------------
// Assertion helpers
// ---------------------------------------------------------------------------

function assertContains(haystack: string, needle: RegExp, label: string): void {
  if (!needle.test(haystack)) {
    throw new Error(
      `Smoke assertion failed [${label}]: expected to find ${needle} in generated output.\n` +
      `First 300 chars of file:\n${haystack.slice(0, 300)}`,
    );
  }
}

function assertAbsent(haystack: string, needle: RegExp, label: string): void {
  if (needle.test(haystack)) {
    throw new Error(
      `Smoke assertion failed [${label}]: expected NOT to find ${needle} in generated output. ` +
      `This leaf must not emit fan-out association methods — they land via #60.`,
    );
  }
}

function assertJunctionEmission(
  generatedSrc: string,
  scenario: Scenario,
  architecture: Architecture,
): void {
  const reads = (p: string): string => {
    const fullPath = path.join(generatedSrc, p);
    if (!fs.existsSync(fullPath)) {
      throw new Error(`Expected generated file not found: ${fullPath}`);
    }
    return fs.readFileSync(fullPath, 'utf8');
  };

  const { junctionName, leftEnt, rightEnt, hasRole } = SCENARIO_META[scenario];
  const pluralName = junctionName.endsWith('y')
    ? junctionName.slice(0, -1) + 'ies'
    : junctionName + 's';

  // Architecture-specific expected directory
  const junctionDir = architecture === 'clean-lite-ps'
    ? `src/modules/${pluralName}`
    : `app/backend/src/domain/${pluralName}`;

  const leftPascal = pascalCase(leftEnt);
  const rightPascal = pascalCase(rightEnt);

  // ── Entity file ──────────────────────────────────────────────────────────
  const entityFile = reads(`${junctionDir}/${junctionName}.entity.ts`);

  // Composite PK on left + right FK columns. When the junction carries a role
  // discriminator (#372), the role column joins the PK as a third member.
  assertContains(
    entityFile,
    hasRole
      ? /primaryKey\(\{\s*columns:\s*\[table\.\w+Id,\s*table\.\w+Id,\s*table\.role\]/
      : /primaryKey\(\{\s*columns:\s*\[table\.\w+Id,\s*table\.\w+Id\]/,
    'entity: composite PK',
  );

  // BaseJunctionFields: is_primary always present
  assertContains(entityFile, /is_primary|isPrimary/, 'entity: is_primary column');

  // Temporal (default: true)
  assertContains(entityFile, /started_at|startedAt/, 'entity: started_at column');
  assertContains(entityFile, /ended_at|endedAt/, 'entity: ended_at column');

  // Sourced (default: true)
  assertContains(entityFile, /sourced_from|sourcedFrom/, 'entity: sourced_from column');
  assertContains(entityFile, /confidence.*numeric|numeric.*confidence/, 'entity: confidence column');
  assertContains(entityFile, /matched_at|matchedAt/, 'entity: matched_at column');

  // relations() extension const
  assertContains(
    entityFile,
    new RegExp(`${camelCase(pluralName)}Relations\\s*=\\s*relations\\(${camelCase(pluralName)}`),
    'entity: relations() extension const',
  );

  if (hasRole) {
    // Role enum declared in fixture
    assertContains(entityFile, /role.*pgEnum|pgEnum.*role/, 'entity: role pgEnum');
  }

  // ── Repository file ──────────────────────────────────────────────────────
  const repoFile = reads(
    architecture === 'clean-lite-ps'
      ? `${junctionDir}/${junctionName}.repository.ts`
      : `app/backend/src/infrastructure/persistence/drizzle/${junctionName.replace(/_/g, '-')}.repository.ts`,
  );

  assertContains(repoFile, /extends BaseRepository<\w+>/, 'repo: extends BaseRepository');
  assertContains(
    repoFile,
    new RegExp(`findBy${leftPascal}Id\\s*\\(`),
    'repo: findByLeftId method',
  );
  assertContains(
    repoFile,
    new RegExp(`findBy${rightPascal}Id\\s*\\(`),
    'repo: findByRightId method',
  );
  // Pagination shape { cursor?, limit? }
  assertContains(repoFile, /cursor\?:\s*string/, 'repo: cursor pagination param');
  assertContains(repoFile, /limit\?:\s*number/, 'repo: limit pagination param');

  // ── Service file ─────────────────────────────────────────────────────────
  const svcFile = reads(
    architecture === 'clean-lite-ps'
      ? `${junctionDir}/${junctionName}.service.ts`
      : `app/backend/src/application/${pluralName}/${junctionName}.service.ts`,
  );

  assertContains(svcFile, /extends WithAnalytics\(\s*BaseService</, 'service: extends WithAnalytics(BaseService<');
  assertContains(svcFile, /protected override readonly entityName/, 'service: entityName override');
  assertContains(svcFile, /@Optional\(\)\s*@Inject\(EVENT_BUS\)/, 'service: @Optional() EVENT_BUS injection');

  // ── CGP-60: junction service body emits the 4 canonical methods ─────────
  assertContains(svcFile, /async\s+attach\s*\(/, 'service: attach() method emitted');
  assertContains(svcFile, /async\s+detach\s*\(/, 'service: detach() method emitted');
  assertContains(svcFile, /async\s+listAssoc\s*\(/, 'service: listAssoc() method emitted');
  assertContains(svcFile, /async\s+setPrimary\s*\(/, 'service: setPrimary() method emitted');

  // CGP-60: list() must use two single-table queries — no Drizzle `with: {`
  assertAbsent(svcFile, /\bwith:\s*\{/, 'service: no Drizzle `with: {` in junction service');

  // CGP-60: junction service must inject left + right repos for `list`
  assertContains(
    svcFile,
    new RegExp(`private readonly \\w+Repo:\\s*${leftPascal}Repository`),
    'service: injects LeftRepository',
  );
  assertContains(
    svcFile,
    new RegExp(`private readonly \\w+Repo:\\s*${rightPascal}Repository`),
    'service: injects RightRepository',
  );

  // ── CGP-60: parent service fan-out injection (clean-lite-ps only) ───────
  if (architecture === 'clean-lite-ps') {
    const leftParentSvc = reads(`src/modules/${pluralize(leftEnt)}/${leftEnt}.service.ts`);
    const rightParentSvc = reads(`src/modules/${pluralize(rightEnt)}/${rightEnt}.service.ts`);

    // Anchor presence (Q4 anti-regression) — verifies #362's emission still
    // emits the literal `// Inherited from` comment that #60's inject
    // templates anchor against. If a future entity-template refactor
    // deletes the marker, this assertion fires before the injection silently
    // becomes a no-op.
    assertContains(leftParentSvc, /\/\/ Inherited from /, 'left parent service: anchor present');
    assertContains(rightParentSvc, /\/\/ Inherited from /, 'right parent service: anchor present');

    // Left parent — verb-flat for attach/detach, flat-noun for list/setPrimary
    assertContains(leftParentSvc, new RegExp(`attach${rightPascal}\\s*\\(`), `left parent: attach${rightPascal}`);
    assertContains(leftParentSvc, new RegExp(`detach${rightPascal}\\s*\\(`), `left parent: detach${rightPascal}`);
    assertContains(leftParentSvc, new RegExp(`${pluralize(rightEnt)}List\\s*\\(`), `left parent: ${pluralize(rightEnt)}List`);
    assertContains(leftParentSvc, new RegExp(`${pluralize(rightEnt)}SetPrimary\\s*\\(`), `left parent: ${pluralize(rightEnt)}SetPrimary`);

    // Right parent — verb-flip for addTo/removeFrom, flat-noun for list/setPrimary
    assertContains(rightParentSvc, new RegExp(`addTo${leftPascal}\\s*\\(`), `right parent: addTo${leftPascal}`);
    assertContains(rightParentSvc, new RegExp(`removeFrom${leftPascal}\\s*\\(`), `right parent: removeFrom${leftPascal}`);
    assertContains(rightParentSvc, new RegExp(`${pluralize(leftEnt)}List\\s*\\(`), `right parent: ${pluralize(leftEnt)}List`);
    assertContains(rightParentSvc, new RegExp(`${pluralize(leftEnt)}SetPrimary\\s*\\(`), `right parent: ${pluralize(leftEnt)}SetPrimary`);

    // Per-junction unique marker (Risk (a)) — prevents silent skip when a
    // second junction targets the same parent.
    assertContains(leftParentSvc, new RegExp(`junction:${junctionName}:left-fan-out`), 'left parent: per-junction marker');
    assertContains(rightParentSvc, new RegExp(`junction:${junctionName}:right-fan-out`), 'right parent: per-junction marker');

    // Coexistence: contact.service.ts (right parent in the `junction`
    // scenario) carries #358's belongs_to `account()` method AND #60's
    // junction fan-out methods. Both must be present after junction
    // codegen — the implicit coexistence test for CGP-60.
    if (scenario === 'junction' && rightEnt === 'contact') {
      assertContains(rightParentSvc, /async\s+account\s*\(/, 'right parent: #358 account() coexists');
    }
  }

  log(`assertions passed: ${scenario}/${architecture}`);
}

// Naive pluralize for parent dirs (matches Hygen's pluralize for our fixtures).
function pluralize(s: string): string {
  if (s.endsWith('y')) return s.slice(0, -1) + 'ies';
  return s + 's';
}

function assertBarrelIncludes(generatedSrc: string, pluralName: string, _architecture: Architecture): void {
  const modulesBarrel = path.join(generatedSrc, 'src/generated/modules.ts');
  const schemaBarrel = path.join(generatedSrc, 'src/generated/schema.ts');

  if (!fs.existsSync(modulesBarrel)) {
    throw new Error(`modules barrel not found: ${modulesBarrel}`);
  }
  if (!fs.existsSync(schemaBarrel)) {
    throw new Error(`schema barrel not found: ${schemaBarrel}`);
  }

  const modulesContent = fs.readFileSync(modulesBarrel, 'utf8');
  const schemaContent = fs.readFileSync(schemaBarrel, 'utf8');

  const moduleClass = pascalCase(pluralName) + 'Module';
  assertContains(modulesContent, new RegExp(moduleClass), `modules barrel: includes ${moduleClass}`);
  assertContains(schemaContent, new RegExp(pluralName), `schema barrel: includes ${pluralName}`);

  log(`barrel assertions passed: ${pluralName}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<number> {
  log(`smoke-junction scenario=${scenarioArg} architecture=${architectureArg}`);

  let exitCode = 0;
  let result: Awaited<ReturnType<typeof bootstrapJunctionProject>> | null = null;

  try {
    result = await bootstrapJunctionProject({
      scenario: scenarioArg,
      architecture: architectureArg,
      log,
    });

    // 8. bunx tsc --noEmit --skipLibCheck
    log('running bunx tsc --noEmit --skipLibCheck');
    const tsc = runSilent('bunx tsc --noEmit --skipLibCheck', result.projectDir);
    const consumerErrors = filterConsumerErrors(tsc.out + tsc.err);
    if (consumerErrors.length > 0) {
      for (const line of consumerErrors) console.error(line);
      logError(`${consumerErrors.length} typecheck errors in consumer-emitted code`);
      exitCode = 1;
    } else {
      log('tsc OK');
    }

    // 9. Grep assertions on generated output
    if (exitCode === 0) {
      const { junctionName } = SCENARIO_META[scenarioArg];
      const pluralName = junctionName.endsWith('y')
        ? junctionName.slice(0, -1) + 'ies'
        : junctionName + 's';

      assertJunctionEmission(result.projectDir, scenarioArg, architectureArg);
      assertBarrelIncludes(result.projectDir, pluralName, architectureArg);
    }

  } catch (err: unknown) {
    logError(err instanceof Error ? err.message : String(err));
    if (err instanceof Error && err.stack) {
      console.error(err.stack);
    }
    exitCode = 1;
  } finally {
    if (result) result.cleanup();
  }

  if (exitCode === 0) {
    log(`smoke-junction PASS (${scenarioArg}/${architectureArg})`);
  } else {
    log(`smoke-junction FAIL (${scenarioArg}/${architectureArg})`);
  }
  return exitCode;
}

main().then((code) => process.exit(code));
