/**
 * DealStates Controller
 * Generated by entity codegen - do not edit directly
 */

import {
	Body,
	Controller,
	Delete,
	Get,
	Headers,
	Param,
	ParseUUIDPipe,
	Post,
	Put,
	Query,
	UsePipes,
} from '@nestjs/common';
import { GetDealStateByIdQuery } from '../../application/queries/deal_state/get-by-id.query';
import { ListDealStatesQuery } from '../../application/queries/deal_state/list.query';
import {
	type CreateDealStateDto,
	createDealStateSchema,
	type UpdateDealStateDto,
	updateDealStateSchema,
} from '../../application/schemas';
import { CreateDealStateCommand } from '../../application/commands/deal_state/create.command';
import { DeleteDealStateCommand } from '../../application/commands/deal_state/delete.command';
import { UpdateDealStateCommand } from '../../application/commands/deal_state/update.command';
import { ZodValidationPipe } from '../../core/pipes/zod-validation.pipe';
import { DealState } from '../../domain';
import type { DealStateWith } from '../../domain';

@Controller('deal_states')
export class DealStatesController {
	constructor(
		private readonly getDealStateByIdQuery: GetDealStateByIdQuery,
		private readonly listDealStatesQuery: ListDealStatesQuery,
		private readonly createDealStateCommand: CreateDealStateCommand,
		private readonly updateDealStateCommand: UpdateDealStateCommand,
		private readonly deleteDealStateCommand: DeleteDealStateCommand,
	) {}

	@Get()
	async findAll(@Query('include') include?: string): Promise<DealState[]> {
		return this.listDealStatesQuery.execute(this.parseInclude(include));
	}

	@Get(':id')
	async findById(
		@Param('id', ParseUUIDPipe) id: string,
		@Query('include') include?: string,
	): Promise<DealState> {
		return this.getDealStateByIdQuery.execute(id, this.parseInclude(include));
	}

	@Post()
	@UsePipes(new ZodValidationPipe(createDealStateSchema))
	async create(
		@Body() dto: CreateDealStateDto,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<DealState> {
		return this.createDealStateCommand.execute(dto, { actor: { tenantId, userId } });
	}

	@Put(':id')
	async update(
		@Param('id', ParseUUIDPipe) id: string,
		@Body(new ZodValidationPipe(updateDealStateSchema)) dto: UpdateDealStateDto,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<DealState> {
		return this.updateDealStateCommand.execute(id, dto, { actor: { tenantId, userId } });
	}

	@Delete(':id')
	async delete(
		@Param('id', ParseUUIDPipe) id: string,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<DealState> {
		return this.deleteDealStateCommand.execute(id, { actor: { tenantId, userId } });
	}

	/**
	 * Parse comma-separated include query param into typed options.
	 * Example: ?include=account,owner → { account: true, owner: true }
	 */
	private parseInclude(include?: string): DealStateWith | undefined {
		if (!include) return undefined;
		const parts = include.split(',').map((s) => s.trim());
		return {
			opportunities: parts.includes('opportunities'),
		};
	}
}
