// @generated by @pattern-stack/codegen from test/fixtures/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * DealStates Controller
 * Generated by entity codegen - do not edit directly
 */

import {
	Body,
	Controller,
	Delete,
	Get,
	Headers,
	Param,
	ParseUUIDPipe,
	Post,
	Put,
	UsePipes,
} from '@nestjs/common';
import {
	ApiBearerAuth,
	ApiBody,
	ApiOperation,
	ApiParam,
	ApiResponse,
} from '@nestjs/swagger';
import { GetDealStateByIdQuery } from '../../application/queries/deal_state/get-by-id.query';
import { ListDealStatesQuery } from '../../application/queries/deal_state/list.query';
import {
	type CreateDealStateDto,
	createDealStateSchema,
	type UpdateDealStateDto,
	updateDealStateSchema,
} from '../../application/schemas';
import { CreateDealStateCommand } from '../../application/commands/deal_state/create.command';
import { DeleteDealStateCommand } from '../../application/commands/deal_state/delete.command';
import { UpdateDealStateCommand } from '../../application/commands/deal_state/update.command';
import { ZodValidationPipe } from '../../core/pipes/zod-validation.pipe';
import { DealState } from '../../domain';

// OPENAPI-3: controller decorators reference schemas by `$ref` rather
// than `type:` class references because generated DTOs are Zod-derived
// types (not NestJS classes). Schemas are registered by name in the
// `OpenApiRegistry` at onModuleInit (OPENAPI-2); these `$ref` URIs point
// at those registered entries. `ErrorResponseDto` is auto-registered by
// the shared registry.
@ApiBearerAuth()
@Controller('deal_states')
export class DealStatesController {
	constructor(
		private readonly getDealStateByIdQuery: GetDealStateByIdQuery,
		private readonly listDealStatesQuery: ListDealStatesQuery,
		private readonly createDealStateCommand: CreateDealStateCommand,
		private readonly updateDealStateCommand: UpdateDealStateCommand,
		private readonly deleteDealStateCommand: DeleteDealStateCommand,
	) {}

	@ApiOperation({ summary: 'List deal_states', operationId: 'listDealStates' })
	@ApiResponse({
		status: 200,
		schema: { type: 'array', items: { $ref: '#/components/schemas/DealStateResponseDto' } },
	})
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@Get()
	async findAll(): Promise<DealState[]> {
		return this.listDealStatesQuery.execute();
	}

	@ApiOperation({ summary: 'Find deal_state by id', operationId: 'findDealStateById' })
	@ApiResponse({ status: 200, schema: { $ref: '#/components/schemas/DealStateResponseDto' } })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiParam({ name: 'id', type: 'string', format: 'uuid' })
	@Get(':id')
	async findById(
		@Param('id', ParseUUIDPipe) id: string,
	): Promise<DealState> {
		return this.getDealStateByIdQuery.execute(id);
	}

	@ApiOperation({ summary: 'Create deal_state', operationId: 'createDealState' })
	@ApiBody({ schema: { $ref: '#/components/schemas/CreateDealStateDto' } })
	@ApiResponse({ status: 201, schema: { $ref: '#/components/schemas/DealStateResponseDto' } })
	@ApiResponse({ status: 400, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@Post()
	@UsePipes(new ZodValidationPipe(createDealStateSchema))
	async create(
		@Body() dto: CreateDealStateDto,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<DealState> {
		return this.createDealStateCommand.execute(dto, { actor: { tenantId, userId } });
	}

	@ApiOperation({ summary: 'Update deal_state', operationId: 'updateDealState' })
	@ApiBody({ schema: { $ref: '#/components/schemas/UpdateDealStateDto' } })
	@ApiResponse({ status: 200, schema: { $ref: '#/components/schemas/DealStateResponseDto' } })
	@ApiResponse({ status: 400, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiParam({ name: 'id', type: 'string', format: 'uuid' })
	@Put(':id')
	async update(
		@Param('id', ParseUUIDPipe) id: string,
		@Body(new ZodValidationPipe(updateDealStateSchema)) dto: UpdateDealStateDto,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<DealState> {
		return this.updateDealStateCommand.execute(id, dto, { actor: { tenantId, userId } });
	}

	@ApiOperation({ summary: 'Delete deal_state', operationId: 'deleteDealState' })
	@ApiResponse({ status: 204 })
	@ApiResponse({ status: 401, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiResponse({ status: 404, schema: { $ref: '#/components/schemas/ErrorResponseDto' } })
	@ApiParam({ name: 'id', type: 'string', format: 'uuid' })
	@Delete(':id')
	async delete(
		@Param('id', ParseUUIDPipe) id: string,
		@Headers('x-tenant-id') tenantId?: string,
		@Headers('x-user-id') userId?: string,
	): Promise<DealState> {
		return this.deleteDealStateCommand.execute(id, { actor: { tenantId, userId } });
	}
}

