/**
 * Users Controller
 * Generated by entity codegen - do not edit directly
 */

import {
	Body,
	Controller,
	Delete,
	Get,
	Param,
	ParseUUIDPipe,
	Post,
	Put,
	Query,
	UsePipes,
} from '@nestjs/common';
import { GetUserByIdQuery } from '../../application/queries/user/get-by-id.query';
import { ListUsersQuery } from '../../application/queries/user/list.query';
import {
	type CreateUserDto,
	createUserSchema,
	type UpdateUserDto,
	updateUserSchema,
} from '../../application/schemas';
import { CreateUserCommand } from '../../application/commands/user/create.command';
import { DeleteUserCommand } from '../../application/commands/user/delete.command';
import { UpdateUserCommand } from '../../application/commands/user/update.command';
import { ZodValidationPipe } from '../../core/pipes/zod-validation.pipe';
import { User } from '../../domain';
import type { UserWith } from '../../domain';

@Controller('users')
export class UsersController {
	constructor(
		private readonly getUserByIdQuery: GetUserByIdQuery,
		private readonly listUsersQuery: ListUsersQuery,
		private readonly createUserCommand: CreateUserCommand,
		private readonly updateUserCommand: UpdateUserCommand,
		private readonly deleteUserCommand: DeleteUserCommand,
	) {}

	@Get()
	async findAll(@Query('include') include?: string): Promise<User[]> {
		return this.listUsersQuery.execute(this.parseInclude(include));
	}

	@Get(':id')
	async findById(
		@Param('id', ParseUUIDPipe) id: string,
		@Query('include') include?: string,
	): Promise<User> {
		return this.getUserByIdQuery.execute(id, this.parseInclude(include));
	}

	@Post()
	@UsePipes(new ZodValidationPipe(createUserSchema))
	async create(@Body() dto: CreateUserDto): Promise<User> {
		return this.createUserCommand.execute(dto);
	}

	@Put(':id')
	async update(
		@Param('id', ParseUUIDPipe) id: string,
		@Body(new ZodValidationPipe(updateUserSchema)) dto: UpdateUserDto,
	): Promise<User> {
		return this.updateUserCommand.execute(id, dto);
	}

	@Delete(':id')
	async delete(@Param('id', ParseUUIDPipe) id: string): Promise<User> {
		return this.deleteUserCommand.execute(id);
	}

	/**
	 * Parse comma-separated include query param into typed options.
	 * Example: ?include=account,owner → { account: true, owner: true }
	 */
	private parseInclude(include?: string): UserWith | undefined {
		if (!include) return undefined;
		const parts = include.split(',').map((s) => s.trim());
		return {
			person: parts.includes('person'),
			owned_opportunities: parts.includes('owned_opportunities'),
		};
	}
}
