/**
 * Frontend emitter — banner + file-writing helpers (ADR-038, FE-2).
 *
 * The banner mirrors the house `generatedBanner()` in
 * `src/cli/shared/adapter-emission-generator.ts` — the shape is copied here so
 * the emitter has no dependency on `src/cli/**` (emitters must not import across
 * from the CLI layer).
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

/**
 * House `@generated` banner. `sourceDesc` describes the input the file was
 * rendered from (e.g. `entities/opportunity.yaml`, `the entity set`).
 */
export function generatedBanner(sourceDesc: string): string {
	return (
		`// @generated by @pattern-stack/codegen from ${sourceDesc} — DO NOT EDIT.\n` +
		'// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.'
	);
}

/**
 * Prefix a file body with the banner and a single blank line. Pure — used by
 * every builder so the banner convention lives in exactly one place.
 */
export function withBanner(sourceDesc: string, body: string): string {
	return `${generatedBanner(sourceDesc)}\n\n${body}`;
}

/**
 * Write a file, creating parent directories. Thin wrapper over fs so the emit
 * steps stay declarative (build string → write).
 */
export function writeFile(outPath: string, content: string): void {
	mkdirSync(dirname(outPath), { recursive: true });
	writeFileSync(outPath, content);
}
