// AUTO-GENERATED by @pattern-stack/codegen. Do not edit.
// See ADR-032 — Orchestration Patterns.

import type { Provider } from '@nestjs/common';
import type { IAuthStrategy } from '@/integrations/ports/auth-strategy.port';
import type { ICrmPort } from '@/integrations/ports/crm.port';
import type { CrmAdapterDomain } from '@/modules/crm/constants/adapter-domains';
import { HubSpotAuthStrategy } from '@/integrations/hubspot/hubspot-auth.strategy';
import { HubSpotCrmAdapter } from '@/integrations/hubspot/hubspot-crm.adapter';
import { SalesforceAuthStrategy } from '@/integrations/salesforce/salesforce-auth.strategy';
import { SalesforceCrmAdapter } from '@/integrations/salesforce/salesforce-crm.adapter';
import { CRM_PORTS_AUTH_REGISTRY, CRM_PORTS_REGISTRY, type CrmPortsAuthRegistryMap, type CrmPortsRegistryMap } from './tokens.js';
import type { CrmPortsForRootOptions } from './module.js';

export function buildCrmPortsRegistryProviders(opts?: CrmPortsForRootOptions): Provider[] {
	return [
		{
			provide: CRM_PORTS_REGISTRY,
			useFactory: (salesforceCrmAdapter_0: SalesforceCrmAdapter, hubSpotCrmAdapter_1: HubSpotCrmAdapter) => {
				const base: CrmPortsRegistryMap = new Map<CrmAdapterDomain, ICrmPort>([
					['salesforce-crm' as CrmAdapterDomain, salesforceCrmAdapter_0],
					['hubspot-crm' as CrmAdapterDomain, hubSpotCrmAdapter_1],
				]);
				if (opts?.overrides) {
					for (const [k, v] of Object.entries(opts.overrides)) {
						if (v !== undefined) base.set(k as CrmAdapterDomain, v as ICrmPort);
					}
				}
				return base as CrmPortsRegistryMap;
			},
			inject: [SalesforceCrmAdapter, HubSpotCrmAdapter],
		},
		{
			provide: CRM_PORTS_AUTH_REGISTRY,
			useFactory: (salesforceAuthStrategy_0: SalesforceAuthStrategy, hubSpotAuthStrategy_1: HubSpotAuthStrategy) => {
				const base: CrmPortsAuthRegistryMap = new Map<CrmAdapterDomain, IAuthStrategy>([
					['salesforce-crm' as CrmAdapterDomain, salesforceAuthStrategy_0],
					['hubspot-crm' as CrmAdapterDomain, hubSpotAuthStrategy_1],
				]);
				if (opts?.authOverrides) {
					for (const [k, v] of Object.entries(opts.authOverrides)) {
						if (v !== undefined) base.set(k as CrmAdapterDomain, v as IAuthStrategy);
					}
				}
				return base as CrmPortsAuthRegistryMap;
			},
			inject: [SalesforceAuthStrategy, HubSpotAuthStrategy],
		},
	];
}
