// @generated by @pattern-stack/codegen from test/fixtures/contact-v2.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Contact Domain Barrel Export
 * Generated by entity codegen - do not edit directly
 *
 * This barrel file exports the entity and repository interface
 * when using separate file layout (file_grouping: "separate")
 */

export * from './contact.entity';
export * from './contact.repository.interface';
