---
to: <%= outputPaths.entity %>
skip_if: <%= !isCleanArchitecture %>
force: true
---
<%- typeof generatedBanner !== 'undefined' ? generatedBanner : '' %>
<% if (outputPaths.entity) { -%>
/**
 * <%= className %> Domain Entity
 * Generated by entity codegen - do not edit directly
 *
 * NOTE: Related entity imports assume a nested folder structure where each entity
 * lives in its own folder (e.g., domain/{entity}/{entity}.entity.ts). This follows
 * CLEAN architecture conventions where each aggregate root has its own bounded context.
 * All entities should follow this structure for consistent imports.
 */
<% if (hasEntityRefFields) { -%>
import type { EntityType } from '<%= locations.dbSchemaServer.import %>';
<% } -%>

export class <%= className %> {
	constructor(
		public readonly id: string,
<% fields.forEach((field) => { -%>
		public readonly <%= field.camelName %>: <%- field.tsType %><%= field.nullable ? ' | null' : '' %>,
<% }) -%>
<% if (hasTimestamps) { -%>
		public readonly createdAt: Date,
		public readonly updatedAt: Date,
<% } -%>
<% if (hasSoftDelete) { -%>
		public readonly deletedAt: Date | null,
<% } -%>
<% if (hasTemporalValidity) { -%>
		public readonly validFrom: Date | null,
		public readonly validTo: Date | null,
		public readonly isActive: boolean,
<% } -%>
	) {}

	static fromRecord(
		// biome-ignore lint/suspicious/noExplicitAny: Drizzle records have dynamic shape
		record: Record<string, any>,
	): <%= className %> {
		return new <%= className %>(
			record.id,
<% fields.forEach((field) => { -%>
			record.<%= field.camelName %>,
<% }) -%>
<% if (hasTimestamps) { -%>
			record.createdAt,
			record.updatedAt,
<% } -%>
<% if (hasSoftDelete) { -%>
			record.deletedAt,
<% } -%>
<% if (hasTemporalValidity) { -%>
			record.validFrom,
			record.validTo,
			record.isActive,
<% } -%>
		);
	}
}
<% } -%>
