/**
 * Deal DTOs
 * Generated by entity codegen - do not edit directly
 */

import { z } from 'zod';

export const createDealSchema = z.object({
	name: z.string().max(255),
	amount: z.coerce.string().nullable().optional(),
	stage: z.enum(['prospecting', 'qualification', 'proposal', 'negotiation', 'closed_won', 'closed_lost']),
	ownerId: z.string().uuid(),
	accountId: z.string().uuid(),
	closeDate: z.coerce.date().nullable().optional(),
	probability: z.number().int().nullable().optional(),
});

export type CreateDealDto = z.infer<typeof createDealSchema>;

export const updateDealSchema = z.object({
	name: z.string().max(255).optional(),
	amount: z.coerce.string().nullable().optional(),
	stage: z.enum(['prospecting', 'qualification', 'proposal', 'negotiation', 'closed_won', 'closed_lost']).optional(),
	ownerId: z.string().uuid().optional(),
	accountId: z.string().uuid().optional(),
	closeDate: z.coerce.date().nullable().optional(),
	probability: z.number().int().nullable().optional(),
});

export type UpdateDealDto = z.infer<typeof updateDealSchema>;
