// @generated by @pattern-stack/codegen from test/fixtures/organization.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Organization DTOs
 * Generated by entity codegen - do not edit directly
 */

import { z } from 'zod';

export const createOrganizationSchema = z.object({
	tenantId: z.string().uuid(),
	name: z.string().max(255),
	domain: z.string().max(255).nullable().optional(),
	parentId: z.string().uuid().nullable().optional(),
});

export type CreateOrganizationDto = z.infer<typeof createOrganizationSchema>;

export const updateOrganizationSchema = z.object({
	tenantId: z.string().uuid().optional(),
	name: z.string().max(255).optional(),
	domain: z.string().max(255).nullable().optional(),
	parentId: z.string().uuid().nullable().optional(),
});

export type UpdateOrganizationDto = z.infer<typeof updateOrganizationSchema>;

// OPENAPI-3: response schema — mirrors the select shape of this entity so
// controller `@ApiResponse({ schema: { $ref: '.../OrganizationResponseDto' } })`
// decorators resolve to a fully-typed document on /docs-json.
export const organizationResponseSchema = z.object({
	id: z.string().uuid(),
	tenantId: z.string().uuid(),
	name: z.string().max(255),
	domain: z.string().max(255).nullable(),
	parentId: z.string().uuid().nullable(),
});

export type OrganizationResponseDto = z.infer<typeof organizationResponseSchema>;
