/**
 * Person DTOs
 * Generated by entity codegen - do not edit directly
 */

import { z } from 'zod';

export const createPersonSchema = z.object({
	tenantId: z.string().uuid(),
	email: z.string().max(255),
	firstName: z.string().max(100),
	lastName: z.string().max(100),
});

export type CreatePersonDto = z.infer<typeof createPersonSchema>;

export const updatePersonSchema = z.object({
	tenantId: z.string().uuid().optional(),
	email: z.string().max(255).optional(),
	firstName: z.string().max(100).optional(),
	lastName: z.string().max(100).optional(),
});

export type UpdatePersonDto = z.infer<typeof updatePersonSchema>;
