// @generated by @pattern-stack/codegen from test/fixtures/person.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Person DTOs
 * Generated by entity codegen - do not edit directly
 */

import { z } from 'zod';

export const createPersonSchema = z.object({
	tenantId: z.string().uuid(),
	email: z.string().max(255),
	firstName: z.string().max(100),
	lastName: z.string().max(100),
});

export type CreatePersonDto = z.infer<typeof createPersonSchema>;

export const updatePersonSchema = z.object({
	tenantId: z.string().uuid().optional(),
	email: z.string().max(255).optional(),
	firstName: z.string().max(100).optional(),
	lastName: z.string().max(100).optional(),
});

export type UpdatePersonDto = z.infer<typeof updatePersonSchema>;

// OPENAPI-3: response schema — mirrors the select shape of this entity so
// controller `@ApiResponse({ schema: { $ref: '.../PersonResponseDto' } })`
// decorators resolve to a fully-typed document on /docs-json.
export const personResponseSchema = z.object({
	id: z.string().uuid(),
	tenantId: z.string().uuid(),
	email: z.string().max(255),
	firstName: z.string().max(100),
	lastName: z.string().max(100),
});

export type PersonResponseDto = z.infer<typeof personResponseSchema>;
