/**
 * User DTOs
 * Generated by entity codegen - do not edit directly
 */

import { z } from 'zod';

export const createUserSchema = z.object({
	tenantId: z.string().uuid(),
	email: z.string().max(255),
	personId: z.string().uuid().nullable().optional(),
});

export type CreateUserDto = z.infer<typeof createUserSchema>;

export const updateUserSchema = z.object({
	tenantId: z.string().uuid().optional(),
	email: z.string().max(255).optional(),
	personId: z.string().uuid().nullable().optional(),
});

export type UpdateUserDto = z.infer<typeof updateUserSchema>;
