// @generated by @pattern-stack/codegen from test/fixtures/entities/tenant.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
/**
 * Tenant module barrel export
 * Generated by entity codegen - do not edit directly
 */

// Value exports (module, service, controller)
export { TenantsModule } from './tenants.module';
export { TenantService } from './tenant.service';
export { TenantController } from './tenant.controller';

// Type-only exports (entity, DTOs)
export type { Tenant } from './tenant.entity';
export type { CreateTenantDto } from './dto/create-tenant.dto';
export type { UpdateTenantDto } from './dto/update-tenant.dto';
export type { TenantOutputDto } from './dto/tenant-output.dto';
export type { ListTenantsQueryDto } from './dto/list-tenants.query';
