// @generated by @pattern-stack/codegen from test/fixtures/entities/tenant.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, Inject } from '@nestjs/common';

import { eq } from 'drizzle-orm';
import { DRIZZLE } from '@shared/constants/tokens';
import type { DrizzleClient } from '@shared/types/drizzle';
// REL-2 (#587): the generated relation graph. `Relations` binds the repository's
// third type parameter; `IncludeOf`/`ResultOf` are what make a `with` include
// typed. Generated code reaching a generated manifest — the runtime package never
// sees it (REL-1 §4).
import type { IncludeOf, Relations, ResultOf } from '../../generated/relations';
import { BaseRepository } from '@shared/base-classes/base-repository';
import type { ListOptions } from '@shared/base-classes/base-repository';
import { tenants, type Tenant } from './tenant.entity';

/**
 * The relation keys a tenant read may include — the `with` surface of
 * `tenants` in this project's graph.
 *
 * `TWith` is inferred AT THE CALL SITE. Annotating an include literal with this
 * type widens it and loses the exact result shape, so hoist an include into a
 * `const` WITHOUT a type annotation (or with `as const`) if you need to reuse it.
 */
export type TenantInclude = IncludeOf<'tenants'>;

/** The row shape a given tenant include tree resolves to, nested exactly as asked. */
export type TenantResult<TWith extends TenantInclude> =
  ResultOf<'tenants', TWith>;

/** The default `TWith` — no include, so the plain row. */
export type TenantNoInclude = Record<string, never>;

/**
 * The shape an HTTP read returns: the row, plus any allowlisted relation.
 *
 * The controller merges allowlisted fragments at REQUEST time, so which relations
 * are present is not statically known — one of finitely many literals, but not a
 * single one. So the handler's result type is the widened form: every relation
 * OPTIONAL, the row's own columns required. `TenantResult<TenantInclude>`
 * (the fully-included shape) would be wrong here — it claims every relation is
 * always present, which no single request produces.
 *
 * Internal callers keep the exact inferred type, because `TWith` is inferred at
 * the call site (REL-2 §2.3/§5.2).
 */
export type TenantApiResult = Tenant &
  Partial<TenantResult<TenantInclude>>;

@Injectable()
export class TenantRepository extends BaseRepository<Tenant, typeof tenants, Relations> {
  readonly table = tenants;

  constructor(@Inject(DRIZZLE) db: DrizzleClient<Relations>) {
    super(db);
  }


  // TODO: Add entity-specific query methods here.

  // Inherited from BaseRepository:
  //   findById, findByIds, list, count, exists, create, update, delete, upsertMany
}
