---
to: "<%= outputPaths.index %>"
force: true
---
/**
 * <%= classNames.entity %> module barrel export
 * Generated by junction codegen — do not edit directly
 */

// Value exports (module, service)
export { <%= classNames.module %> } from './<%= entityNamePlural %>.module';
export { <%= classNames.service %> } from './<%= name %>.service';

// Type-only exports (entity)
export type { <%= classNames.entity %> } from './<%= name %>.entity';
