---
to: "<%= generate.queries ? outputPaths.queriesIndex : '' %>"
force: true
---
<% if (outputPaths.queriesIndex) { -%>
/**
 * <%= className %> Queries Barrel Export
 * Generated by entity codegen - do not edit directly
 */

export * from './<%= fileNames.getByIdQuery.replace('.ts', '') %>';
export * from './<%= fileNames.listQuery.replace('.ts', '') %>';
<% } -%>
