// @generated by @pattern-stack/codegen from test/fixtures/entities/tenant.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, NotFoundException } from '@nestjs/common';
import { TenantService } from '../tenant.service';
import type { Tenant } from '../tenant.entity';

@Injectable()
export class FindTenantByIdUseCase {
  constructor(private readonly service: TenantService) {}

  async execute(id: string): Promise<Tenant> {
    const entity = await this.service.findById(id);
    if (entity === null || entity === undefined) {
      throw new NotFoundException(`Tenant not found: ${id}`);
    }
    return entity;
  }
}
