// @generated by @pattern-stack/codegen from test/fixtures/entities/tenant.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable } from '@nestjs/common';
import { TenantService } from '../tenant.service';
import type { UpdateTenantDto } from '../dto/update-tenant.dto';
import type { Tenant } from '../tenant.entity';

@Injectable()
export class UpdateTenantUseCase {
  constructor(private readonly service: TenantService) {}

  async execute(
    id: string,
    dto: UpdateTenantDto,
  ): Promise<Tenant | null> {
    return this.service.update(id, dto);
  }
}
