// @generated by @pattern-stack/codegen from entities/deal_state.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { queryCollectionOptions } from '@tanstack/query-db-collection';
import { createCollection } from '@tanstack/react-db';
import { queryClient } from '../query-client';
import { dealStateApi } from '../api/deal-state';
import { dealStateSchema } from '@repo/db/entities/deal_state';

export const dealStateCollection = createCollection(
	queryCollectionOptions({
		id: 'deal_states',
		queryKey: ['deal_states'],
		queryClient,
		// pagination-by-default: the list endpoint returns a Page<T> envelope, so
		// unwrap `.items` to seed the collection with rows (the first page). The
		// paged table drives later fetches via the sync-layer useList; off-page FK
		// resolution hydrates from the full-fetch escape hatch (store/resolvers.ts).
		// async/await (not `.then`) so queryCollectionOptions' overload inference
		// keeps `getKey`'s `item` typed — the .then() form collapses it to unknown.
		queryFn: async () => {
			const page = await dealStateApi.list();
			return page.items;
		},
		getKey: (item) => item.id,
		schema: dealStateSchema,
	}),
);
