// @generated by @pattern-stack/codegen from entities/person.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { electricCollectionOptions } from '@tanstack/electric-db-collection';
import { createCollection } from '@tanstack/react-db';
import { snakeCamelMapper } from '@electric-sql/client';
import { personSchema } from '@repo/db/entities/person';

export const personCollection = createCollection(
	electricCollectionOptions({
		id: 'persons',
		shapeOptions: {
			url: new URL(
				'/v1/shape',
				typeof window !== 'undefined' ? window.location.origin : '',
			).toString(),
			params: {
				table: 'persons',
			},
			parser: {
				timestamptz: (date: string) => new Date(date),
			},
			columnMapper: snakeCamelMapper(),
		},
		schema: personSchema,
		getKey: (item) => item.id,
	}),
);
