// @generated by @pattern-stack/codegen from entities/user.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { queryCollectionOptions } from '@tanstack/query-db-collection';
import { createCollection } from '@tanstack/react-db';
import { queryClient } from '../query-client';
import { userApi } from '../api/user';
import { userSchema } from '@repo/db/entities/user';

export const userCollection = createCollection(
	queryCollectionOptions({
		id: 'users',
		queryKey: ['users'],
		queryClient,
		// pagination-by-default: the list endpoint returns a Page<T> envelope, so
		// unwrap `.items` to seed the collection with rows (the first page). The
		// paged table drives later fetches via the sync-layer useList; off-page FK
		// resolution hydrates from the full-fetch escape hatch (store/resolvers.ts).
		// async/await (not `.then`) so queryCollectionOptions' overload inference
		// keeps `getKey`'s `item` typed — the .then() form collapses it to unknown.
		queryFn: async () => {
			const page = await userApi.list();
			return page.items;
		},
		getKey: (item) => item.id,
		schema: userSchema,
	}),
);
