// @generated by @pattern-stack/codegen from entities/user.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { queryCollectionOptions } from '@tanstack/query-db-collection';
import { createCollection } from '@tanstack/react-db';
import { queryClient } from '../query-client';
import { userApi } from '../api/user';
import { userSchema } from '@repo/db/entities/user';

export const userCollection = createCollection(
	queryCollectionOptions({
		id: 'users',
		queryKey: ['users'],
		queryClient,
		queryFn: () => userApi.list(),
		getKey: (item) => item.id,
		schema: userSchema,
	}),
);
