// @generated by @pattern-stack/codegen from test/fixtures/entities/person.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
/**
 * Person module barrel export
 * Generated by entity codegen - do not edit directly
 */

// Value exports (module, service, controller)
export { PersonsModule } from './persons.module';
export { PersonService } from './person.service';
export { PersonController } from './person.controller';

// Type-only exports (entity, DTOs)
export type { Person } from './person.entity';
export type { CreatePersonDto } from './dto/create-person.dto';
export type { UpdatePersonDto } from './dto/update-person.dto';
export type { PersonOutputDto } from './dto/person-output.dto';
export type { ListPersonsQueryDto } from './dto/list-persons.query';
