// @generated by @pattern-stack/codegen from test/fixtures/entities/person.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Inject, Module, type OnModuleInit } from '@nestjs/common';
import { OPENAPI_REGISTRY, type OpenApiRegistry } from '@shared/openapi';
import { DatabaseModule } from '@shared/database/database.module';

import { PersonRepository } from './person.repository';
import { PersonService } from './person.service';
import { PersonController } from './person.controller';
// OPENAPI-2: Zod schemas registered with OpenApiRegistry at module init.
import { CreatePersonSchema } from './dto/create-person.dto';
import { UpdatePersonSchema } from './dto/update-person.dto';
import { PersonOutputSchema } from './dto/person-output.dto';
import { FindPersonByIdUseCase } from './use-cases/find-person-by-id.use-case';
import { ListPersonsUseCase } from './use-cases/list-persons.use-case';
import { CreatePersonUseCase } from './use-cases/create-person.use-case';
import { UpdatePersonUseCase } from './use-cases/update-person.use-case';
import { DeletePersonUseCase } from './use-cases/delete-person.use-case';

@Module({
  imports: [
    DatabaseModule,
    // TODO: Add subsystem modules as needed (EventsSubsystemModule, IntegrationsSubsystemModule, etc.)
    // Cross-domain modules from relationships:
  ],
  controllers: [PersonController],
  providers: [
    PersonRepository,
    PersonService,
    FindPersonByIdUseCase,
    ListPersonsUseCase,
    CreatePersonUseCase,
    UpdatePersonUseCase,
    DeletePersonUseCase,
  ],
  // ADR-002 (revised): the service is the public API; the repository is ALSO
  // exported so sibling modules that compose this entity cross-module (junction
  // `.list()`, EAV value→definition resolution) inject the home-module instance
  // — the only place the repo's own deps are wired (e.g. an EAV entity's repo
  // injects FieldValueService for the #374 integration dual-write tx). Local-providing
  // such a repo elsewhere can't satisfy those deps. Use-case internals stay unexported.
  exports: [PersonService, PersonRepository],
})
export class PersonsModule implements OnModuleInit {
  // OPENAPI-2: register this entity's Zod schemas with the shared
  // OpenApiRegistry at module init. OPENAPI-4 awaits `build()` at boot
  // to emit the full /docs-json document.
  constructor(
    @Inject(OPENAPI_REGISTRY) private readonly openApi: OpenApiRegistry,
  ) {}

  onModuleInit(): void {
    this.openApi.registerSchema('CreatePersonDto', CreatePersonSchema);
    this.openApi.registerSchema('UpdatePersonDto', UpdatePersonSchema);
    // CLP pipeline names the response schema <Entity>OutputDto (matches
    // classNames.outputDto); the OPENAPI-2 spec sketch uses "ResponseDto"
    // but existing CLP code already publishes OutputDto everywhere, so we
    // keep consistency. OPENAPI-3 decorators reference the same name.
    this.openApi.registerSchema('PersonOutputDto', PersonOutputSchema);
  }
}
