// @generated by @pattern-stack/codegen from test/fixtures/person.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Person Queries Barrel Export
 * Generated by entity codegen - do not edit directly
 */

export * from './get-by-id.query';
export * from './list.query';
