// @generated by @pattern-stack/codegen from test/fixtures/entities/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable } from '@nestjs/common';
import { DealStateService } from '../deal_state.service';
import type { UpdateDealStateDto } from '../dto/update-deal_state.dto';
import type { DealState } from '../deal_state.entity';

@Injectable()
export class UpdateDealStateUseCase {
  constructor(private readonly service: DealStateService) {}

  async execute(
    id: string,
    dto: UpdateDealStateDto,
  ): Promise<DealState | null> {
    return this.service.update(id, dto);
  }
}
