// @generated by @pattern-stack/codegen from entities/deal_state.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { createEntityHooks } from '@pattern-stack/frontend-patterns';
import { dealStateCollection } from '../collections/deal-state';
import { dealStateApi } from '../api/deal-state';
import { getSyncMode } from '../config';
import type { DealState } from '@repo/db/entities/deal_state';

/**
 * Typed hooks for DealState, wired via the framework factory.
 *
 * `localFirst` is resolved at call time from the entity's runtime sync mode
 * (`getSyncMode('deal_state')`) — `api` mode is confirmed-write, everything else
 * is local-first (optimistic).
 */
export const dealStateHooks = createEntityHooks<DealState>({
	name: 'deal_state',
	collection: dealStateCollection,
	api: dealStateApi,
	localFirst: () => getSyncMode('deal_state') !== 'api',
});

// Per-entity hook re-exports for direct imports.
export const {
	useList: useDealStateList,
	useGet: useDealState,
	useCreate: useCreateDealState,
	useUpdate: useUpdateDealState,
	useDelete: useDeleteDealState,
	keys: dealStateKeys,
} = dealStateHooks;
