// @generated by @pattern-stack/codegen — do not edit.
// Run `codegen entity new --all` to regenerate.
//
// The v2 Drizzle relation graph (ADR-044), derived from the entity YAML:
// `relationships:` blocks and `Junction` pairings. Every relation carries an
// explicit `from`/`to`, which is why none of them needs an `alias` — Drizzle
// only consults `alias` when it has to infer a relation's columns from the
// reverse side. See docs/specs/REL-1.md.
import { defineRelations } from 'drizzle-orm';

import * as schema from './schema';

export const relations = defineRelations(schema, (r) => ({
	accounts: {
		contacts: r.many.contacts({ from: r.accounts.id, to: r.contacts.accountId }),
		opportunities: r.many.opportunities({ from: r.accounts.id, to: r.opportunities.accountId }),
		parentAccount: r.one.accounts({ from: r.accounts.parentAccountId, to: r.accounts.id, optional: true }),
	},
	contacts: {
		account: r.one.accounts({ from: r.contacts.accountId, to: r.accounts.id, optional: false }),
		opportunities: r.many.opportunities({ from: r.contacts.id.through(r.opportunityContacts.contactId), to: r.opportunities.id.through(r.opportunityContacts.opportunityId) }),
		opportunityContacts: r.many.opportunityContacts({ from: r.contacts.id, to: r.opportunityContacts.contactId }),
		people: r.many.persons({ from: r.contacts.id, to: r.persons.contactId }),
	},
	notes: {
		opportunity: r.one.opportunities({ from: r.notes.opportunityId, to: r.opportunities.id, optional: false }),
	},
	opportunities: {
		account: r.one.accounts({ from: r.opportunities.accountId, to: r.accounts.id, optional: false }),
		contacts: r.many.contacts({ from: r.opportunities.id.through(r.opportunityContacts.opportunityId), to: r.contacts.id.through(r.opportunityContacts.contactId) }),
		opportunityContacts: r.many.opportunityContacts({ from: r.opportunities.id, to: r.opportunityContacts.opportunityId }),
		primaryNote: r.one.notes({ from: r.opportunities.id, to: r.notes.opportunityId, optional: true }),
	},
	opportunityContacts: {
		contact: r.one.contacts({ from: r.opportunityContacts.contactId, to: r.contacts.id, optional: false }),
		opportunity: r.one.opportunities({ from: r.opportunityContacts.opportunityId, to: r.opportunities.id, optional: false }),
	},
	persons: {
		contact: r.one.contacts({ from: r.persons.contactId, to: r.contacts.id, optional: true }),
	},
}));
