/**
 * Create Organization Command
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add business logic here):
 * - Validation: Add domain validation rules before creating
 * - Defaults: Compute default values not handled by DTO
 * - Side effects: Emit events, send notifications, create related entities
 * - Authorization: Check user permissions beyond route-level auth
 * - Audit: Log creation for compliance/debugging
 */

import { Inject, Injectable } from '@nestjs/common';
import { ORGANIZATION_REPOSITORY } from '../../../constants';
import type { CreateOrganizationInput, IOrganizationRepository } from '../../../domain';
import { Organization } from '../../../domain';
import type { CreateOrganizationDto } from '../../schemas';

@Injectable()
export class CreateOrganizationCommand {
	constructor(
		@Inject(ORGANIZATION_REPOSITORY)
		private readonly organizationRepository: IOrganizationRepository,
	) {}

	async execute(dto: CreateOrganizationDto): Promise<Organization> {
		// TODO: Add pre-create validation and business rules here

		// Map DTO to domain input
		const input: CreateOrganizationInput = {
			tenantId: dto.tenantId,
			name: dto.name,
			domain: dto.domain ?? null,
			parentId: dto.parentId ?? null,
		};

		const created = await this.organizationRepository.create(input);

		// TODO: Add post-create side effects here (events, notifications, etc.)

		return created;
	}
}
