// @generated by @pattern-stack/codegen from the entity set — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { createStore } from '@pattern-stack/frontend-patterns';

import { dealStateHooks } from '../entities/deal-state';
import { personHooks } from '../entities/person';
import { userHooks } from '../entities/user';

import { dealStateCollection } from '../collections/deal-state';
import { personCollection } from '../collections/person';
import { userCollection } from '../collections/user';

import { dealStateFields } from '../fields/deal-state';
import { personFields } from '../fields/person';
import { userFields } from '../fields/user';

import { createLookups } from './lookups';

/**
 * The application store — unified access to every entity.
 *
 * Entities, collections, and field metadata are keyed by their plural name:
 *   store.deal_states.useData()   // useList + fields[plural] meta + hydrated lookups
 *   store.deal_states.useList()
 *   store.resolve.<entity>(id)
 *   store.lookups.current
 *
 * `fields` carries the generated FieldMeta (`fields/<entity>` → `<camel>Fields`);
 * `lookups` is the generated lookups engine (`{ hydrate(): Promise<EntityLookups>;
 * current }`) — hydrated once so off-page FK resolution stays correct under
 * pagination-by-default. Both bind `store.<entity>.useData()`.
 */
export const store = createStore({
	entities: {
		deal_states: dealStateHooks,
		persons: personHooks,
		users: userHooks,
	},
	collections: {
		deal_states: dealStateCollection,
		persons: personCollection,
		users: userCollection,
	},
	fields: {
		deal_states: dealStateFields,
		persons: personFields,
		users: userFields,
	},
	lookups: createLookups(),
});

/** Store type for the `useStore` hook. */
export type AppStore = typeof store;
