// @generated by @pattern-stack/codegen from the entity set — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { personCollection } from '../collections/person';
import { userCollection } from '../collections/user';
import type { Person } from '@repo/db/entities/person';
import type { User } from '@repo/db/entities/user';

/** All entity lookup maps, keyed by plural entity name (id → entity). */
export interface EntityLookups {
	persons: Map<string, Person>;
	users: Map<string, User>;
}

/** Build fresh lookup maps from current collection state. */
export function buildLookups(): EntityLookups {
	return {
		persons: new Map(
			Array.from(personCollection.state.values()).map((item) => [
				(item as Person).id as string,
				item as Person,
			]),
		),
		users: new Map(
			Array.from(userCollection.state.values()).map((item) => [
				(item as User).id as string,
				item as User,
			]),
		),
	};
}

/** Caching lookup factory: `build()` (re)computes, `current` reads, `clear()` resets. */
export function createLookups() {
	let cache: EntityLookups | null = null;
	return {
		build: (): EntityLookups => {
			cache = buildLookups();
			return cache;
		},
		get current(): EntityLookups | null {
			return cache;
		},
		clear: (): void => {
			cache = null;
		},
	};
}
