// @generated by @pattern-stack/codegen from test/fixtures/entities/account.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import {
  pgTable,
  text,
  uuid,
} from 'drizzle-orm/pg-core';
import { type InferSelectModel } from 'drizzle-orm';

export const accounts = pgTable(
  'accounts',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    name: text('name').notNull(),
  },
);

export type Account = InferSelectModel<typeof accounts>;
export type AccountInsert = typeof accounts.$inferInsert;
