// @generated by @pattern-stack/codegen from test/fixtures/entities/account.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, Inject } from '@nestjs/common';
import { DRIZZLE } from '@shared/constants/tokens';
import type { DrizzleClient } from '@shared/types/drizzle';
import { BaseRepository } from '@shared/base-classes/base-repository';
import { accounts, type Account } from './account.entity';

@Injectable()
export class AccountRepository extends BaseRepository<Account, typeof accounts> {
  readonly table = accounts;

  constructor(@Inject(DRIZZLE) db: DrizzleClient) {
    super(db);
  }

  // TODO: Add entity-specific query methods here.

  // Inherited from BaseRepository:
  //   findById, findByIds, list, count, exists, create, update, delete, upsertMany
}
