// @generated by @pattern-stack/codegen from test/fixtures/entities/contact-v2.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
/**
 * EVT-7: This entity emits typed domain events. Use-cases depend on
 * TYPED_EVENT_BUS + DRIZZLE. Ensure EventsModule is registered in the
 * root AppModule (global) so these tokens resolve at runtime.
 */
import { Inject, Module, type OnModuleInit } from '@nestjs/common';
import { OPENAPI_REGISTRY, type OpenApiRegistry } from '@shared/openapi';
import { DatabaseModule } from '@shared/database/database.module';
import { AccountRepository } from '../accounts/account.repository';
import { UserRepository } from '../users/user.repository';

import { ContactRepository } from './contact.repository';
import { ContactService } from './contact.service';
import { ContactController } from './contact.controller';
// OPENAPI-2: Zod schemas registered with OpenApiRegistry at module init.
import { CreateContactSchema } from './dto/create-contact.dto';
import { UpdateContactSchema } from './dto/update-contact.dto';
import { ContactOutputSchema } from './dto/contact-output.dto';
import { FindContactByIdUseCase } from './use-cases/find-contact-by-id.use-case';
import { ListContactsUseCase } from './use-cases/list-contacts.use-case';
import { CreateContactUseCase } from './use-cases/create-contact.use-case';
import { UpdateContactUseCase } from './use-cases/update-contact.use-case';
import { DeleteContactUseCase } from './use-cases/delete-contact.use-case';
import { declarativeQueryClasses } from './use-cases/declarative-queries';

@Module({
  imports: [
    DatabaseModule,
    // TODO: Add subsystem modules as needed (EventsSubsystemModule, IntegrationsSubsystemModule, etc.)
    // Cross-domain modules from relationships:
    // AccountsModule,
    // UsersModule,
  ],
  controllers: [ContactController],
  providers: [
    ContactRepository,
    ContactService,
    AccountRepository,
    UserRepository,
    FindContactByIdUseCase,
    ListContactsUseCase,
    CreateContactUseCase,
    UpdateContactUseCase,
    DeleteContactUseCase,
    ...declarativeQueryClasses,
  ],
  // ADR-002 (revised): the service is the public API; the repository is ALSO
  // exported so sibling modules that compose this entity cross-module (junction
  // `.list()`, EAV value→definition resolution) inject the home-module instance
  // — the only place the repo's own deps are wired (e.g. an EAV entity's repo
  // injects FieldValueService for the #374 integration dual-write tx). Local-providing
  // such a repo elsewhere can't satisfy those deps. Use-case internals stay unexported.
  exports: [ContactService, ContactRepository],
})
export class ContactsModule implements OnModuleInit {
  // OPENAPI-2: register this entity's Zod schemas with the shared
  // OpenApiRegistry at module init. OPENAPI-4 awaits `build()` at boot
  // to emit the full /docs-json document.
  constructor(
    @Inject(OPENAPI_REGISTRY) private readonly openApi: OpenApiRegistry,
  ) {}

  onModuleInit(): void {
    this.openApi.registerSchema('CreateContactDto', CreateContactSchema);
    this.openApi.registerSchema('UpdateContactDto', UpdateContactSchema);
    // The response schema is named <Entity>OutputDto (matches
    // classNames.outputDto); the OPENAPI-2 spec sketch uses "ResponseDto"
    // but the generated code publishes OutputDto everywhere, so we
    // keep consistency. OPENAPI-3 decorators reference the same name.
    this.openApi.registerSchema('ContactOutputDto', ContactOutputSchema);
  }
}
