// @generated by @pattern-stack/codegen from test/fixtures/entities/contact-v2.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { Injectable, Inject } from '@nestjs/common';

import { eq, and, desc, asc } from 'drizzle-orm';
import { DRIZZLE } from '@shared/constants/tokens';
import type { DrizzleClient, DrizzleTx } from '@shared/types/drizzle';
// REL-2 (#587): the generated relation graph. `Relations` binds the repository's
// third type parameter; `IncludeOf`/`ResultOf` are what make a `with` include
// typed. Generated code reaching a generated manifest — the runtime package never
// sees it (REL-1 §4).
import type { IncludeOf, Relations, ResultOf } from '../../generated/relations';
import { IntegratedEntityRepository } from '@shared/base-classes/integrated-entity-repository';
import type { IntegrationUpsertConfig } from '@shared/base-classes/integration-upsert-config';
import type { BehaviorConfig, ListOptions } from '@shared/base-classes/base-repository';
import { contacts, type Contact } from './contact.entity';
import { accounts } from '../accounts/account.entity';
import { users } from '../users/user.entity';

/**
 * Canonical fields a integrated contact write carries (#374). Copy-through
 * columns are typed from the entity; each FK is named by its parent's external
 * id and resolved in integrationUpsertOne. Provider/providerMetadata are persistence
 * seam, not carried here.
 */
export interface ContactIntegrationWrite {
  readonly externalId: string;
  readonly firstName: string;
  readonly lastName: string;
  readonly email: string;
  readonly title: string | null;
  readonly phone: string | null;
  readonly linkedinUrl: string | null;
  readonly accountExternalId?: string | null;
  readonly userExternalId?: string | null;
  /** Flat custom-field bag (EAV). */
  readonly fields?: Record<string, unknown>;
}

/**
 * Canonical-projected view of a contact row, keyed for the integration differ
 * (#374). external_id_tracking columns (provider/providerMetadata) are OMITTED;
 * externalId is kept.
 */
export interface ContactIntegrationProjection {
  readonly id: string;
  readonly externalId: string;
  readonly firstName: string;
  readonly lastName: string;
  readonly email: string;
  readonly title: string | null;
  readonly phone: string | null;
  readonly linkedinUrl: string | null;
  readonly accountId: string | null;
  readonly userId: string;
  readonly createdAt: Date;
  readonly updatedAt: Date;
}

/**
 * The relation keys a contact read may include — the `with` surface of
 * `contacts` in this project's graph.
 *
 * `TWith` is inferred AT THE CALL SITE. Annotating an include literal with this
 * type widens it and loses the exact result shape, so hoist an include into a
 * `const` WITHOUT a type annotation (or with `as const`) if you need to reuse it.
 */
export type ContactInclude = IncludeOf<'contacts'>;

/** The row shape a given contact include tree resolves to, nested exactly as asked. */
export type ContactResult<TWith extends ContactInclude> =
  ResultOf<'contacts', TWith>;

/** The default `TWith` — no include, so the plain row. */
export type ContactNoInclude = Record<string, never>;

/**
 * The shape an HTTP read returns: the row, plus any allowlisted relation.
 *
 * The controller merges allowlisted fragments at REQUEST time, so which relations
 * are present is not statically known — one of finitely many literals, but not a
 * single one. So the handler's result type is the widened form: every relation
 * OPTIONAL, the row's own columns required. `ContactResult<ContactInclude>`
 * (the fully-included shape) would be wrong here — it claims every relation is
 * always present, which no single request produces.
 *
 * Internal callers keep the exact inferred type, because `TWith` is inferred at
 * the call site (REL-2 §2.3/§5.2).
 */
export type ContactApiResult = Contact &
  Partial<ContactResult<ContactInclude>>;

@Injectable()
export class ContactRepository extends IntegratedEntityRepository<
  Contact,
  typeof contacts,
  Relations,
  ContactIntegrationWrite,
  ContactIntegrationProjection
> {
  readonly table = contacts;

  // Behaviors declared in YAML -> generated as config object
  protected override readonly behaviors: BehaviorConfig = {
    timestamps: true,
    softDelete: true,
    userTracking: false,
    tenantScoped: false,
  };

  // Inbound-integration write surface (#374). Drives the generic integrationUpsertOne /
  // findByExternalIdProjected / softDeleteByExternalId on the base. FK
  // resolvers carry LIVE Drizzle table handles ('self' → this.table).
  protected readonly integrationConfig: IntegrationUpsertConfig = {
    conflictTarget: ['provider', 'externalId'],
    writeColumns: ['firstName', 'lastName', 'email', 'title', 'phone', 'linkedinUrl'],
    fkResolvers: [
      { column: 'accountId', writeKey: 'accountExternalId', refTable: accounts },
      { column: 'userId', writeKey: 'userExternalId', refTable: users, strict: true },
    ],
    projectionColumns: ['id', 'externalId', 'firstName', 'lastName', 'email', 'title', 'phone', 'linkedinUrl', 'accountId', 'userId', 'createdAt', 'updatedAt'],
    eav: false,
    softDelete: true,
  };

  constructor(@Inject(DRIZZLE) db: DrizzleClient<Relations>) {
    super(db);
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Typed `with` includes (REL-2, #587)
  //
  // The include surface is emitted HERE, not on the base class: with
  // `TRelations` and the relation key as naked type parameters,
  // `DBQueryConfig<…>['with']` is a TS2536, so a generic
  // `BaseRepository.findById<TWith>` cannot be written (REL-2 §2.1). Where both
  // are concrete — this subclass — everything resolves.
  //
  // Two execution paths, one scope. Without a `with` the call goes through
  // `baseQuery()`, whose single `WHERE` carries the guards. With a `with` it
  // goes through RQBv2 (`db.query.contacts`), because `baseQuery()`
  // cannot carry an include — and the root filter injects the SAME predicate via
  // `rootScopeRawOn(t, …)`. Every HOP is scoped by the relations manifest itself,
  // so a caller cannot reach an unscoped level (REL-2 §1.4/§3).
  //
  // The `t` matters: RQBv2 ALIASES the root table, so the predicate must render
  // against the handle it hands the closure, not against the repository's own.
  //
  // Depth is uncapped here: charter I4 asks for ONE statement, not a shallow
  // one. The depth cap is an HTTP concern (`api.includes.max_depth`).
  // ═══════════════════════════════════════════════════════════════════════

  override async findById<TWith extends ContactInclude = ContactNoInclude>(
    id: string,
    opts?: { with?: TWith },
  ): Promise<ContactResult<TWith> | null> {
    if (opts?.with === undefined) {
      const rows = await this.baseQuery(eq(this.table['id'], id)).limit(1);
      return (rows[0] as ContactResult<TWith>) ?? null;
    }
    const row = await this.db.query.contacts.findFirst({
      where: {
        AND: [
          { id: { eq: id } },
          { RAW: (t) => this.rootScopeRawOn(t, { softDelete: true }) },
        ],
      },
      with: opts.with,
    });
    return (row as ContactResult<TWith> | undefined) ?? null;
  }

  override async list<TWith extends ContactInclude = ContactNoInclude>(
    query?: ListOptions & { with?: TWith },
  ): Promise<Array<ContactResult<TWith>>> {
    if (query?.with === undefined) {
      return (await super.list(query)) as Array<ContactResult<TWith>>;
    }
    if (query.orderBy !== undefined) {
      // A pre-rendered `orderBy` names the table by its REAL name, and RQBv2
      // aliases the root — so the fragment would reference a table that is not in
      // scope and Postgres would reject the statement. Fail loud rather than issue
      // it; pass `sort` instead, which both paths can render (REL-2 §2.4).
      throw new Error(
        'ContactRepository.list: `orderBy` cannot be combined with `with` — ' +
          'pass `sort: [{ column, direction }]` instead.',
      );
    }
    const callerWhere = query.where;
    const callerSort = query.sort;
    const rows = await this.db.query.contacts.findMany({
      where: {
        AND: [
          ...(callerWhere === undefined ? [] : [{ RAW: callerWhere }]),
          { RAW: (t) => this.rootScopeRawOn(t, { softDelete: true }) },
        ],
      },
      with: query.with,
      // The ALIASED table RQBv2 hands the callback, not this repo's own handle.
      ...(callerSort === undefined ? {} : { orderBy: (t) => this.orderByOn(t, callerSort) ?? [] }),
      ...(query.limit === undefined ? {} : { limit: query.limit }),
      ...(query.offset === undefined ? {} : { offset: query.offset }),
    });
    return rows as Array<ContactResult<TWith>>;
  }

  // ═══════════════════════════════════════════════════════════════════════
  // Declarative queries (from queries: block in entity YAML)
  // ═══════════════════════════════════════════════════════════════════════

  async findByEmail<TWith extends ContactInclude = ContactNoInclude>(
    email: string,
    opts?: { with?: TWith },
  ): Promise<ContactResult<TWith> | null> {
    if (opts?.with === undefined) {
      const rows = await this.baseQuery(eq(this.table['email'], email))
        .limit(1);
      return (rows[0] as ContactResult<TWith>) ?? null;
    }
    const row = await this.db.query.contacts.findFirst({
      where: {
        AND: [
          { email: { eq: email } },
          { RAW: (t) => this.rootScopeRawOn(t, { softDelete: true }) },
        ],
      },
      with: opts.with,
    });
    return (row as ContactResult<TWith> | undefined) ?? null;
  }

  async findByUserIdAndAccountId<TWith extends ContactInclude = ContactNoInclude>(
    userId: string, accountId: string,
    opts?: { with?: TWith },
  ): Promise<Array<ContactResult<TWith>>> {
    if (opts?.with === undefined) {
      const rows = await this.baseQuery(and(eq(this.table['userId'], userId), eq(this.table['accountId'], accountId)));
      return rows as Array<ContactResult<TWith>>;
    }
    const rows = await this.db.query.contacts.findMany({
      where: {
        AND: [
          { userId: { eq: userId } },
          { accountId: { eq: accountId } },
          { RAW: (t) => this.rootScopeRawOn(t, { softDelete: true }) },
        ],
      },
      with: opts.with,
    });
    return rows as Array<ContactResult<TWith>>;
  }

  async findByOpportunityId(opportunityId: string): Promise<Contact[]> {
    const rows = await this.baseQuery(eq(this.table['opportunityId'], opportunityId));
    return rows as Contact[];
  }

  async findEmailsByOpportunityId(opportunityId: string): Promise<string[]> {
    const rows = await this.baseQuery(eq(this.table['opportunityId'], opportunityId));
    return rows as Contact[];
  }

  // ═══════════════════════════════════════════════════════════════════════
  // FK traversal methods (from belongs_to relationships — CGP-358b)
  // Called by service-layer composition methods on the inverse (has_many) side.
  // A FK method whose name collides with a unique/via/select declarative query
  // is skipped — that declarative query is the more specific intent and wins.
  // ═══════════════════════════════════════════════════════════════════════

  async findByAccountId<TWith extends ContactInclude = ContactNoInclude>(
    id: string,
    opts?: { cursor?: string; limit?: number; with?: TWith },
  ): Promise<Array<ContactResult<TWith>>> {
    if (opts?.with === undefined) {
      let q = this.baseQuery(eq(this.table['accountId'], id));
      if (opts?.limit) q = q.limit(opts.limit) as typeof q;
      return (await q) as Array<ContactResult<TWith>>;
    }
    const rows = await this.db.query.contacts.findMany({
      where: {
        AND: [
          { accountId: { eq: id } },
          { RAW: (t) => this.rootScopeRawOn(t, { softDelete: true }) },
        ],
      },
      with: opts.with,
      ...(opts.limit === undefined ? {} : { limit: opts.limit }),
    });
    return rows as Array<ContactResult<TWith>>;
  }

  async findByUserId<TWith extends ContactInclude = ContactNoInclude>(
    id: string,
    opts?: { cursor?: string; limit?: number; with?: TWith },
  ): Promise<Array<ContactResult<TWith>>> {
    if (opts?.with === undefined) {
      let q = this.baseQuery(eq(this.table['userId'], id));
      if (opts?.limit) q = q.limit(opts.limit) as typeof q;
      return (await q) as Array<ContactResult<TWith>>;
    }
    const rows = await this.db.query.contacts.findMany({
      where: {
        AND: [
          { userId: { eq: id } },
          { RAW: (t) => this.rootScopeRawOn(t, { softDelete: true }) },
        ],
      },
      with: opts.with,
      ...(opts.limit === undefined ? {} : { limit: opts.limit }),
    });
    return rows as Array<ContactResult<TWith>>;
  }

  // Inherited from IntegratedEntityRepository:
  //   findById, findByIds, list, count, exists, create, update, delete, upsertMany
  //   findByExternalId, findManyByExternalIds, findAllByUserId, findVisibleByUserId
  //   integrationUpsertOne, findByExternalIdProjected, softDeleteByExternalId, integrationUpsert
}
