/**
 * DealState Shared Schema
 * Generated by entity codegen - do not edit directly
 */

import { z } from 'zod';

// Base schema
export const dealStateSchema = z.object({
	id: z.string().uuid(),
	tenantId: z.string().uuid().nullable(),
	name: z.string().max(50),
	displayName: z.string().max(100),
	stateType: z.enum(['open', 'won', 'lost', 'stalled']),
	sortOrder: z.number().int(),
	probabilityDefault: z.number().int().min(0).max(100).nullable(),
	color: z.string().max(20).nullable(),
});

export type DealState = z.infer<typeof dealStateSchema>;

// Create schema (for mutations)
export const createDealStateSchema = z.object({
	tenantId: z.string().uuid().nullable().optional(),
	name: z.string().max(50),
	displayName: z.string().max(100),
	stateType: z.enum(['open', 'won', 'lost', 'stalled']),
	sortOrder: z.number().int(),
	probabilityDefault: z.number().int().min(0).max(100).nullable().optional(),
	color: z.string().max(20).nullable().optional(),
});

export type CreateDealStateInput = z.infer<typeof createDealStateSchema>;

// Update schema (for mutations)
export const updateDealStateSchema = z.object({
	tenantId: z.string().uuid().nullable().optional(),
	name: z.string().max(50).optional(),
	displayName: z.string().max(100).optional(),
	stateType: z.enum(['open', 'won', 'lost', 'stalled']).optional(),
	sortOrder: z.number().int().optional(),
	probabilityDefault: z.number().int().min(0).max(100).nullable().optional(),
	color: z.string().max(20).nullable().optional(),
});

export type UpdateDealStateInput = z.infer<typeof updateDealStateSchema>;

// Mutation schemas (for tRPC)
export const dealStateMutationSchemas = {
	create: createDealStateSchema,
	update: z.object({
		id: z.string().uuid(),
		data: updateDealStateSchema,
	}),
	delete: z.object({
		id: z.string().uuid(),
	}),
};
