// @generated by @pattern-stack/codegen from entities/account.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { eq, useLiveQuery } from '@tanstack/react-db';

import { accountCollection } from '../collections/account';
import { contactCollection } from '../collections/contact';
import { noteCollection } from '../collections/note';
import { opportunityCollection } from '../collections/opportunity';

import type { Account } from '@repo/db/entities/account';
import type { Contact } from '@repo/db/entities/contact';
import type { Note } from '@repo/db/entities/note';
import type { Opportunity } from '@repo/db/entities/opportunity';

/**
 * Read a key off an include literal that may omit it.
 *
 * `I['parentAccount']` alone would be an error for a literal that does not
 * carry the key; this resolves to `undefined` instead, which is what the
 * result type branches on.
 */
type Sel<I, K extends PropertyKey> = K extends keyof I ? I[K] : undefined;

/** To-one hops of Contact that join into the `contacts` branch's own query. */
export interface AccountContactsWith {
	/** Contact.account → Account */
	account?: true;
}

/** To-one hops of Opportunity that join into the `opportunities` branch's own query. */
export interface AccountOpportunitiesWith {
	/** Opportunity.account → Account */
	account?: true;
	/** Opportunity.primaryNote → Note */
	primaryNote?: true;
}

/**
 * The relations of Account that are navigable on the client.
 *
 * A misspelled key is a compile error here, nested or not (FE-REL §5). The
 * include literal is inferred at the CALL SITE — annotating a `const` with this
 * type widens it and loses the exact result shape, the same caveat REL-2
 * records for the server side.
 */
export interface AccountInclude {
	/** to-one → Account | undefined */
	parentAccount?: true;
	/** to-many → Contact[] — its own live query */
	contacts?: true | { with?: AccountContactsWith };
	/** to-many → Opportunity[] — its own live query */
	opportunities?: true | { with?: AccountOpportunitiesWith };
}

type AccountContactsRow<W> = Contact &
	(Sel<Sel<W, 'with'>, 'account'> extends true ? { account: Account | undefined } : unknown);
type AccountOpportunitiesRow<W> = Opportunity &
	(Sel<Sel<W, 'with'>, 'account'> extends true ? { account: Account | undefined } : unknown) &
	(Sel<Sel<W, 'with'>, 'primaryNote'> extends true ? { primaryNote: Note | undefined } : unknown);

/**
 * The result of {@link useAccountGraph} for a given include.
 *
 * A to-one hop is `T | undefined` (it is left-joined); a to-many is `T[]`. A
 * relation that was not included is not on the type at all, so reading it is a
 * compile error rather than `undefined` at runtime.
 */
export type AccountGraph<I extends AccountInclude> = Account &
	(Sel<I, 'parentAccount'> extends true ? { parentAccount: Account | undefined } : unknown) &
	(Sel<I, 'contacts'> extends undefined ? unknown : { contacts: Array<AccountContactsRow<Sel<I, 'contacts'>>> }) &
	(Sel<I, 'opportunities'> extends undefined ? unknown : { opportunities: Array<AccountOpportunitiesRow<Sel<I, 'opportunities'>>> });

/** What every graph hook returns. */
export interface AccountGraphResult<I extends AccountInclude> {
	data: AccountGraph<I> | undefined;
	isLoading: boolean;
	isError: boolean;
}

/** The `with` object of a branch's include value, or `{}` for a bare `true`. */
function withOf(value: unknown): Record<string, unknown> {
	return typeof value === 'object' && value !== null && 'with' in value
		? ((value as { with?: Record<string, unknown> }).with ?? {})
		: {};
}

/**
 * Traverse the graph from one Account.
 *
 * ```ts
 * const { data } = useAccountGraph(id, { contacts: true });
 * ```
 *
 * Queries issued: **1 for the root** (carrying every to-one hop as a join) plus
 * **one per to-many relation that was included** — 2 possible, all
 * visible below. Never one per row: there is no loop here that could produce an
 * N+1 (charter I4, FE-REL §4.1). A branch that was not included returns
 * `undefined` from its query function, which `useLiveQuery` treats as disabled,
 * so it costs nothing while keeping the hook count static as React requires.
 */
export function useAccountGraph<const I extends AccountInclude>(
	id: string | null | undefined,
	include: I,
): AccountGraphResult<I> {
	// Widened once: the generic `I` is for the CALLER's result type; the body
	// reads the include as plain data.
	const inc = include as AccountInclude;

	// The root row, with every to-one hop joined in. One query regardless of
	// how many to-one relations the entity has.
	const root = useLiveQuery(
		(q) =>
			id !== null && id !== undefined
				? q
						.from({ row: accountCollection })
						.where(({ row }) => eq(row.id, id))
						.join({ parentAccount: accountCollection }, ({ row, parentAccount }) =>
							eq(row.parentAccountId, parentAccount.id),
						)
						.select(({ row, parentAccount }) => ({ row, parentAccount }))
				: undefined,
		[id],
	);

	// `contacts` — one live query, disabled unless it was included.
	const contactsBranch = useLiveQuery(
		(q) =>
			id !== null && id !== undefined && inc.contacts
				? q
						.from({ row: contactCollection })
						.where(({ row }) => eq(row.accountId, id))
						.join({ account: accountCollection }, ({ row, account }) =>
							eq(row.accountId, account.id),
						)
						.select(({ row, account }) => ({ row, account }))
				: undefined,
		[id, Boolean(inc.contacts)],
	);

	// `opportunities` — one live query, disabled unless it was included.
	const opportunitiesBranch = useLiveQuery(
		(q) =>
			id !== null && id !== undefined && inc.opportunities
				? q
						.from({ row: opportunityCollection })
						.where(({ row }) => eq(row.accountId, id))
						.join({ account: accountCollection }, ({ row, account }) =>
							eq(row.accountId, account.id),
						)
						.join({ primaryNote: noteCollection }, ({ row, primaryNote }) =>
							eq(row.id, primaryNote.opportunityId),
						)
						.select(({ row, account, primaryNote }) => ({ row, account, primaryNote }))
				: undefined,
		[id, Boolean(inc.opportunities)],
	);

	const isLoading = root.isLoading || contactsBranch.isLoading || opportunitiesBranch.isLoading;
	const isError = root.isError || contactsBranch.isError || opportunitiesBranch.isError;

	const rootRow = root.data?.[0];
	if (!rootRow) return { data: undefined, isLoading, isError };

	const out: Record<string, unknown> = { ...rootRow.row };
	if (inc.parentAccount) out.parentAccount = rootRow.parentAccount;
	if (inc.contacts) {
		out.contacts = (contactsBranch.data ?? []).map((r) => ({
			...r.row,
			...(withOf(inc.contacts).account ? { account: r.account } : {}),
		}));
	}
	if (inc.opportunities) {
		out.opportunities = (opportunitiesBranch.data ?? []).map((r) => ({
			...r.row,
			...(withOf(inc.opportunities).account ? { account: r.account } : {}),
			...(withOf(inc.opportunities).primaryNote ? { primaryNote: r.primaryNote } : {}),
		}));
	}

	// The one cast in the file, and it is the boundary cast: `out` is assembled
	// from the include at runtime, and `AccountGraph<I>` is the same
	// shape derived from it at compile time. Every property put on `out` above is
	// guarded by the same `inc.<rel>` check the type branches on.
	return { data: out as AccountGraph<I>, isLoading, isError };
}
