// @generated by @pattern-stack/codegen from entities/contact.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { eq, useLiveQuery } from '@tanstack/react-db';

import { accountCollection } from '../collections/account';
import { contactCollection } from '../collections/contact';
import { noteCollection } from '../collections/note';
import { opportunityCollection } from '../collections/opportunity';
import { opportunityContactCollection } from '../collections/opportunity-contact';
import { personCollection } from '../collections/person';

import type { Account } from '@repo/db/entities/account';
import type { Contact } from '@repo/db/entities/contact';
import type { Note } from '@repo/db/entities/note';
import type { Opportunity } from '@repo/db/entities/opportunity';
import type { OpportunityContact } from '@repo/db/entities/opportunity_contact';
import type { Person } from '@repo/db/entities/person';

/**
 * Read a key off an include literal that may omit it.
 *
 * `I['account']` alone would be an error for a literal that does not
 * carry the key; this resolves to `undefined` instead, which is what the
 * result type branches on.
 */
type Sel<I, K extends PropertyKey> = K extends keyof I ? I[K] : undefined;

/** To-one hops of Opportunity that join into the `opportunities` branch's own query. */
export interface ContactOpportunitiesWith {
	/** Opportunity.account → Account */
	account?: true;
	/** Opportunity.primaryNote → Note */
	primaryNote?: true;
}

/** `contact.opportunityContacts` has no to-one hop to nest — `with` is empty. */
export type ContactOpportunityContactsWith = Record<never, never>;

/** To-one hops of Person that join into the `people` branch's own query. */
export interface ContactPeopleWith {
	/** Person.contact → Contact */
	contact?: true;
}

/**
 * The relations of Contact that are navigable on the client.
 *
 * A misspelled key is a compile error here, nested or not (FE-REL §5). The
 * include literal is inferred at the CALL SITE — annotating a `const` with this
 * type widens it and loses the exact result shape, the same caveat REL-2
 * records for the server side.
 */
export interface ContactInclude {
	/** to-one → Account */
	account?: true;
	/** to-many → Opportunity[] (through `opportunityContacts`) — its own live query */
	opportunities?: true | { with?: ContactOpportunitiesWith };
	/** to-many → OpportunityContact[] — its own live query */
	opportunityContacts?: true | { with?: ContactOpportunityContactsWith };
	/** to-many → Person[] — its own live query */
	people?: true | { with?: ContactPeopleWith };
}

type ContactOpportunitiesRow<W> = Opportunity &
	(Sel<Sel<W, 'with'>, 'account'> extends true ? { account: Account | undefined } : unknown) &
	(Sel<Sel<W, 'with'>, 'primaryNote'> extends true ? { primaryNote: Note | undefined } : unknown);
/** `contact.opportunityContacts` rows — nothing nests into them. */
type ContactOpportunityContactsRow = OpportunityContact;
type ContactPeopleRow<W> = Person &
	(Sel<Sel<W, 'with'>, 'contact'> extends true ? { contact: Contact | undefined } : unknown);

/**
 * The result of {@link useContactGraph} for a given include.
 *
 * A to-one hop is `T | undefined` (it is left-joined); a to-many is `T[]`. A
 * relation that was not included is not on the type at all, so reading it is a
 * compile error rather than `undefined` at runtime.
 */
export type ContactGraph<I extends ContactInclude> = Contact &
	(Sel<I, 'account'> extends true ? { account: Account | undefined } : unknown) &
	(Sel<I, 'opportunities'> extends undefined ? unknown : { opportunities: Array<ContactOpportunitiesRow<Sel<I, 'opportunities'>>> }) &
	(Sel<I, 'opportunityContacts'> extends undefined ? unknown : { opportunityContacts: Array<ContactOpportunityContactsRow> }) &
	(Sel<I, 'people'> extends undefined ? unknown : { people: Array<ContactPeopleRow<Sel<I, 'people'>>> });

/** What every graph hook returns. */
export interface ContactGraphResult<I extends ContactInclude> {
	data: ContactGraph<I> | undefined;
	isLoading: boolean;
	isError: boolean;
}

/** The `with` object of a branch's include value, or `{}` for a bare `true`. */
function withOf(value: unknown): Record<string, unknown> {
	return typeof value === 'object' && value !== null && 'with' in value
		? ((value as { with?: Record<string, unknown> }).with ?? {})
		: {};
}

/**
 * Traverse the graph from one Contact.
 *
 * ```ts
 * const { data } = useContactGraph(id, { opportunities: true });
 * ```
 *
 * Queries issued: **1 for the root** (carrying every to-one hop as a join) plus
 * **one per to-many relation that was included** — 3 possible, all
 * visible below. Never one per row: there is no loop here that could produce an
 * N+1 (charter I4, FE-REL §4.1). A branch that was not included returns
 * `undefined` from its query function, which `useLiveQuery` treats as disabled,
 * so it costs nothing while keeping the hook count static as React requires.
 */
export function useContactGraph<const I extends ContactInclude>(
	id: string | null | undefined,
	include: I,
): ContactGraphResult<I> {
	// Widened once: the generic `I` is for the CALLER's result type; the body
	// reads the include as plain data.
	const inc = include as ContactInclude;

	// The root row, with every to-one hop joined in. One query regardless of
	// how many to-one relations the entity has.
	const root = useLiveQuery(
		(q) =>
			id !== null && id !== undefined
				? q
						.from({ row: contactCollection })
						.where(({ row }) => eq(row.id, id))
						.join({ account: accountCollection }, ({ row, account }) =>
							eq(row.accountId, account.id),
						)
						.select(({ row, account }) => ({ row, account }))
				: undefined,
		[id],
	);

	// `opportunities` — one live query, disabled unless it was included.
	const opportunitiesBranch = useLiveQuery(
		(q) =>
			id !== null && id !== undefined && inc.opportunities
				? q
						.from({ link: opportunityContactCollection })
						.where(({ link }) => eq(link.contactId, id))
						.innerJoin({ row: opportunityCollection }, ({ link, row }) =>
							eq(link.opportunityId, row.id),
						)
						.join({ account: accountCollection }, ({ row, account }) =>
							eq(row.accountId, account.id),
						)
						.join({ primaryNote: noteCollection }, ({ row, primaryNote }) =>
							eq(row.id, primaryNote.opportunityId),
						)
						.select(({ row, account, primaryNote }) => ({ row, account, primaryNote }))
				: undefined,
		[id, Boolean(inc.opportunities)],
	);

	// `opportunityContacts` — one live query, disabled unless it was included.
	const opportunityContactsBranch = useLiveQuery(
		(q) =>
			id !== null && id !== undefined && inc.opportunityContacts
				? q
						.from({ row: opportunityContactCollection })
						.where(({ row }) => eq(row.contactId, id))
						.select(({ row }) => ({ row }))
				: undefined,
		[id, Boolean(inc.opportunityContacts)],
	);

	// `people` — one live query, disabled unless it was included.
	const peopleBranch = useLiveQuery(
		(q) =>
			id !== null && id !== undefined && inc.people
				? q
						.from({ row: personCollection })
						.where(({ row }) => eq(row.contactId, id))
						.join({ contact: contactCollection }, ({ row, contact }) =>
							eq(row.contactId, contact.id),
						)
						.select(({ row, contact }) => ({ row, contact }))
				: undefined,
		[id, Boolean(inc.people)],
	);

	const isLoading = root.isLoading || opportunitiesBranch.isLoading || opportunityContactsBranch.isLoading || peopleBranch.isLoading;
	const isError = root.isError || opportunitiesBranch.isError || opportunityContactsBranch.isError || peopleBranch.isError;

	const rootRow = root.data?.[0];
	if (!rootRow) return { data: undefined, isLoading, isError };

	const out: Record<string, unknown> = { ...rootRow.row };
	if (inc.account) out.account = rootRow.account;
	if (inc.opportunities) {
		out.opportunities = (opportunitiesBranch.data ?? []).map((r) => ({
			...r.row,
			...(withOf(inc.opportunities).account ? { account: r.account } : {}),
			...(withOf(inc.opportunities).primaryNote ? { primaryNote: r.primaryNote } : {}),
		}));
	}
	if (inc.opportunityContacts) {
		out.opportunityContacts = (opportunityContactsBranch.data ?? []).map((r) => ({ ...r.row }));
	}
	if (inc.people) {
		out.people = (peopleBranch.data ?? []).map((r) => ({
			...r.row,
			...(withOf(inc.people).contact ? { contact: r.contact } : {}),
		}));
	}

	// The one cast in the file, and it is the boundary cast: `out` is assembled
	// from the include at runtime, and `ContactGraph<I>` is the same
	// shape derived from it at compile time. Every property put on `out` above is
	// guarded by the same `inc.<rel>` check the type branches on.
	return { data: out as ContactGraph<I>, isLoading, isError };
}
