// @generated by @pattern-stack/codegen from entities/person.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import { eq, useLiveQuery } from '@tanstack/react-db';

import { accountCollection } from '../collections/account';
import { contactCollection } from '../collections/contact';
import { personCollection } from '../collections/person';

import type { Account } from '@repo/db/entities/account';
import type { Contact } from '@repo/db/entities/contact';
import type { Person } from '@repo/db/entities/person';

/**
 * Read a key off an include literal that may omit it.
 *
 * `I['contact']` alone would be an error for a literal that does not
 * carry the key; this resolves to `undefined` instead, which is what the
 * result type branches on.
 */
type Sel<I, K extends PropertyKey> = K extends keyof I ? I[K] : undefined;



/**
 * The relations of Person that are navigable on the client.
 *
 * A misspelled key is a compile error here, nested or not (FE-REL §5). The
 * include literal is inferred at the CALL SITE — annotating a `const` with this
 * type widens it and loses the exact result shape, the same caveat REL-2
 * records for the server side.
 */
export interface PersonInclude {
	/** to-one → Contact | undefined */
	contact?: true;
}



/**
 * The result of {@link usePersonGraph} for a given include.
 *
 * A to-one hop is `T | undefined` (it is left-joined); a to-many is `T[]`. A
 * relation that was not included is not on the type at all, so reading it is a
 * compile error rather than `undefined` at runtime.
 */
export type PersonGraph<I extends PersonInclude> = Person &
	(Sel<I, 'contact'> extends true ? { contact: Contact | undefined } : unknown);

/** What every graph hook returns. */
export interface PersonGraphResult<I extends PersonInclude> {
	data: PersonGraph<I> | undefined;
	isLoading: boolean;
	isError: boolean;
}

/**
 * Traverse the graph from one Person.
 *
 * ```ts
 * const { data } = usePersonGraph(id, { contact: true });
 * ```
 *
 * Queries issued: **1 for the root** (carrying every to-one hop as a join) plus
 * **one per to-many relation that was included** — 0 possible, all
 * visible below. Never one per row: there is no loop here that could produce an
 * N+1 (charter I4, FE-REL §4.1). A branch that was not included returns
 * `undefined` from its query function, which `useLiveQuery` treats as disabled,
 * so it costs nothing while keeping the hook count static as React requires.
 */
export function usePersonGraph<const I extends PersonInclude>(
	id: string | null | undefined,
	include: I,
): PersonGraphResult<I> {
	// Widened once: the generic `I` is for the CALLER's result type; the body
	// reads the include as plain data.
	const inc = include as PersonInclude;

	// The root row, with every to-one hop joined in. One query regardless of
	// how many to-one relations the entity has.
	const root = useLiveQuery(
		(q) =>
			id !== null && id !== undefined
				? q
						.from({ row: personCollection })
						.where(({ row }) => eq(row.id, id))
						.join({ contact: contactCollection }, ({ row, contact }) =>
							eq(row.contactId, contact.id),
						)
						.select(({ row, contact }) => ({ row, contact }))
				: undefined,
		[id],
	);



	const isLoading = root.isLoading;
	const isError = root.isError;

	const rootRow = root.data?.[0];
	if (!rootRow) return { data: undefined, isLoading, isError };

	const out: Record<string, unknown> = { ...rootRow.row };
	if (inc.contact) out.contact = rootRow.contact;


	// The one cast in the file, and it is the boundary cast: `out` is assembled
	// from the include at runtime, and `PersonGraph<I>` is the same
	// shape derived from it at compile time. Every property put on `out` above is
	// guarded by the same `inc.<rel>` check the type branches on.
	return { data: out as PersonGraph<I>, isLoading, isError };
}
