// @generated by @pattern-stack/codegen from test/fixtures/demo-deal.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Update Deal Command
 * Generated by entity codegen - do not edit directly
 *
 * EXTENSION POINTS (add business logic here):
 * - Validation: Add domain validation rules (e.g., state transitions)
 * - Authorization: Check if user can modify this specific record
 * - Conflict detection: Optimistic locking, version checks
 * - Side effects: Emit events, invalidate caches, notify subscribers
 * - Audit: Log changes for compliance/debugging
 */

import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { DEAL_REPOSITORY } from '../../../constants';
import type { IDealRepository, UpdateDealInput } from '../../../domain';
import { Deal } from '../../../domain';
import type { UpdateDealDto } from '../../schemas';

@Injectable()
export class UpdateDealCommand {
	constructor(
		@Inject(DEAL_REPOSITORY)
		private readonly dealRepository: IDealRepository,
	) {}

	async execute(
		id: string,
		dto: UpdateDealDto,
		_opts?: { actor?: { tenantId?: string | null; userId?: string } },
	): Promise<Deal> {
		const existing = await this.dealRepository.findById(id);
		if (!existing) {
			throw new NotFoundException(`Deal with id ${id} not found`);
		}

		// TODO: Add pre-update validation and business rules here
		// e.g., check state transitions, verify user permissions on this record

		// Map DTO to domain input (only include defined fields)
		const input: UpdateDealInput = {
			...(dto.name !== undefined && { name: dto.name }),
			...(dto.amount !== undefined && { amount: dto.amount }),
			...(dto.stage !== undefined && { stage: dto.stage }),
			...(dto.ownerId !== undefined && { ownerId: dto.ownerId }),
			...(dto.accountId !== undefined && { accountId: dto.accountId }),
			...(dto.closeDate !== undefined && { closeDate: dto.closeDate }),
			...(dto.probability !== undefined && { probability: dto.probability }),
		};

		const updated = await this.dealRepository.update(id, input);
		if (!updated) {
			throw new NotFoundException(`Deal with id ${id} not found`);
		}

		// TODO: Add post-update side effects here (events, cache invalidation, etc.)

		return updated;
	}
}
