/**
 * Opportunity tRPC Module
 * Generated by entity codegen - do not edit directly
 *
 * Provides tRPC procedures for Opportunity CRUD operations.
 * Mounts on /api/trpc/opportunities
 */

import { Module } from '@nestjs/common';
import { TrpcModule } from './trpc/trpc.module';
import { Router, publicProcedure } from './trpc/trpc.router';
import { z } from 'zod';
import {
	opportunitySchema,
	createOpportunitySchema,
	updateOpportunitySchema,
} from '@repo/db/entities/opportunity';
import { GetOpportunityByIdQuery } from '../application/queries/opportunity/get-by-id.query';
import { ListOpportunitiesQuery } from '../application/queries/opportunity/list.query';
import { CreateOpportunityCommand } from '../application/commands/opportunity/create.command';
import { UpdateOpportunityCommand } from '../application/commands/opportunity/update.command';
import { DeleteOpportunityCommand } from '../application/commands/opportunity/delete.command';
import { OpportunitiesModule } from './opportunities.module';

@Module({
	imports: [TrpcModule, OpportunitiesModule],
})
export class OpportunityTrpcModule {
	constructor(
		private readonly getOpportunityByIdQuery: GetOpportunityByIdQuery,
		private readonly listOpportunitiesQuery: ListOpportunitiesQuery,
		private readonly createOpportunityCommand: CreateOpportunityCommand,
		private readonly updateOpportunityCommand: UpdateOpportunityCommand,
		private readonly deleteOpportunityCommand: DeleteOpportunityCommand,
	) {}

	@Router('opportunities')
	router() {
		return {
			list: publicProcedure.output(z.array(opportunitySchema)).query(async () => {
				return this.listOpportunitiesQuery.execute();
			}),

			getById: publicProcedure
				.input(z.object({ id: z.string().uuid() }))
				.output(opportunitySchema)
				.query(async ({ input }) => {
					return this.getOpportunityByIdQuery.execute(input.id);
				}),

			create: publicProcedure
				.input(createOpportunitySchema)
				.output(opportunitySchema)
				.mutation(async ({ input }) => {
					return this.createOpportunityCommand.execute(input);
				}),

			update: publicProcedure
				.input(z.object({ id: z.string().uuid(), data: updateOpportunitySchema }))
				.output(opportunitySchema)
				.mutation(async ({ input }) => {
					return this.updateOpportunityCommand.execute(input.id, input.data);
				}),

			delete: publicProcedure
				.input(z.object({ id: z.string().uuid() }))
				.output(opportunitySchema)
				.mutation(async ({ input }) => {
					return this.deleteOpportunityCommand.execute(input.id);
				}),
		};
	}
}
