// @generated by @pattern-stack/codegen from test/fixtures/opportunity.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
import { Module } from '@nestjs/common';
import { buildChangeSource } from '@shared/subsystems/sync';
import type {
  DetectionConfig,
  IChangeSource,
  PollFetchCallback,
} from '@shared/subsystems/sync';
import type { Opportunity } from '../domain';

const OPPORTUNITY_DETECTION_CONFIGS: Record<string, DetectionConfig> = {
  "hubspot-crm": {
    "mode": "poll",
    "poll": {
      "cursor": {
        "kind": "timestamp",
        "field": "hs_lastmodifieddate"
      }
    },
    "mapping": [
      {
        "source": "dealname",
        "target": "name"
      },
      {
        "source": "amount",
        "target": "amount",
        "transform": "decimal-string"
      },
      {
        "source": "closedate",
        "target": "expected_close_date",
        "transform": "date-iso"
      },
      {
        "source": "hubspot_owner_id",
        "target": "owner_id"
      }
    ],
    "filters": [
      {
        "field": "pipeline",
        "op": "neq",
        "value": "archived"
      }
    ]
  },
  "salesforce-crm": {
    "mode": "poll",
    "poll": {
      "cursor": {
        "kind": "systemModstamp",
        "field": "SystemModstamp"
      }
    },
    "mapping": [
      {
        "source": "Name",
        "target": "name"
      },
      {
        "source": "Amount",
        "target": "amount",
        "transform": "decimal-string"
      },
      {
        "source": "CloseDate",
        "target": "expected_close_date",
        "transform": "date-iso"
      },
      {
        "source": "OwnerId",
        "target": "owner_id"
      }
    ],
    "filters": [
      {
        "field": "IsDeleted",
        "op": "eq",
        "value": false
      },
      {
        "field": "StageName",
        "op": "neq",
        "value": "Closed Lost"
      }
    ]
  }
};

export const OPPORTUNITY_POLL_FETCH_REGISTRY = Symbol('OPPORTUNITY_POLL_FETCH_REGISTRY');
export const OPPORTUNITY_CHANGE_SOURCES = Symbol('OPPORTUNITY_CHANGE_SOURCES');

@Module({
  providers: [
    {
      provide: OPPORTUNITY_CHANGE_SOURCES,
      inject: [OPPORTUNITY_POLL_FETCH_REGISTRY],
      useFactory: (
        fetches: Record<string, PollFetchCallback<Opportunity>>,
      ): ReadonlyMap<string, IChangeSource<Opportunity>> =>
        new Map(
          Object.entries(OPPORTUNITY_DETECTION_CONFIGS).map(([provider, cfg]) => {
            const fetch = fetches[provider];
            if (!fetch) {
              throw new Error(
                `OpportunitySyncSourceModule: missing fetch callback for provider '${provider}' in OPPORTUNITY_POLL_FETCH_REGISTRY`,
              );
            }
            return [provider, buildChangeSource(cfg, fetch)];
          }),
        ),
    },
  ],
  exports: [OPPORTUNITY_CHANGE_SOURCES],
})
export class OpportunitySyncSourceModule {}
