// @generated by @pattern-stack/codegen from test/fixtures/opportunity.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use the entity YAML or a base-class behavior config.
/**
 * Opportunity sync-source providers
 * Generated by entity codegen — do not edit directly.
 *
 * ADR-033.2: typed provider artifacts. Consumers type their registry as
 * Record<OpportunityProvider, …> to get compile-time provider-key checks.
 * Order matches YAML detection: insertion order.
 */

export const OPPORTUNITY_PROVIDERS = ['hubspot-crm', 'salesforce-crm'] as const;

export type OpportunityProvider = (typeof OPPORTUNITY_PROVIDERS)[number];
