// @generated by @pattern-stack/codegen from test/fixtures/entities/deal_state.yaml — DO NOT EDIT. Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`. To extend, use a pattern (src/patterns/*.pattern.ts) or the entity YAML.
import { z } from 'zod';
import { CreateDealStateSchema } from './create-deal_state.dto';

export const UpdateDealStateSchema = CreateDealStateSchema.partial();

export type UpdateDealStateDto = z.infer<typeof UpdateDealStateSchema>;
