/**
 * Deal Repository Interface
 * Generated by entity codegen - do not edit directly
 */

import type { Deal } from './deal.entity';

/**
 * Type-safe eager loading options.
 * Pass to repository methods to include related entities.
 */
export type DealWith = {
	owner?: boolean;
	account?: boolean;
};

/**
 * Domain-level input types for repository operations.
 */
export type CreateDealInput = {
	name: string;
	amount?: number | null;
	stage: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost';
	ownerId: string;
	accountId: string;
	closeDate?: Date | null;
	probability?: number | null;
};

export type UpdateDealInput = Partial<CreateDealInput>;

export interface IDealRepository {
	create(input: CreateDealInput): Promise<Deal>;
	findById(id: string, include?: DealWith): Promise<Deal | null>;
	findAll(include?: DealWith): Promise<Deal[]>;
	update(id: string, input: UpdateDealInput): Promise<Deal | null>;
	delete(id: string): Promise<Deal | null>;
	// Soft delete recovery methods
	restore(id: string): Promise<Deal | null>;
	findWithDeleted(): Promise<Deal[]>;
	findOnlyDeleted(): Promise<Deal[]>;
	findByOwnerId(id: string, include?: DealWith): Promise<Deal[]>;
	findByAccountId(id: string, include?: DealWith): Promise<Deal[]>;
	// Declarative queries (from queries: block in entity YAML)
	findByOwnerId(ownerId: string): Promise<Deal[]>;
	findByAccountId(accountId: string): Promise<Deal[]>;
	findByStage(stage: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost'): Promise<Deal[]>;
	findByOwnerIdAndStage(ownerId: string, stage: 'prospecting' | 'qualification' | 'proposal' | 'negotiation' | 'closed_won' | 'closed_lost'): Promise<Deal[]>;
}
