// @generated by @pattern-stack/codegen from entities/deal_state.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import type { FieldMeta, FieldType, FieldImportance } from './field-meta';
import type { DealState } from '@repo/db/entities/deal_state';

export const dealStateFields: Record<string, FieldMeta<DealState>> = {
	tenantId: {
		field: 'tenantId',
		label: 'Tenant Id',
		type: 'reference' as FieldType,
		importance: 'secondary' as FieldImportance,
		reference: 'tenants',
	},
	name: {
		field: 'name',
		label: 'Name',
		type: 'text' as FieldType,
		importance: 'primary' as FieldImportance,
		isKeyField: true,
		keyFieldOrder: 0,
	},
	sortOrder: {
		field: 'sortOrder',
		label: 'Sort Order',
		type: 'number' as FieldType,
		importance: 'primary' as FieldImportance,
	},
	isClosed: {
		field: 'isClosed',
		label: 'Is Closed',
		type: 'boolean' as FieldType,
		importance: 'primary' as FieldImportance,
	},
};

export const dealStateMetadata = {
	name: 'deal_state',
	plural: 'deal_states',
	displayName: 'Deal State',
	displayNamePlural: 'Deal States',

	fields: dealStateFields,

	primaryFields: [
		'name',
		'sortOrder',
		'isClosed',
	],
	keyFields: [
		'name',
	],
	searchFields: [

	],
	defaultSort: { field: 'id', direction: 'desc' as const },

	capabilities: {
		create: true,
		update: true,
		delete: true,
		list: true,
		get: true,
	},
} as const;
