// @generated by @pattern-stack/codegen from entities/person.yaml — DO NOT EDIT.
// Hand edits are overwritten on re-emit. Regenerate with `bun run codegen`.

import type { FieldMeta, FieldType, FieldImportance } from './field-meta';
import type { Person } from '@repo/db/entities/person';

export const personFields: Record<string, FieldMeta<Person>> = {
	tenantId: {
		field: 'tenantId',
		label: 'Tenant Id',
		type: 'reference' as FieldType,
		importance: 'secondary' as FieldImportance,
		group: 'system',
		visible: false,
		reference: 'tenants',
	},
	email: {
		field: 'email',
		label: 'Email',
		type: 'email' as FieldType,
		importance: 'primary' as FieldImportance,
		placeholder: 'name@example.com',
		help: 'Primary contact address.',
		isKeyField: true,
		keyFieldOrder: 1,
	},
	firstName: {
		field: 'firstName',
		label: 'First Name',
		type: 'text' as FieldType,
		importance: 'primary' as FieldImportance,
		isKeyField: true,
		keyFieldOrder: 0,
	},
	lastName: {
		field: 'lastName',
		label: 'Last Name',
		type: 'text' as FieldType,
		importance: 'primary' as FieldImportance,
	},
	deletedAt: {
		field: 'deletedAt',
		label: 'Deleted',
		type: 'datetime' as FieldType,
		importance: 'tertiary' as FieldImportance,
		format: { dateFormat: 'relative' },
	},
};

export const personMetadata = {
	name: 'person',
	plural: 'persons',
	displayName: 'Person',
	displayNamePlural: 'Persons',

	fields: personFields,

	primaryFields: [
		'email',
		'firstName',
		'lastName',
	],
	keyFields: [
		'firstName',
		'email',
	],
	searchFields: [

	],
	defaultSort: { field: 'id', direction: 'desc' as const },

	capabilities: {
		create: true,
		update: true,
		delete: true,
		list: true,
		get: true,
	},
} as const;
